// artilist_records.js — the artifact table.
// C ref: include/artilist.h
//
// GENERATED from the header's 36 A(...) entries, not hand-written. The header
// is an X-macro file: included repeatedly with a different #define A(...),
// which is how one table yields the names array, the ART_* enum and these
// records.
//
// Two parsing hazards, both hit while writing the generator:
//   - fields 6..8 hold macros with commas inside parens, so splitting on
//     commas needs parenthesis-depth matching
//   - a C comment can sit INSIDE a field (the Heart of Ahriman's attack is
//     preceded by one), so comments must be stripped before parsing
//
// attk/defn/cary ARE evaluated, using the macro table at include/artilist.h:35
//   NO_ATTK/NO_DFNS/NO_CARY {0,0,0,0}   DFNS(c)/CARY(c) {0,c,0,0}
//   PHYS(a,b) {0,AD_PHYS,a,b}, and likewise DRLI COLD FIRE ELEC STUN, plus
//   POIS(a,b) {0,AD_DRST,a,b}  <- note POIS maps to AD_DRST, not AD_POIS
// Struct order is C's: {aatyp, adtyp, damn, damd}. adtyp is kept as its AD_*
// NAME rather than a number, because the AD_* values are not all ported yet
// and a wrong number here would silently change which artifacts match.
//
// spfx and cspfx ARE evaluated to numbers from include/artifact.h, because
// every consumer tests them with '&'. The first version kept them as source
// text, which made `weap.spfx & SPFX_DBONUS` coerce to NaN and silently take
// the wrong branch in spec_applies -- it read as working and was not.
//
// Everything else keeps C's field names and C's order, as source text.
// Index 0 is the sentinel, so ART_NONARTIFACT === 0 and C's
// `oart != &artilist[ART_NONARTIFACT]` is an index-zero test here.
export const artilist = [
    {"nam": "", "typ": "STRANGE_OBJECT", "spfx": 0, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "0", "cost": "0L", "color": "NO_COLOR", "bn": "NONARTIFACT", "alignment": "A_NONE"},
    {"nam": "Excalibur", "typ": "LONG_SWORD", "spfx": 663, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 10}, "defn": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "PM_KNIGHT", "race": "NON_PM", "gift_status": "0", "gift_value": "10", "cost": "4000L", "color": "NO_COLOR", "bn": "EXCALIBUR", "alignment": "A_LAWFUL"},
    {"nam": "Stormbringer", "typ": "RUNESWORD", "spfx": 454, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 5, "damd": 2}, "defn": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "9", "cost": "8000L", "color": "NO_COLOR", "bn": "STORMBRINGER", "alignment": "A_CHAOTIC"},
    {"nam": "Mjollnir", "typ": "WAR_HAMMER", "spfx": 66, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_ELEC", "damn": 5, "damd": 24}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "PM_VALKYRIE", "race": "NON_PM", "gift_status": "0", "gift_value": "8", "cost": "4000L", "color": "NO_COLOR", "bn": "MJOLLNIR", "alignment": "A_NEUTRAL"},
    {"nam": "Cleaver", "typ": "BATTLE_AXE", "spfx": 2, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 3, "damd": 6}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "PM_BARBARIAN", "race": "NON_PM", "gift_status": "0", "gift_value": "8", "cost": "1500L", "color": "NO_COLOR", "bn": "CLEAVER", "alignment": "A_NEUTRAL"},
    {"nam": "Grimtooth", "typ": "ORCISH_DAGGER", "spfx": 8388642, "cspfx": 0, "mtype": "M2_ELF", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 2, "damd": 6}, "defn": {"aatyp": 0, "adtyp": "AD_DRST", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "FLING_POISON", "role": "NON_PM", "race": "PM_ORC", "gift_status": "0", "gift_value": "5", "cost": "1200L", "color": "CLR_RED", "bn": "GRIMTOOTH", "alignment": "A_CHAOTIC"},
    {"nam": "Orcrist", "typ": "ELVEN_BROADSWORD", "spfx": 8388640, "cspfx": 0, "mtype": "M2_ORC", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "PM_ELF", "gift_status": "3", "gift_value": "4", "cost": "2000L", "color": "CLR_BRIGHT_BLUE", "bn": "ORCRIST", "alignment": "A_CHAOTIC"},
    {"nam": "Sting", "typ": "ELVEN_DAGGER", "spfx": 8388640, "cspfx": 0, "mtype": "M2_ORC", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "PM_ELF", "gift_status": "3", "gift_value": "1", "cost": "800L", "color": "CLR_BRIGHT_BLUE", "bn": "STING", "alignment": "A_CHAOTIC"},
    {"nam": "Magicbane", "typ": "ATHAME", "spfx": 194, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_STUN", "damn": 3, "damd": 4}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "PM_WIZARD", "race": "NON_PM", "gift_status": "0", "gift_value": "7", "cost": "3500L", "color": "NO_COLOR", "bn": "MAGICBANE", "alignment": "A_NEUTRAL"},
    {"nam": "Frost Brand", "typ": "LONG_SWORD", "spfx": 194, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_COLD", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_COLD", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "SNOWSTORM", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "9", "cost": "3000L", "color": "NO_COLOR", "bn": "FROST_BRAND", "alignment": "A_NONE"},
    {"nam": "Fire Brand", "typ": "LONG_SWORD", "spfx": 194, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_FIRE", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_FIRE", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "FIRESTORM", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "5", "cost": "3000L", "color": "NO_COLOR", "bn": "FIRE_BRAND", "alignment": "A_NONE"},
    {"nam": "Dragonbane", "typ": "BROADSWORD", "spfx": 69206018, "cspfx": 0, "mtype": "S_DRAGON", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "5", "cost": "500L", "color": "NO_COLOR", "bn": "DRAGONBANE", "alignment": "A_NONE"},
    {"nam": "Demonbane", "typ": "SILVER_MACE", "spfx": 8388610, "cspfx": 0, "mtype": "M2_DEMON", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "BANISH", "role": "PM_CLERIC", "race": "NON_PM", "gift_status": "1", "gift_value": "3", "cost": "2500L", "color": "NO_COLOR", "bn": "DEMONBANE", "alignment": "A_LAWFUL"},
    {"nam": "Werebane", "typ": "SILVER_SABER", "spfx": 8388610, "cspfx": 0, "mtype": "M2_WERE", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_WERE", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "1", "gift_value": "4", "cost": "1500L", "color": "NO_COLOR", "bn": "WEREBANE", "alignment": "A_NONE"},
    {"nam": "Grayswandir", "typ": "SILVER_SABER", "spfx": 2050, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "10", "cost": "8000L", "color": "NO_COLOR", "bn": "GRAYSWANDIR", "alignment": "A_LAWFUL"},
    {"nam": "Giantslayer", "typ": "LONG_SWORD", "spfx": 8388610, "cspfx": 0, "mtype": "M2_GIANT", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "4", "cost": "200L", "color": "NO_COLOR", "bn": "GIANTSLAYER", "alignment": "A_NEUTRAL"},
    {"nam": "Ogresmasher", "typ": "WAR_HAMMER", "spfx": 2097154, "cspfx": 0, "mtype": "S_OGRE", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "1", "cost": "200L", "color": "NO_COLOR", "bn": "OGRESMASHER", "alignment": "A_NONE"},
    {"nam": "Trollsbane", "typ": "MORNING_STAR", "spfx": 2113538, "cspfx": 0, "mtype": "S_TROLL", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "1", "cost": "200L", "color": "NO_COLOR", "bn": "TROLLSBANE", "alignment": "A_NONE"},
    {"nam": "Vorpal Blade", "typ": "LONG_SWORD", "spfx": 1026, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 1}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "1", "gift_value": "5", "cost": "4000L", "color": "NO_COLOR", "bn": "VORPAL_BLADE", "alignment": "A_NEUTRAL"},
    {"nam": "Snickersnee", "typ": "KATANA", "spfx": 2, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 0, "damd": 8}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "PM_SAMURAI", "race": "NON_PM", "gift_status": "0", "gift_value": "8", "cost": "1200L", "color": "NO_COLOR", "bn": "SNICKERSNEE", "alignment": "A_LAWFUL"},
    {"nam": "Sunsword", "typ": "LONG_SWORD", "spfx": 8388610, "cspfx": 0, "mtype": "M2_UNDEAD", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_BLND", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "BLINDING_RAY", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "6", "cost": "1500L", "color": "NO_COLOR", "bn": "SUNSWORD", "alignment": "A_LAWFUL"},
    {"nam": "The Orb of Detection", "typ": "CRYSTAL_BALL", "spfx": 7, "cspfx": 69632, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "inv": "INVIS", "role": "PM_ARCHEOLOGIST", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "ORB_OF_DETECTION", "alignment": "A_LAWFUL"},
    {"nam": "The Heart of Ahriman", "typ": "LUCKSTONE", "spfx": 7, "cspfx": 8192, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "LEVITATION", "role": "PM_BARBARIAN", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "HEART_OF_AHRIMAN", "alignment": "A_NEUTRAL"},
    {"nam": "The Sceptre of Might", "typ": "MACE", "spfx": 16777223, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "CONFLICT", "role": "PM_CAVE_DWELLER", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "SCEPTRE_OF_MIGHT", "alignment": "A_LAWFUL"},
    {"nam": "The Palantir of Westernesse", "typ": "CRYSTAL_BALL", "spfx": 7, "cspfx": 86016, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "TAMING", "role": "NON_PM", "race": "PM_ELF", "gift_status": "0", "gift_value": "12", "cost": "8000L", "color": "NO_COLOR", "bn": "PALANTIR_OF_WESTERNESSE", "alignment": "A_CHAOTIC"},
    {"nam": "The Staff of Aesculapius", "typ": "QUARTERSTAFF", "spfx": 16711, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "HEALING", "role": "PM_HEALER", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "5000L", "color": "NO_COLOR", "bn": "STAFF_OF_AESCULAPIUS", "alignment": "A_NEUTRAL"},
    {"nam": "The Magic Mirror of Merlin", "typ": "MIRROR", "spfx": 15, "cspfx": 4096, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "inv": "0", "role": "PM_KNIGHT", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "1500L", "color": "NO_COLOR", "bn": "MAGIC_MIRROR_OF_MERLIN", "alignment": "A_LAWFUL"},
    {"nam": "The Eyes of the Overworld", "typ": "LENSES", "spfx": 33554439, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "ENLIGHTENING", "role": "PM_MONK", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "EYES_OF_THE_OVERWORLD", "alignment": "A_NEUTRAL"},
    {"nam": "The Mitre of Holiness", "typ": "HELM_OF_BRILLIANCE", "spfx": 142606343, "cspfx": 0, "mtype": "M2_UNDEAD", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_FIRE", "damn": 0, "damd": 0}, "inv": "ENERGY_BOOST", "role": "PM_CLERIC", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2000L", "color": "NO_COLOR", "bn": "MITRE_OF_HOLINESS", "alignment": "A_LAWFUL"},
    {"nam": "The Longbow of Diana", "typ": "BOW", "spfx": 67108871, "cspfx": 4096, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "CREATE_AMMO", "role": "PM_RANGER", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "4000L", "color": "NO_COLOR", "bn": "LONGBOW_OF_DIANA", "alignment": "A_CHAOTIC"},
    {"nam": "The Master Key of Thievery", "typ": "SKELETON_KEY", "spfx": 15, "cspfx": 393248, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "UNTRAP", "role": "PM_ROGUE", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "3500L", "color": "NO_COLOR", "bn": "MASTER_KEY_OF_THIEVERY", "alignment": "A_CHAOTIC"},
    {"nam": "The Tsurugi of Muramasa", "typ": "TSURUGI", "spfx": 134743047, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 0, "damd": 8}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "PM_SAMURAI", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "4500L", "color": "NO_COLOR", "bn": "TSURUGI_OF_MURAMASA", "alignment": "A_LAWFUL"},
    {"nam": "The Platinum Yendorian Express Card", "typ": "CREDIT_CARD", "spfx": 135, "cspfx": 69632, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "inv": "CHARGE_OBJ", "role": "PM_TOURIST", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "7000L", "color": "NO_COLOR", "bn": "YENDORIAN_EXPRESS_CARD", "alignment": "A_NEUTRAL"},
    {"nam": "The Orb of Fate", "typ": "CRYSTAL_BALL", "spfx": 524295, "cspfx": 196640, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "LEV_TELE", "role": "PM_VALKYRIE", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "3500L", "color": "NO_COLOR", "bn": "ORB_OF_FATE", "alignment": "A_NEUTRAL"},
    {"nam": "The Eye of the Aethiopica", "typ": "AMULET_OF_ESP", "spfx": 7, "cspfx": 98304, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "CREATE_PORTAL", "role": "PM_WIZARD", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "4000L", "color": "NO_COLOR", "bn": "EYE_OF_THE_AETHIOPICA", "alignment": "A_NEUTRAL"},
    {"nam": "0", "typ": "0", "spfx": 0, "cspfx": 0, "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "0", "cost": "0L", "color": "NO_COLOR", "bn": "TERMINATOR", "alignment": "A_NONE"},
];
