// artilist_records.js — the artifact table.
// C ref: include/artilist.h
//
// GENERATED from the 36 A(...) entries in the header, not hand-written.
// include/artilist.h is an X-macro file: it is included repeatedly with a
// different #define A(...) each time, which is how one table yields the names
// array, the ART_* enum and these records.
//
// Fields keep C"s names and C"s order. Values that are macros in the header
// (NO_ATTK, PHYS(4,0), CARY(AD_MAGM), SPFX_* expressions) are kept as SOURCE
// TEXT rather than evaluated -- evaluating them needs the attack and defence
// macro families, which are not ported, and a plausible-looking wrong value
// here would silently change which artifacts match.
//
// Index 0 is the sentinel, so ART_NONARTIFACT === 0 and the C idiom
// `oart != &artilist[ART_NONARTIFACT]` is an index-zero test here.
//
// The ART_* indices live in js/artilist_data.js and are verified to line up
// with this order.
export const artilist = [
    { nam: "", typ: "STRANGE_OBJECT", spfx: "0", cspfx: "0", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "0", gift_value: "0", cost: "0L", color: "NO_COLOR", bn: "NONARTIFACT" },
    { nam: "Excalibur", typ: "LONG_SWORD", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_SEEK | SPFX_DEFN | SPFX_INTEL | SPFX_SEARCH)", cspfx: "0", mtype: "0", attk: "PHYS(5, 10)", defn: "DRLI(0, 0)", cary: "NO_CARY", inv: "0", alignment: "A_LAWFUL", role: "PM_KNIGHT", race: "NON_PM", gift_status: "0", gift_value: "10", cost: "4000L", color: "NO_COLOR", bn: "EXCALIBUR" },
    { nam: "Stormbringer", typ: "RUNESWORD", spfx: "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN | SPFX_INTEL | SPFX_DRLI)", cspfx: "0", mtype: "0", attk: "DRLI(5, 2)", defn: "DRLI(0, 0)", cary: "NO_CARY", inv: "0", alignment: "A_CHAOTIC", role: "NON_PM", race: "NON_PM", gift_status: "0", gift_value: "9", cost: "8000L", color: "NO_COLOR", bn: "STORMBRINGER" },
    { nam: "Mjollnir", typ: "WAR_HAMMER", spfx: "/* Mjo:llnir */ (SPFX_RESTR | SPFX_ATTK)", cspfx: "0", mtype: "0", attk: "ELEC(5, 24)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NEUTRAL", role: "PM_VALKYRIE", race: "NON_PM", gift_status: "0", gift_value: "8", cost: "4000L", color: "NO_COLOR", bn: "MJOLLNIR" },
    { nam: "Cleaver", typ: "BATTLE_AXE", spfx: "SPFX_RESTR", cspfx: "0", mtype: "0", attk: "PHYS(3, 6)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NEUTRAL", role: "PM_BARBARIAN", race: "NON_PM", gift_status: "0", gift_value: "8", cost: "1500L", color: "NO_COLOR", bn: "CLEAVER" },
    { nam: "Grimtooth", typ: "ORCISH_DAGGER", spfx: "(SPFX_RESTR | SPFX_WARN | SPFX_DFLAG2)", cspfx: "0", mtype: "M2_ELF", attk: "PHYS(2, 6)", defn: "POIS(0,0)", cary: "NO_CARY", inv: "FLING_POISON", alignment: "A_CHAOTIC", role: "NON_PM", race: "PM_ORC", gift_status: "0", gift_value: "5", cost: "1200L", color: "CLR_RED", bn: "GRIMTOOTH" },
    { nam: "Orcrist", typ: "ELVEN_BROADSWORD", spfx: "(SPFX_WARN | SPFX_DFLAG2)", cspfx: "0", mtype: "M2_ORC", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_CHAOTIC", role: "NON_PM", race: "PM_ELF", gift_status: "3", gift_value: "4", cost: "2000L", color: "CLR_BRIGHT_BLUE", bn: "ORCRIST" },
    { nam: "Sting", typ: "ELVEN_DAGGER", spfx: "(SPFX_WARN | SPFX_DFLAG2)", cspfx: "0", mtype: "M2_ORC", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_CHAOTIC", role: "NON_PM", race: "PM_ELF", gift_status: "3", gift_value: "1", cost: "800L", color: "CLR_BRIGHT_BLUE", bn: "STING" },
    { nam: "Magicbane", typ: "ATHAME", spfx: "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN)", cspfx: "0", mtype: "0", attk: "STUN(3, 4)", defn: "DFNS(AD_MAGM)", cary: "NO_CARY", inv: "0", alignment: "A_NEUTRAL", role: "PM_WIZARD", race: "NON_PM", gift_status: "0", gift_value: "7", cost: "3500L", color: "NO_COLOR", bn: "MAGICBANE" },
    { nam: "Frost Brand", typ: "LONG_SWORD", spfx: "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN)", cspfx: "0", mtype: "0", attk: "COLD(5, 0)", defn: "COLD(0, 0)", cary: "NO_CARY", inv: "SNOWSTORM", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "0", gift_value: "9", cost: "3000L", color: "NO_COLOR", bn: "FROST_BRAND" },
    { nam: "Fire Brand", typ: "LONG_SWORD", spfx: "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN)", cspfx: "0", mtype: "0", attk: "FIRE(5, 0)", defn: "FIRE(0, 0)", cary: "NO_CARY", inv: "FIRESTORM", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "0", gift_value: "5", cost: "3000L", color: "NO_COLOR", bn: "FIRE_BRAND" },
    { nam: "Dragonbane", typ: "BROADSWORD", spfx: "(SPFX_RESTR | SPFX_DCLAS | SPFX_REFLECT)", cspfx: "0", mtype: "S_DRAGON", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "2", gift_value: "5", cost: "500L", color: "NO_COLOR", bn: "DRAGONBANE" },
    { nam: "Demonbane", typ: "SILVER_MACE", spfx: "(SPFX_RESTR | SPFX_DFLAG2)", cspfx: "0", mtype: "M2_DEMON", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "BANISH", alignment: "A_LAWFUL", role: "PM_CLERIC", race: "NON_PM", gift_status: "1", gift_value: "3", cost: "2500L", color: "NO_COLOR", bn: "DEMONBANE" },
    { nam: "Werebane", typ: "SILVER_SABER", spfx: "(SPFX_RESTR | SPFX_DFLAG2)", cspfx: "0", mtype: "M2_WERE", attk: "PHYS(5, 0)", defn: "DFNS(AD_WERE)", cary: "NO_CARY", inv: "0", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "1", gift_value: "4", cost: "1500L", color: "NO_COLOR", bn: "WEREBANE" },
    { nam: "Grayswandir", typ: "SILVER_SABER", spfx: "(SPFX_RESTR | SPFX_HALRES)", cspfx: "0", mtype: "0", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_LAWFUL", role: "NON_PM", race: "NON_PM", gift_status: "0", gift_value: "10", cost: "8000L", color: "NO_COLOR", bn: "GRAYSWANDIR" },
    { nam: "Giantslayer", typ: "LONG_SWORD", spfx: "(SPFX_RESTR | SPFX_DFLAG2)", cspfx: "0", mtype: "M2_GIANT", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NEUTRAL", role: "NON_PM", race: "NON_PM", gift_status: "2", gift_value: "4", cost: "200L", color: "NO_COLOR", bn: "GIANTSLAYER" },
    { nam: "Ogresmasher", typ: "WAR_HAMMER", spfx: "(SPFX_RESTR | SPFX_DCLAS)", cspfx: "0", mtype: "S_OGRE", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "2", gift_value: "1", cost: "200L", color: "NO_COLOR", bn: "OGRESMASHER" },
    { nam: "Trollsbane", typ: "MORNING_STAR", spfx: "(SPFX_RESTR | SPFX_DCLAS | SPFX_REGEN)", cspfx: "0", mtype: "S_TROLL", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "2", gift_value: "1", cost: "200L", color: "NO_COLOR", bn: "TROLLSBANE" },
    { nam: "Vorpal Blade", typ: "LONG_SWORD", spfx: "(SPFX_RESTR | SPFX_BEHEAD)", cspfx: "0", mtype: "0", attk: "PHYS(5, 1)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NEUTRAL", role: "NON_PM", race: "NON_PM", gift_status: "1", gift_value: "5", cost: "4000L", color: "NO_COLOR", bn: "VORPAL_BLADE" },
    { nam: "Snickersnee", typ: "KATANA", spfx: "SPFX_RESTR", cspfx: "0", mtype: "0", attk: "PHYS(0, 8)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_LAWFUL", role: "PM_SAMURAI", race: "NON_PM", gift_status: "0", gift_value: "8", cost: "1200L", color: "NO_COLOR", bn: "SNICKERSNEE" },
    { nam: "Sunsword", typ: "LONG_SWORD", spfx: "(SPFX_RESTR | SPFX_DFLAG2)", cspfx: "0", mtype: "M2_UNDEAD", attk: "PHYS(5, 0)", defn: "DFNS(AD_BLND)", cary: "NO_CARY", inv: "BLINDING_RAY", alignment: "A_LAWFUL", role: "NON_PM", race: "NON_PM", gift_status: "0", gift_value: "6", cost: "1500L", color: "NO_COLOR", bn: "SUNSWORD" },
    { nam: "The Orb of Detection", typ: "CRYSTAL_BALL", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", cspfx: "(SPFX_ESP | SPFX_HSPDAM)", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "CARY(AD_MAGM)", inv: "INVIS", alignment: "A_LAWFUL", role: "PM_ARCHEOLOGIST", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "2500L", color: "NO_COLOR", bn: "ORB_OF_DETECTION" },
    { nam: "The Heart of Ahriman", typ: "LUCKSTONE", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", cspfx: "SPFX_STLTH", mtype: "0", attk: "/* this stone does double damage if used as a projectile weapon */ PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "LEVITATION", alignment: "A_NEUTRAL", role: "PM_BARBARIAN", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "2500L", color: "NO_COLOR", bn: "HEART_OF_AHRIMAN" },
    { nam: "The Sceptre of Might", typ: "MACE", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_DALIGN)", cspfx: "0", mtype: "0", attk: "PHYS(5, 0)", defn: "DFNS(AD_MAGM)", cary: "NO_CARY", inv: "CONFLICT", alignment: "A_LAWFUL", role: "PM_CAVE_DWELLER", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "2500L", color: "NO_COLOR", bn: "SCEPTRE_OF_MIGHT" },
    { nam: "The Palantir of Westernesse", typ: "CRYSTAL_BALL", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", cspfx: "(SPFX_ESP | SPFX_REGEN | SPFX_HSPDAM)", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "NO_CARY", inv: "TAMING", alignment: "A_CHAOTIC", role: "NON_PM", race: "PM_ELF", gift_status: "0", gift_value: "12", cost: "8000L", color: "NO_COLOR", bn: "PALANTIR_OF_WESTERNESSE" },
    { nam: "The Staff of Aesculapius", typ: "QUARTERSTAFF", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_ATTK | SPFX_INTEL | SPFX_DRLI | SPFX_REGEN)", cspfx: "0", mtype: "0", attk: "DRLI(0, 0)", defn: "DRLI(0, 0)", cary: "NO_CARY", inv: "HEALING", alignment: "A_NEUTRAL", role: "PM_HEALER", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "5000L", color: "NO_COLOR", bn: "STAFF_OF_AESCULAPIUS" },
    { nam: "The Magic Mirror of Merlin", typ: "MIRROR", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_SPEAK)", cspfx: "SPFX_ESP", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "CARY(AD_MAGM)", inv: "0", alignment: "A_LAWFUL", role: "PM_KNIGHT", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "1500L", color: "NO_COLOR", bn: "MAGIC_MIRROR_OF_MERLIN" },
    { nam: "The Eyes of the Overworld", typ: "LENSES", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_XRAY)", cspfx: "0", mtype: "0", attk: "NO_ATTK", defn: "DFNS(AD_MAGM)", cary: "NO_CARY", inv: "ENLIGHTENING", alignment: "A_NEUTRAL", role: "PM_MONK", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "2500L", color: "NO_COLOR", bn: "EYES_OF_THE_OVERWORLD" },
    { nam: "The Mitre of Holiness", typ: "HELM_OF_BRILLIANCE", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_DFLAG2 | SPFX_INTEL | SPFX_PROTECT)", cspfx: "0", mtype: "M2_UNDEAD", attk: "NO_ATTK", defn: "NO_DFNS", cary: "CARY(AD_FIRE)", inv: "ENERGY_BOOST", alignment: "A_LAWFUL", role: "PM_CLERIC", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "2000L", color: "NO_COLOR", bn: "MITRE_OF_HOLINESS" },
    { nam: "The Longbow of Diana", typ: "BOW", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_REFLECT)", cspfx: "SPFX_ESP", mtype: "0", attk: "PHYS(5, 0)", defn: "NO_DFNS", cary: "NO_CARY", inv: "CREATE_AMMO", alignment: "A_CHAOTIC", role: "PM_RANGER", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "4000L", color: "NO_COLOR", bn: "LONGBOW_OF_DIANA" },
    { nam: "The Master Key of Thievery", typ: "SKELETON_KEY", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_SPEAK)", cspfx: "(SPFX_WARN | SPFX_TCTRL | SPFX_HPHDAM)", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "NO_CARY", inv: "UNTRAP", alignment: "A_CHAOTIC", role: "PM_ROGUE", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "3500L", color: "NO_COLOR", bn: "MASTER_KEY_OF_THIEVERY" },
    { nam: "The Tsurugi of Muramasa", typ: "TSURUGI", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_BEHEAD | SPFX_LUCK | SPFX_PROTECT)", cspfx: "0", mtype: "0", attk: "PHYS(0, 8)", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_LAWFUL", role: "PM_SAMURAI", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "4500L", color: "NO_COLOR", bn: "TSURUGI_OF_MURAMASA" },
    { nam: "The Platinum Yendorian Express Card", typ: "CREDIT_CARD", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_DEFN)", cspfx: "(SPFX_ESP | SPFX_HSPDAM)", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "CARY(AD_MAGM)", inv: "CHARGE_OBJ", alignment: "A_NEUTRAL", role: "PM_TOURIST", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "7000L", color: "NO_COLOR", bn: "YENDORIAN_EXPRESS_CARD" },
    { nam: "The Orb of Fate", typ: "CRYSTAL_BALL", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_LUCK)", cspfx: "(SPFX_WARN | SPFX_HSPDAM | SPFX_HPHDAM)", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "NO_CARY", inv: "LEV_TELE", alignment: "A_NEUTRAL", role: "PM_VALKYRIE", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "3500L", color: "NO_COLOR", bn: "ORB_OF_FATE" },
    { nam: "The Eye of the Aethiopica", typ: "AMULET_OF_ESP", spfx: "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", cspfx: "(SPFX_EREGEN | SPFX_HSPDAM)", mtype: "0", attk: "NO_ATTK", defn: "DFNS(AD_MAGM)", cary: "NO_CARY", inv: "CREATE_PORTAL", alignment: "A_NEUTRAL", role: "PM_WIZARD", race: "NON_PM", gift_status: "0", gift_value: "12", cost: "4000L", color: "NO_COLOR", bn: "EYE_OF_THE_AETHIOPICA" },
    { nam: "0", typ: "0", spfx: "0", cspfx: "0", mtype: "0", attk: "NO_ATTK", defn: "NO_DFNS", cary: "NO_CARY", inv: "0", alignment: "A_NONE", role: "NON_PM", race: "NON_PM", gift_status: "0", gift_value: "0", cost: "0L", color: "NO_COLOR", bn: "TERMINATOR" },
];
