// artilist_data.js — GENERATED by tools/gen-artifacts.mjs. Do not edit.
// Source: include/artilist.h, the A() entries makedefs numbers into ART_*.
//
// Index is positional and matches obj->oartifact. Index 0 is artilist.h's
// A("") dummy, which is why oartifact==0 means "not an artifact" and is_art()
// on an ordinary object is always false.

export const ART_NONARTIFACT = 0;
export const ART_EXCALIBUR = 1;
export const ART_STORMBRINGER = 2;
export const ART_MJOLLNIR = 3;
export const ART_CLEAVER = 4;
export const ART_GRIMTOOTH = 5;
export const ART_ORCRIST = 6;
export const ART_STING = 7;
export const ART_MAGICBANE = 8;
export const ART_FROST_BRAND = 9;
export const ART_FIRE_BRAND = 10;
export const ART_DRAGONBANE = 11;
export const ART_DEMONBANE = 12;
export const ART_WEREBANE = 13;
export const ART_GRAYSWANDIR = 14;
export const ART_GIANTSLAYER = 15;
export const ART_OGRESMASHER = 16;
export const ART_TROLLSBANE = 17;
export const ART_VORPAL_BLADE = 18;
export const ART_SNICKERSNEE = 19;
export const ART_SUNSWORD = 20;
export const ART_ORB_OF_DETECTION = 21;
export const ART_HEART_OF_AHRIMAN = 22;
export const ART_SCEPTRE_OF_MIGHT = 23;
export const ART_PALANTIR_OF_WESTERNESSE = 24;
export const ART_STAFF_OF_AESCULAPIUS = 25;
export const ART_MAGIC_MIRROR_OF_MERLIN = 26;
export const ART_EYES_OF_THE_OVERWORLD = 27;
export const ART_MITRE_OF_HOLINESS = 28;
export const ART_LONGBOW_OF_DIANA = 29;
export const ART_MASTER_KEY_OF_THIEVERY = 30;
export const ART_TSURUGI_OF_MURAMASA = 31;
export const ART_YENDORIAN_EXPRESS_CARD = 32;
export const ART_ORB_OF_FATE = 33;
export const ART_EYE_OF_THE_AETHIOPICA = 34;

// Names in list order including the empty dummy at 0, so this indexes directly
// by oartifact the way C's artifact_names[] does.
export const artifact_names = [
 "",
 "Excalibur",
 "Stormbringer",
 "Mjollnir",
 "Cleaver",
 "Grimtooth",
 "Orcrist",
 "Sting",
 "Magicbane",
 "Frost Brand",
 "Fire Brand",
 "Dragonbane",
 "Demonbane",
 "Werebane",
 "Grayswandir",
 "Giantslayer",
 "Ogresmasher",
 "Trollsbane",
 "Vorpal Blade",
 "Snickersnee",
 "Sunsword",
 "The Orb of Detection",
 "The Heart of Ahriman",
 "The Sceptre of Might",
 "The Palantir of Westernesse",
 "The Staff of Aesculapius",
 "The Magic Mirror of Merlin",
 "The Eyes of the Overworld",
 "The Mitre of Holiness",
 "The Longbow of Diana",
 "The Master Key of Thievery",
 "The Tsurugi of Muramasa",
 "The Platinum Yendorian Express Card",
 "The Orb of Fate",
 "The Eye of the Aethiopica"
];

// Base object type of each artifact (artilist.h's second A() field), as the
// ONAMES key. Index 0 is the dummy's STRANGE_OBJECT, which is how
// `for (a = artilist + 1; a->otyp; a++)` loops know where the list ends.
export const artifact_otyps = [
 "STRANGE_OBJECT",
 "LONG_SWORD",
 "RUNESWORD",
 "WAR_HAMMER",
 "BATTLE_AXE",
 "ORCISH_DAGGER",
 "ELVEN_BROADSWORD",
 "ELVEN_DAGGER",
 "ATHAME",
 "LONG_SWORD",
 "LONG_SWORD",
 "BROADSWORD",
 "SILVER_MACE",
 "SILVER_SABER",
 "SILVER_SABER",
 "LONG_SWORD",
 "WAR_HAMMER",
 "MORNING_STAR",
 "LONG_SWORD",
 "KATANA",
 "LONG_SWORD",
 "CRYSTAL_BALL",
 "LUCKSTONE",
 "MACE",
 "CRYSTAL_BALL",
 "QUARTERSTAFF",
 "MIRROR",
 "LENSES",
 "HELM_OF_BRILLIANCE",
 "BOW",
 "SKELETON_KEY",
 "TSURUGI",
 "CREDIT_CARD",
 "CRYSTAL_BALL",
 "AMULET_OF_ESP"
];
