// artilist_records.js — the artifact table.
// C ref: include/artilist.h
//
// GENERATED from the header's 36 A(...) entries, not hand-written. The header
// is an X-macro file: included repeatedly with a different #define A(...),
// which is how one table yields the names array, the ART_* enum and these
// records.
//
// Two parsing hazards, both hit while writing the generator:
//   - fields 6..8 hold macros with commas inside parens, so splitting on
//     commas needs parenthesis-depth matching
//   - a C comment can sit INSIDE a field (the Heart of Ahriman's attack is
//     preceded by one), so comments must be stripped before parsing
//
// attk/defn/cary ARE evaluated, using the macro table at include/artilist.h:35
//   NO_ATTK/NO_DFNS/NO_CARY {0,0,0,0}   DFNS(c)/CARY(c) {0,c,0,0}
//   PHYS(a,b) {0,AD_PHYS,a,b}, and likewise DRLI COLD FIRE ELEC STUN, plus
//   POIS(a,b) {0,AD_DRST,a,b}  <- note POIS maps to AD_DRST, not AD_POIS
// Struct order is C's: {aatyp, adtyp, damn, damd}. adtyp is kept as its AD_*
// NAME rather than a number, because the AD_* values are not all ported yet
// and a wrong number here would silently change which artifacts match.
//
// Everything else keeps C's field names and C's order, as source text.
// Index 0 is the sentinel, so ART_NONARTIFACT === 0 and C's
// `oart != &artilist[ART_NONARTIFACT]` is an index-zero test here.
export const artilist = [
    {"nam": "", "typ": "STRANGE_OBJECT", "spfx": "0", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "0", "cost": "0L", "color": "NO_COLOR", "bn": "NONARTIFACT"},
    {"nam": "Excalibur", "typ": "LONG_SWORD", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_SEEK | SPFX_DEFN | SPFX_INTEL | SPFX_SEARCH)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 10}, "defn": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_LAWFUL", "role": "PM_KNIGHT", "race": "NON_PM", "gift_status": "0", "gift_value": "10", "cost": "4000L", "color": "NO_COLOR", "bn": "EXCALIBUR"},
    {"nam": "Stormbringer", "typ": "RUNESWORD", "spfx": "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN | SPFX_INTEL | SPFX_DRLI)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 5, "damd": 2}, "defn": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_CHAOTIC", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "9", "cost": "8000L", "color": "NO_COLOR", "bn": "STORMBRINGER"},
    {"nam": "Mjollnir", "typ": "WAR_HAMMER", "spfx": "(SPFX_RESTR | SPFX_ATTK)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_ELEC", "damn": 5, "damd": 24}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NEUTRAL", "role": "PM_VALKYRIE", "race": "NON_PM", "gift_status": "0", "gift_value": "8", "cost": "4000L", "color": "NO_COLOR", "bn": "MJOLLNIR"},
    {"nam": "Cleaver", "typ": "BATTLE_AXE", "spfx": "SPFX_RESTR", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 3, "damd": 6}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NEUTRAL", "role": "PM_BARBARIAN", "race": "NON_PM", "gift_status": "0", "gift_value": "8", "cost": "1500L", "color": "NO_COLOR", "bn": "CLEAVER"},
    {"nam": "Grimtooth", "typ": "ORCISH_DAGGER", "spfx": "(SPFX_RESTR | SPFX_WARN | SPFX_DFLAG2)", "cspfx": "0", "mtype": "M2_ELF", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 2, "damd": 6}, "defn": {"aatyp": 0, "adtyp": "AD_DRST", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "FLING_POISON", "alignment": "A_CHAOTIC", "role": "NON_PM", "race": "PM_ORC", "gift_status": "0", "gift_value": "5", "cost": "1200L", "color": "CLR_RED", "bn": "GRIMTOOTH"},
    {"nam": "Orcrist", "typ": "ELVEN_BROADSWORD", "spfx": "(SPFX_WARN | SPFX_DFLAG2)", "cspfx": "0", "mtype": "M2_ORC", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_CHAOTIC", "role": "NON_PM", "race": "PM_ELF", "gift_status": "3", "gift_value": "4", "cost": "2000L", "color": "CLR_BRIGHT_BLUE", "bn": "ORCRIST"},
    {"nam": "Sting", "typ": "ELVEN_DAGGER", "spfx": "(SPFX_WARN | SPFX_DFLAG2)", "cspfx": "0", "mtype": "M2_ORC", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_CHAOTIC", "role": "NON_PM", "race": "PM_ELF", "gift_status": "3", "gift_value": "1", "cost": "800L", "color": "CLR_BRIGHT_BLUE", "bn": "STING"},
    {"nam": "Magicbane", "typ": "ATHAME", "spfx": "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_STUN", "damn": 3, "damd": 4}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NEUTRAL", "role": "PM_WIZARD", "race": "NON_PM", "gift_status": "0", "gift_value": "7", "cost": "3500L", "color": "NO_COLOR", "bn": "MAGICBANE"},
    {"nam": "Frost Brand", "typ": "LONG_SWORD", "spfx": "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_COLD", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_COLD", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "SNOWSTORM", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "9", "cost": "3000L", "color": "NO_COLOR", "bn": "FROST_BRAND"},
    {"nam": "Fire Brand", "typ": "LONG_SWORD", "spfx": "(SPFX_RESTR | SPFX_ATTK | SPFX_DEFN)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_FIRE", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_FIRE", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "FIRESTORM", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "5", "cost": "3000L", "color": "NO_COLOR", "bn": "FIRE_BRAND"},
    {"nam": "Dragonbane", "typ": "BROADSWORD", "spfx": "(SPFX_RESTR | SPFX_DCLAS | SPFX_REFLECT)", "cspfx": "0", "mtype": "S_DRAGON", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "5", "cost": "500L", "color": "NO_COLOR", "bn": "DRAGONBANE"},
    {"nam": "Demonbane", "typ": "SILVER_MACE", "spfx": "(SPFX_RESTR | SPFX_DFLAG2)", "cspfx": "0", "mtype": "M2_DEMON", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "BANISH", "alignment": "A_LAWFUL", "role": "PM_CLERIC", "race": "NON_PM", "gift_status": "1", "gift_value": "3", "cost": "2500L", "color": "NO_COLOR", "bn": "DEMONBANE"},
    {"nam": "Werebane", "typ": "SILVER_SABER", "spfx": "(SPFX_RESTR | SPFX_DFLAG2)", "cspfx": "0", "mtype": "M2_WERE", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_WERE", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "1", "gift_value": "4", "cost": "1500L", "color": "NO_COLOR", "bn": "WEREBANE"},
    {"nam": "Grayswandir", "typ": "SILVER_SABER", "spfx": "(SPFX_RESTR | SPFX_HALRES)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_LAWFUL", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "10", "cost": "8000L", "color": "NO_COLOR", "bn": "GRAYSWANDIR"},
    {"nam": "Giantslayer", "typ": "LONG_SWORD", "spfx": "(SPFX_RESTR | SPFX_DFLAG2)", "cspfx": "0", "mtype": "M2_GIANT", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NEUTRAL", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "4", "cost": "200L", "color": "NO_COLOR", "bn": "GIANTSLAYER"},
    {"nam": "Ogresmasher", "typ": "WAR_HAMMER", "spfx": "(SPFX_RESTR | SPFX_DCLAS)", "cspfx": "0", "mtype": "S_OGRE", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "1", "cost": "200L", "color": "NO_COLOR", "bn": "OGRESMASHER"},
    {"nam": "Trollsbane", "typ": "MORNING_STAR", "spfx": "(SPFX_RESTR | SPFX_DCLAS | SPFX_REGEN)", "cspfx": "0", "mtype": "S_TROLL", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "2", "gift_value": "1", "cost": "200L", "color": "NO_COLOR", "bn": "TROLLSBANE"},
    {"nam": "Vorpal Blade", "typ": "LONG_SWORD", "spfx": "(SPFX_RESTR | SPFX_BEHEAD)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 1}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NEUTRAL", "role": "NON_PM", "race": "NON_PM", "gift_status": "1", "gift_value": "5", "cost": "4000L", "color": "NO_COLOR", "bn": "VORPAL_BLADE"},
    {"nam": "Snickersnee", "typ": "KATANA", "spfx": "SPFX_RESTR", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 0, "damd": 8}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_LAWFUL", "role": "PM_SAMURAI", "race": "NON_PM", "gift_status": "0", "gift_value": "8", "cost": "1200L", "color": "NO_COLOR", "bn": "SNICKERSNEE"},
    {"nam": "Sunsword", "typ": "LONG_SWORD", "spfx": "(SPFX_RESTR | SPFX_DFLAG2)", "cspfx": "0", "mtype": "M2_UNDEAD", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_BLND", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "BLINDING_RAY", "alignment": "A_LAWFUL", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "6", "cost": "1500L", "color": "NO_COLOR", "bn": "SUNSWORD"},
    {"nam": "The Orb of Detection", "typ": "CRYSTAL_BALL", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", "cspfx": "(SPFX_ESP | SPFX_HSPDAM)", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "inv": "INVIS", "alignment": "A_LAWFUL", "role": "PM_ARCHEOLOGIST", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "ORB_OF_DETECTION"},
    {"nam": "The Heart of Ahriman", "typ": "LUCKSTONE", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", "cspfx": "SPFX_STLTH", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "LEVITATION", "alignment": "A_NEUTRAL", "role": "PM_BARBARIAN", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "HEART_OF_AHRIMAN"},
    {"nam": "The Sceptre of Might", "typ": "MACE", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_DALIGN)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "CONFLICT", "alignment": "A_LAWFUL", "role": "PM_CAVE_DWELLER", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "SCEPTRE_OF_MIGHT"},
    {"nam": "The Palantir of Westernesse", "typ": "CRYSTAL_BALL", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", "cspfx": "(SPFX_ESP | SPFX_REGEN | SPFX_HSPDAM)", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "TAMING", "alignment": "A_CHAOTIC", "role": "NON_PM", "race": "PM_ELF", "gift_status": "0", "gift_value": "12", "cost": "8000L", "color": "NO_COLOR", "bn": "PALANTIR_OF_WESTERNESSE"},
    {"nam": "The Staff of Aesculapius", "typ": "QUARTERSTAFF", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_ATTK | SPFX_INTEL | SPFX_DRLI | SPFX_REGEN)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_DRLI", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "HEALING", "alignment": "A_NEUTRAL", "role": "PM_HEALER", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "5000L", "color": "NO_COLOR", "bn": "STAFF_OF_AESCULAPIUS"},
    {"nam": "The Magic Mirror of Merlin", "typ": "MIRROR", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_SPEAK)", "cspfx": "SPFX_ESP", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_LAWFUL", "role": "PM_KNIGHT", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "1500L", "color": "NO_COLOR", "bn": "MAGIC_MIRROR_OF_MERLIN"},
    {"nam": "The Eyes of the Overworld", "typ": "LENSES", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_XRAY)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "ENLIGHTENING", "alignment": "A_NEUTRAL", "role": "PM_MONK", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2500L", "color": "NO_COLOR", "bn": "EYES_OF_THE_OVERWORLD"},
    {"nam": "The Mitre of Holiness", "typ": "HELM_OF_BRILLIANCE", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_DFLAG2 | SPFX_INTEL | SPFX_PROTECT)", "cspfx": "0", "mtype": "M2_UNDEAD", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_FIRE", "damn": 0, "damd": 0}, "inv": "ENERGY_BOOST", "alignment": "A_LAWFUL", "role": "PM_CLERIC", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "2000L", "color": "NO_COLOR", "bn": "MITRE_OF_HOLINESS"},
    {"nam": "The Longbow of Diana", "typ": "BOW", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_REFLECT)", "cspfx": "SPFX_ESP", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 5, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "CREATE_AMMO", "alignment": "A_CHAOTIC", "role": "PM_RANGER", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "4000L", "color": "NO_COLOR", "bn": "LONGBOW_OF_DIANA"},
    {"nam": "The Master Key of Thievery", "typ": "SKELETON_KEY", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_SPEAK)", "cspfx": "(SPFX_WARN | SPFX_TCTRL | SPFX_HPHDAM)", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "UNTRAP", "alignment": "A_CHAOTIC", "role": "PM_ROGUE", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "3500L", "color": "NO_COLOR", "bn": "MASTER_KEY_OF_THIEVERY"},
    {"nam": "The Tsurugi of Muramasa", "typ": "TSURUGI", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_BEHEAD | SPFX_LUCK | SPFX_PROTECT)", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "AD_PHYS", "damn": 0, "damd": 8}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_LAWFUL", "role": "PM_SAMURAI", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "4500L", "color": "NO_COLOR", "bn": "TSURUGI_OF_MURAMASA"},
    {"nam": "The Platinum Yendorian Express Card", "typ": "CREDIT_CARD", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_DEFN)", "cspfx": "(SPFX_ESP | SPFX_HSPDAM)", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "inv": "CHARGE_OBJ", "alignment": "A_NEUTRAL", "role": "PM_TOURIST", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "7000L", "color": "NO_COLOR", "bn": "YENDORIAN_EXPRESS_CARD"},
    {"nam": "The Orb of Fate", "typ": "CRYSTAL_BALL", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL | SPFX_LUCK)", "cspfx": "(SPFX_WARN | SPFX_HSPDAM | SPFX_HPHDAM)", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "LEV_TELE", "alignment": "A_NEUTRAL", "role": "PM_VALKYRIE", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "3500L", "color": "NO_COLOR", "bn": "ORB_OF_FATE"},
    {"nam": "The Eye of the Aethiopica", "typ": "AMULET_OF_ESP", "spfx": "(SPFX_NOGEN | SPFX_RESTR | SPFX_INTEL)", "cspfx": "(SPFX_EREGEN | SPFX_HSPDAM)", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "AD_MAGM", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "CREATE_PORTAL", "alignment": "A_NEUTRAL", "role": "PM_WIZARD", "race": "NON_PM", "gift_status": "0", "gift_value": "12", "cost": "4000L", "color": "NO_COLOR", "bn": "EYE_OF_THE_AETHIOPICA"},
    {"nam": "0", "typ": "0", "spfx": "0", "cspfx": "0", "mtype": "0", "attk": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "defn": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "cary": {"aatyp": 0, "adtyp": "0", "damn": 0, "damd": 0}, "inv": "0", "alignment": "A_NONE", "role": "NON_PM", "race": "NON_PM", "gift_status": "0", "gift_value": "0", "cost": "0L", "color": "NO_COLOR", "bn": "TERMINATOR"},
];
