// banner_data.js — GENERATED by tools/gen-banner.mjs.
// Do not edit by hand; re-run the generator.
//
// The four startup banner lines, composed exactly as src/mdlib.c
// bannerc_string() and include/patchlevel.h do. win/tty/wintty.c writes them at
// rows 4-7 before the "Who are you?" prompt, so they are on every chargen frame.
//
// The build date is a constant because a recorder patch pins it (src/date.c);
// without that the banner would differ from the recording on every rebuild.

export const COPYRIGHT_BANNER = [
 "NetHack, Copyright 1985-2026",
 "         By Stichting Mathematisch Centrum and M. Stephenson.",
 "         Version 5.0.0 MacOS, built May  2 2026 12:00:00.",
 "         See license for details."
];
