// drawing_data.js — GENERATED by tools/gen-drawing.mjs. Do not edit.
// Source: include/defsym.h, the MONSYM() and OBJCLASS() invocations that
// src/drawing.c expands into def_monsyms[] and def_oc_syms[].
//
// Indexed by class number, so def_monsyms[mlet] and def_oc_syms[oclass] give
// the character newsym() should show. Index 0 is the "random class" placeholder
// in both and is deliberately empty.

// 60 monster classes
export const def_monsyms = ["","a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z","A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","@"," ","'","&",";",":","~","]"];

// 17 object classes
export const def_oc_syms = ["","]",")","[","=","\"","(","%","!","?","+","/","$","*","`","0","_","."];

// symbol name -> class index, for reading SYMBOLS= lines from an rc
export const monsym_names = {
 "ANT": 1,
 "BLOB": 2,
 "COCKATRICE": 3,
 "DOG": 4,
 "EYE": 5,
 "FELINE": 6,
 "GREMLIN": 7,
 "HUMANOID": 8,
 "IMP": 9,
 "JELLY": 10,
 "KOBOLD": 11,
 "LEPRECHAUN": 12,
 "MIMIC": 13,
 "NYMPH": 14,
 "ORC": 15,
 "PIERCER": 16,
 "QUADRUPED": 17,
 "RODENT": 18,
 "SPIDER": 19,
 "TRAPPER": 20,
 "UNICORN": 21,
 "VORTEX": 22,
 "WORM": 23,
 "XAN": 24,
 "LIGHT": 25,
 "ZRUTY": 26,
 "ANGEL": 27,
 "BAT": 28,
 "CENTAUR": 29,
 "DRAGON": 30,
 "ELEMENTAL": 31,
 "FUNGUS": 32,
 "GNOME": 33,
 "GIANT": 34,
 "INVISIBLE": 35,
 "JABBERWOCK": 36,
 "KOP": 37,
 "LICH": 38,
 "MUMMY": 39,
 "NAGA": 40,
 "OGRE": 41,
 "PUDDING": 42,
 "QUANTMECH": 43,
 "RUSTMONST": 44,
 "SNAKE": 45,
 "TROLL": 46,
 "UMBER": 47,
 "VAMPIRE": 48,
 "WRAITH": 49,
 "XORN": 50,
 "YETI": 51,
 "ZOMBIE": 52,
 "HUMAN": 53,
 "GHOST": 54,
 "GOLEM": 55,
 "DEMON": 56,
 "EEL": 57,
 "LIZARD": 58,
 "WORM_TAIL": 59,
 "MIMIC_DEF": 60
};

export const oclass_names = {
 "ILLOBJ": 1,
 "WEAPON": 2,
 "ARMOR": 3,
 "RING": 4,
 "AMULET": 5,
 "TOOL": 6,
 "FOOD": 7,
 "POTION": 8,
 "SCROLL": 9,
 "SPBOOK": 10,
 "WAND": 11,
 "COIN": 12,
 "GEM": 13,
 "ROCK": 14,
 "BALL": 15,
 "CHAIN": 16,
 "VENOM": 17
};
