// mkobj.js — object creation.
// C ref: src/mkobj.c
//
// NOT YET WIRED IN. js/mklev.js still uses its own local stubs for object
// creation. Swapping them for these breaks the structural phase of level
// generation, because mksobj() below does not yet run mksobj_init() — the
// per-class enchantment, blessing, corpse-type and artifact draws. Doing the
// swap without that took seed8000 from 19 screens to 0.
//
// What is verified: mkobj()'s class selection is exact. Against
// seed0102-ranger-name-cancel it reproduces
//     rnd(100)=30   @ mkobj(mkobj.c:280)
//     rnd(1000)=813 @ mkobj(mkobj.c:289)
//     rnd(2)=2      @ next_ident(mkobj.c:521)
// call for call, and moves that session's first divergence from 1191 to 1213.
//
// To finish: port mksobj_init (mkobj.c:971 onward) and blessorcurse
// (mkobj.c:1846 — the top blocker at 9 sessions), then replace the stubs in
// js/mklev.js and re-check seed8000's screen count before committing.
//
// The object tables come from js/objects_data.js, generated by
// tools/gen-objects.mjs; svb.bases[] and go.oclass_prob_totals[] are built by
// js/o_init.js init_objects().

import { game } from './gstate.js';
import { rnd, rn1, rn2 } from './rng.js';
import { OCLASSES } from './objects_data.js';

const {
    WEAPON_CLASS, ARMOR_CLASS, FOOD_CLASS, TOOL_CLASS, GEM_CLASS,
    POTION_CLASS, SCROLL_CLASS, SPBOOK_CLASS, WAND_CLASS, RING_CLASS,
    AMULET_CLASS, COIN_CLASS, RANDOM_CLASS,
} = OCLASSES;

// src/mkobj.c:36 — class probability tables. struct icp { iprob, iclass }.
const mkobjprobs = [
    [10, WEAPON_CLASS], [11, ARMOR_CLASS], [20, FOOD_CLASS],
    [8, TOOL_CLASS], [7, GEM_CLASS], [16, POTION_CLASS],
    [16, SCROLL_CLASS], [4, SPBOOK_CLASS], [4, WAND_CLASS],
    [3, RING_CLASS], [1, AMULET_CLASS],
];

const boxiprobs = [
    [18, GEM_CLASS], [15, FOOD_CLASS], [18, POTION_CLASS],
    [18, SCROLL_CLASS], [12, SPBOOK_CLASS], [7, COIN_CLASS],
    [6, WAND_CLASS], [5, RING_CLASS], [1, AMULET_CLASS],
];

const rogueprobs = [
    [12, WEAPON_CLASS], [12, ARMOR_CLASS], [22, FOOD_CLASS],
    [22, POTION_CLASS], [22, SCROLL_CLASS], [5, WAND_CLASS],
    [5, RING_CLASS],
];

const hellprobs = [
    [20, WEAPON_CLASS], [20, ARMOR_CLASS], [16, FOOD_CLASS],
    [12, TOOL_CLASS], [10, GEM_CLASS], [1, POTION_CLASS],
    [1, SCROLL_CLASS], [8, WAND_CLASS], [8, RING_CLASS],
    [4, AMULET_CLASS],
];

export { mkobjprobs, boxiprobs, rogueprobs, hellprobs };

// src/mkobj.c:521 next_ident()
// One rnd(2) per created object or monster. Cheap to overlook and it appears
// between every pair of object draws in the recordings.
export function next_ident() {
    const ctx = game.context;
    const id = ctx.ident || 1;
    ctx.ident = id + rnd(2); /* ready for next new object or monster */
    if (!ctx.ident)
        ctx.ident = rnd(2) + 1; /* id 1 is reserved */
    return id;
}

// src/mkobj.c:270 mkobj() — select a type of item from a class.
//
// Two draws: rnd(100) walks the class table, then
// rnd(oclass_prob_totals[oclass]) walks objects[] by oc_prob. Both are visible
// in the recordings as mkobj.c:280 and mkobj.c:289.
export function mkobj(oclass, artif) {
    const objects = game.objects;
    let tprob, i, prob;

    if (oclass === RANDOM_CLASS) {
        const iprobs = Is_rogue_level() ? rogueprobs
                     : Inhell() ? hellprobs
                     : mkobjprobs;
        let idx = 0;
        for (tprob = rnd(100); (tprob -= iprobs[idx][0]) > 0; idx++)
            continue;
        oclass = iprobs[idx][1];
    }

    /* SPBOOK_no_NOVEL takes the rnd_class() path in C; ordinary classes walk
       the per-class probability total. */
    prob = rnd(game.oclass_prob_totals[oclass]);
    i = game.bases[oclass];
    while ((prob -= objects[i].oc_prob) > 0)
        ++i;

    return mksobj(i, true, artif);
}

// src/mkobj.c mksobj() — create a specific object type.
//
// Only the identity and o_id allocation are ported so far. mksobj_init(), which
// carries the per-class enchantment, blessing, corpse-type and artifact draws,
// needs artifacts and monster-hatching and lands with those subsystems. Nothing
// here invents a draw it cannot justify.
export function mksobj(otyp, init, artif) {
    const objects = game.objects;
    const otmp = {
        otyp,
        oclass: objects[otyp].oc_class,
        quan: 1,
        spe: 0,
        blessed: 0,
        cursed: 0,
        o_id: next_ident(),
    };
    return otmp;
}

// src/dungeon.c Is_rogue_level() / Inhell — neither is reachable on the levels
// the public corpus generates, but the branches exist so the class table is
// selected the way C selects it rather than being assumed.
function Is_rogue_level() {
    return game.level?.flags?.is_rogue_level === true;
}
function Inhell() {
    return game.dungeons?.[game.u?.uz?.dnum]?.flags?.hellish === true;
}
