// mkobj.js — object creation.
// C ref: src/mkobj.c
//
// Wired in and carrying the whole level-generation object pipeline: mkobj(),
// mksobj(), mksobj_init() for every class, blessorcurse(), mkobj_erosions(),
// mkbox_cnts(), rnd_class(), the corpse block (set_corpsenm,
// start_corpse_timeout, undead_to_corpse, special_corpse) and next_ident().
//
// Two things about this file are load-bearing and easy to get wrong:
//
//   * mkobj_erosions() is the LAST STATEMENT OF mksobj_init(), not of
//     mksobj(). An object created with init = FALSE must not draw for erosion.
//   * The switch after `if (init) mksobj_init(...)` in mksobj() is the "must
//     be done even if init = 0" block from src/mkobj.c:1200. A corpse draws
//     rndmonnum() for its species and rn2(2) for its gender there, and
//     mkcorpstat() overwrites the species afterwards — but the draws still
//     happened.
//
// Still missing: mkbox_cnts()'s add_to_container weight propagation (no draw),
// artifact creation (mk_artifact), and permapoisoned().
//
// The object tables come from js/objects_data.js, generated by
// tools/gen-objects.mjs; svb.bases[] and go.oclass_prob_totals[] are built by
// js/o_init.js init_objects().

import { game } from './gstate.js';
import { Is_rogue_level } from './const.js';
import { rnd, rn1, rn2, rne, rnz } from './rng.js';
import { OCLASSES, ONAMES, SKILLS, obj_descr } from './objects_data.js';
import {
    rndmonnum, level_difficulty, is_male, is_female, is_neuter, is_rider,
} from './makemon.js';
import { PMNAMES, MONSYMS, MFLAGS, GROWNUPS } from './monst_data.js';
/* invent.js imports erosion_matters() from here, so this edge closes a cycle.
   Both sides export function DECLARATIONS, which hoist, so each module sees the
   other's bindings by the time anything is called. */
import { merged, weight } from './invent.js';
import { OBJ_CONTAINED } from './obj.js';
import { depth } from './dungeon.js';

// include/objclass.h:152 — #define SPBOOK_no_NOVEL (0 - (int) SPBOOK_CLASS)
// A NEGATED class, not an index past the real ones. It is the one caller-facing
// value mkobj() accepts that is not a real oclass.
const SPBOOK_no_NOVEL = -OCLASSES.SPBOOK_CLASS;

// include/permonst.h
const NON_PM = -1;
// include/hack.h:1189-1200 — corpse/statue gender is stored in obj.spe.
const CORPSTAT_INIT = 0x08;
const CORPSTAT_FEMALE = 1, CORPSTAT_MALE = 2, CORPSTAT_NEUTER = 3;
// include/hack.h:1404-1406
const TAINT_AGE = 50, TROLL_REVIVE_CHANCE = 37, ROT_AGE = 250;
const { G_NOCORPSE, G_GENOD, G_EXTINCT } = MFLAGS;
const G_GONE = G_GENOD | G_EXTINCT;

// gu.urole.mnum is a PM_ name in the generated role table.
function pmIndexOf(name) {
    if (typeof name === 'number') return name;
    return (name && PMNAMES[name] !== undefined) ? PMNAMES[name] : NON_PM;
}

const { P_BOW, P_SHURIKEN } = SKILLS;

const {
    WEAPON_CLASS, ARMOR_CLASS, FOOD_CLASS, TOOL_CLASS, GEM_CLASS,
    POTION_CLASS, SCROLL_CLASS, SPBOOK_CLASS, WAND_CLASS, RING_CLASS,
    AMULET_CLASS, COIN_CLASS, RANDOM_CLASS, ROCK_CLASS, BALL_CLASS,
    CHAIN_CLASS, VENOM_CLASS,
} = OCLASSES;

// src/mkobj.c:36 — class probability tables. struct icp { iprob, iclass }.
const mkobjprobs = [
    [10, WEAPON_CLASS], [11, ARMOR_CLASS], [20, FOOD_CLASS],
    [8, TOOL_CLASS], [7, GEM_CLASS], [16, POTION_CLASS],
    [16, SCROLL_CLASS], [4, SPBOOK_CLASS], [4, WAND_CLASS],
    [3, RING_CLASS], [1, AMULET_CLASS],
];

const boxiprobs = [
    [18, GEM_CLASS], [15, FOOD_CLASS], [18, POTION_CLASS],
    [18, SCROLL_CLASS], [12, SPBOOK_CLASS], [7, COIN_CLASS],
    [6, WAND_CLASS], [5, RING_CLASS], [1, AMULET_CLASS],
];

const rogueprobs = [
    [12, WEAPON_CLASS], [12, ARMOR_CLASS], [22, FOOD_CLASS],
    [22, POTION_CLASS], [22, SCROLL_CLASS], [5, WAND_CLASS],
    [5, RING_CLASS],
];

const hellprobs = [
    [20, WEAPON_CLASS], [20, ARMOR_CLASS], [16, FOOD_CLASS],
    [12, TOOL_CLASS], [10, GEM_CLASS], [1, POTION_CLASS],
    [1, SCROLL_CLASS], [8, WAND_CLASS], [8, RING_CLASS],
    [4, AMULET_CLASS],
];

export { mkobjprobs, boxiprobs, rogueprobs, hellprobs };

// src/mkobj.c:521 next_ident()
// One rnd(2) per created object or monster. Cheap to overlook and it appears
// between every pair of object draws in the recordings.
export function next_ident() {
    const ctx = game.context;
    const id = ctx.ident || 1;
    ctx.ident = id + rnd(2); /* ready for next new object or monster */
    if (!ctx.ident)
        ctx.ident = rnd(2) + 1; /* id 1 is reserved */
    return id;
}

// src/mkobj.c:270 mkobj() — select a type of item from a class.
//
// Two draws: rnd(100) walks the class table, then
// rnd(oclass_prob_totals[oclass]) walks objects[] by oc_prob. Both are visible
// in the recordings as mkobj.c:280 and mkobj.c:289.
export function mkobj(oclass, artif) {
    const objects = game.objects;
    let tprob, i, prob;

    if (oclass === RANDOM_CLASS) {
        const iprobs = Is_rogue_level() ? rogueprobs
                     : Inhell() ? hellprobs
                     : mkobjprobs;
        let idx = 0;
        for (tprob = rnd(100); (tprob -= iprobs[idx][0]) > 0; idx++)
            continue;
        oclass = iprobs[idx][1];
    }

    /* src/mkobj.c:285 — SPBOOK_no_NOVEL draws differently: rnd_class() over the
       spellbooks stopping at SPE_BLANK_PAPER, which excludes SPE_NOVEL. That
       range sums to 999 where the full SPBOOK_CLASS total is 1000. */
    if (oclass === SPBOOK_no_NOVEL) {
        i = rnd_class(game.bases[OCLASSES.SPBOOK_CLASS], ONAMES.SPE_BLANK_PAPER);
        oclass = OCLASSES.SPBOOK_CLASS;     /* for the sanity check below */
    } else {
        prob = rnd(game.oclass_prob_totals[oclass]);
        i = game.bases[oclass];
        while ((prob -= objects[i].oc_prob) > 0)
            ++i;
    }

    /* src/mkobj.c:295 — C's probtype guard. It resets i when the walk lands
       outside the class, which changes WHICH object is returned, so leaving it
       out is not merely dropping a diagnostic. If it ever fires, oc_prob or
       oclass_prob_totals is wrong. */
    if (objects[i].oc_class !== oclass || !obj_descr_name(i)) {
        note_unported_obj(`probtype error oclass=${oclass} i=${i}`);
        i = game.bases[oclass];
    }

    return mksobj(i, true, artif);
}

// include/obj.h:260-268 — weapon-ish predicates. oc_skill is oc_subtyp, and
// thrown weapons carry the *negated* skill, so the test brackets -P_SHURIKEN
// .. -P_BOW. These were hand-written as 26 and 31; the real values are 20 and
// 24, which made is_multigen() false for every dart and arrow and silently
// dropped the rn1(6,6) stack-size draw.
function is_multigen(otmp, objects) {
    const o = objects[otmp.otyp];
    return otmp.oclass === WEAPON_CLASS
        && o.oc_subtyp >= -P_SHURIKEN && o.oc_subtyp <= -P_BOW;
}
function is_poisonable(otmp, objects) {
    return is_multigen(otmp, objects);   /* plus permapoisoned(), not ported */
}

// src/mkobj.c bcsign()
function bcsign(otmp) {
    return (otmp.blessed ? 1 : 0) - (otmp.cursed ? 1 : 0);
}

// src/mkobj.c:1783 curse() and :1745 bless(). Both return early for gold,
// which is neither blessed nor cursed, and both clear the opposite flag. The
// lamplit/arti_light_radius bookkeeping needs the light-source subsystem.
export function curse(otmp) {
    if (otmp.oclass === OCLASSES.COIN_CLASS)
        return;
    otmp.blessed = 0;
    otmp.cursed = 1;
}
export function bless(otmp) {
    if (otmp.oclass === OCLASSES.COIN_CLASS)
        return;
    otmp.cursed = 0;
    otmp.blessed = 1;
}

// src/mkobj.c:1846 blessorcurse()
export function blessorcurse(otmp, chance) {
    if (otmp.blessed || otmp.cursed)
        return;
    if (!rn2(chance)) {
        if (!rn2(2)) curse(otmp); else bless(otmp);
    }
}

// No artifacts are generated yet, so none exist.
function nartifact_exist() { return 0; }

// src/mkobj.c:869 mksobj_init() — per-class initialisation.
//
// Dispatches on the real objects[otyp].oc_class from js/objects_data.js.
//
// NOT COMPLETE: the FOOD_CLASS corpse/egg/tin paths and the ROCK_CLASS statue
// path need rndmonnum(), which needs makemon.c's monster selection. Those
// otyps are rare in level generation; every other class below is the full C
// logic. The gap is marked rather than filled with an invented draw.
export function mksobj_init(otmp, artif) {
    const objects = game.objects;
    const let_ = objects[otmp.otyp].oc_class;

    switch (let_) {
    case WEAPON_CLASS:
        otmp.quan = is_multigen(otmp, objects) ? rn1(6, 6) : 1;
        if (!rn2(11)) {
            otmp.spe = rne(3);
            otmp.blessed = rn2(2);
        } else if (!rn2(10)) {
            curse(otmp);
            otmp.spe = -rne(3);
        } else {
            blessorcurse(otmp, 10);
        }
        if (is_poisonable(otmp, objects) && !rn2(100))
            otmp.opoisoned = 1;
        if (artif && !rn2(20 + (10 * nartifact_exist()))) {
            /* mk_artifact() — artifacts not ported */
        }
        break;

    case FOOD_CLASS: {
        otmp.oeaten = 0;
        let tryct, mndx;
        switch (otmp.otyp) {
        case ONAMES.CORPSE:
            tryct = 50;
            do
                otmp.corpsenm = undead_to_corpse(rndmonnum());
            while ((game.mvitals[otmp.corpsenm].mvflags & G_NOCORPSE)
                   && (--tryct > 0));
            if (tryct === 0)
                otmp.corpsenm = PMNAMES.PM_HUMAN;
            /* timer set below */
            break;
        case ONAMES.EGG:
            otmp.corpsenm = NON_PM; /* generic egg */
            if (!rn2(3))
                for (tryct = 200; tryct > 0; --tryct) {
                    mndx = can_be_hatched(rndmonnum());
                    if (mndx !== NON_PM && !dead_species(mndx, true)) {
                        otmp.corpsenm = mndx; /* typed egg */
                        break;
                    }
                }
            /* timer set below */
            break;
        case ONAMES.TIN:
            otmp.corpsenm = NON_PM; /* empty (so far) */
            if (!rn2(6)) {
                set_tin_variety(otmp, SPINACH_TIN);
            } else {
                for (tryct = 200; tryct > 0; --tryct) {
                    mndx = undead_to_corpse(rndmonnum());
                    if (game.mons[mndx].cnutrit
                        && !(game.mvitals[mndx].mvflags & G_NOCORPSE)) {
                        otmp.corpsenm = mndx;
                        set_tin_variety(otmp, RANDOM_TIN);
                        break;
                    }
                }
            }
            blessorcurse(otmp, 10);
            break;
        case ONAMES.SLIME_MOLD:
            otmp.spe = game.context.current_fruit ?? 1;
            break;
        case ONAMES.KELP_FROND:
            otmp.quan = rnd(2);
            break;
        case ONAMES.CANDY_BAR:
            assign_candy_wrapper(otmp);
            break;
        default:
            break;
        }
        if (Is_pudding(otmp)) {
            otmp.globby = 1;
            otmp.quan = 1;
            otmp.owt = objects[otmp.otyp].oc_weight;
            otmp.known = otmp.dknown = 1;
            otmp.corpsenm = PMNAMES.PM_GRAY_OOZE
                          + (otmp.otyp - ONAMES.GLOB_OF_GRAY_OOZE);
            start_glob_timeout(otmp, 0);
        } else {
            /* every non-glob food that is not a corpse, meat ring or kelp
               frond draws here — the branch this port used to be missing */
            if (otmp.otyp !== ONAMES.CORPSE && otmp.otyp !== ONAMES.MEAT_RING
                && otmp.otyp !== ONAMES.KELP_FROND && !rn2(6))
                otmp.quan = 2;
        }
        break;
    }

    case TOOL_CLASS:
        switch (otmp.otyp) {
        case ONAMES.TALLOW_CANDLE:
        case ONAMES.WAX_CANDLE:
            otmp.spe = 1;
            otmp.age = 20 * 20; /* 400 */
            otmp.lamplit = 0;
            otmp.quan = 1 + (rn2(2) ? rn2(7) : 0);
            blessorcurse(otmp, 5);
            break;
        case ONAMES.BRASS_LANTERN:
        case ONAMES.OIL_LAMP:
            otmp.spe = 1;
            otmp.age = 1500;
            otmp.lamplit = 0;
            blessorcurse(otmp, 5);
            break;
        case ONAMES.MAGIC_LAMP:
            otmp.spe = 1;
            otmp.lamplit = 0;
            blessorcurse(otmp, 2);
            break;
        case ONAMES.CHEST:
        case ONAMES.LARGE_BOX:
            otmp.olocked = !!rn2(5);
            otmp.otrapped = !rn2(10);
            otmp.tknown = (otmp.otrapped && !rn2(100)) ? 1 : 0;
            /* FALLTHRU — src/mkobj.c:1015 */
        case ONAMES.ICE_BOX:
        case ONAMES.SACK:
        case ONAMES.OILSKIN_SACK:
        case ONAMES.BAG_OF_HOLDING:
            mkbox_cnts(otmp);
            break;
        case ONAMES.EXPENSIVE_CAMERA:
        case ONAMES.TINNING_KIT:
        case ONAMES.MAGIC_MARKER:
            otmp.spe = rn1(70, 30);
            break;
        case ONAMES.CAN_OF_GREASE:
            otmp.spe = rn1(21, 5);
            blessorcurse(otmp, 10);
            break;
        case ONAMES.CRYSTAL_BALL:
            otmp.spe = rn1(5, 3);
            blessorcurse(otmp, 2);
            break;
        case ONAMES.HORN_OF_PLENTY:
        case ONAMES.BAG_OF_TRICKS:
            otmp.spe = rn1(18, 3);
            break;
        case ONAMES.FIGURINE:
            /* corpsenm needs rndmonnum() — see the header note */
            blessorcurse(otmp, 4);
            break;
        case ONAMES.BELL_OF_OPENING:
            otmp.spe = 3;
            break;
        case ONAMES.MAGIC_FLUTE:
        case ONAMES.MAGIC_HARP:
        case ONAMES.FROST_HORN:
        case ONAMES.FIRE_HORN:
        case ONAMES.DRUM_OF_EARTHQUAKE:
            otmp.spe = rn1(5, 4);
            break;
        default:
            break;
        }
        break;

    case GEM_CLASS:
        otmp.corpsenm = 0; /* LOADSTONE hack */
        if (otmp.otyp === ONAMES.LOADSTONE)
            curse(otmp);
        else if (otmp.otyp === ONAMES.ROCK)
            otmp.quan = rn1(6, 6);
        else if (otmp.otyp !== ONAMES.LUCKSTONE && !rn2(6))
            otmp.quan = 2;
        else
            otmp.quan = 1;
        break;

    case AMULET_CLASS:
        if (rn2(10) && (otmp.otyp === ONAMES.AMULET_OF_STRANGULATION
                        || otmp.otyp === ONAMES.AMULET_OF_RESTFUL_SLEEP))
            curse(otmp);
        else
            blessorcurse(otmp, 10);
        break;

    case VENOM_CLASS:
    case CHAIN_CLASS:
    case BALL_CLASS:
        break;

    case POTION_CLASS:
    case SCROLL_CLASS:
        blessorcurse(otmp, 4);
        break;

    case SPBOOK_CLASS:
        otmp.spestudied = 0;
        blessorcurse(otmp, 17);
        break;

    case ARMOR_CLASS:
        if (rn2(10)
            && (otmp.otyp === ONAMES.FUMBLE_BOOTS
                || otmp.otyp === ONAMES.LEVITATION_BOOTS
                || otmp.otyp === ONAMES.HELM_OF_OPPOSITE_ALIGNMENT
                || otmp.otyp === ONAMES.GAUNTLETS_OF_FUMBLING || !rn2(11))) {
            curse(otmp);
            otmp.spe = -rne(3);
        } else if (!rn2(10)) {
            otmp.blessed = rn2(2);
            otmp.spe = rne(3);
        } else {
            blessorcurse(otmp, 10);
        }
        if (artif && !rn2(40 + (10 * nartifact_exist()))) {
            /* mk_artifact() — artifacts not ported */
        }
        break;

    case WAND_CLASS:
        if (otmp.otyp === ONAMES.WAN_WISHING)
            otmp.spe = 1;
        else if (otmp.otyp === ONAMES.WAN_STASIS)
            otmp.spe = rn1(4, 3);
        else
            otmp.spe = rn1(5, (objects[otmp.otyp].oc_dir === NODIR) ? 11 : 4);
        blessorcurse(otmp, 17);
        otmp.recharged = 0;
        break;

    case RING_CLASS:
        if (objects[otmp.otyp].oc_charged) {
            blessorcurse(otmp, 3);
            if (rn2(10)) {
                if (rn2(10) && bcsign(otmp))
                    otmp.spe = bcsign(otmp) * rne(3);
                else
                    otmp.spe = rn2(2) ? rne(3) : -rne(3);
            }
            /* make useless +0 rings much less common */
            if (otmp.spe === 0)
                otmp.spe = rn2(4) - rn2(3);
            /* negative rings are usually cursed */
            if (otmp.spe < 0 && rn2(5))
                curse(otmp);
        } else if (rn2(10) && (otmp.otyp === ONAMES.RIN_TELEPORTATION
                               || otmp.otyp === ONAMES.RIN_POLYMORPH
                               || otmp.otyp === ONAMES.RIN_AGGRAVATE_MONSTER
                               || otmp.otyp === ONAMES.RIN_HUNGER || !rn2(9))) {
            curse(otmp);
        }
        break;

    case ROCK_CLASS:
        if (otmp.otyp === ONAMES.STATUE) {
            /* possibly overridden by mkcorpstat() */
            otmp.corpsenm = rndmonnum();
            /* include/mondata.h:11 verysmall(ptr) is msize < MZ_SMALL */
            if (!(game.mons[otmp.corpsenm].msize < MZ_SMALL)
                && rn2(Math.trunc(level_difficulty() / 2) + 10) > 10) {
                /* add_to_container(otmp, mkobj(SPBOOK_no_NOVEL, FALSE)) —
                   SPBOOK_no_NOVEL takes mkobj's rnd_class() branch, which is
                   not ported; the container add itself makes no draw. */
                mkobj(SPBOOK_CLASS, false);
            }
        }
        /* boulder init'd below in the 'regardless of !init' code */
        break;

    case COIN_CLASS:
        break; /* do nothing */

    default:
        break;
    }

    /* src/mkobj.c:1172 — the last statement of mksobj_init(), not of mksobj().
       An object created with init = FALSE must not draw for erosion. */
    mkobj_erosions(otmp);
}

// include/objclass.h — oc_dir value used by the wand charge formula.
const NODIR = 1;
// include/monflag.h:178
const MZ_SMALL = 1;

// include/objclass.h:14-32 — object materials.
const LIQUID = 1, PAPER = 5, LEATHER = 7, WOOD = 8, DRAGON_HIDE = 10,
      IRON = 11, COPPER = 13, MITHRIL = 17, PLASTIC = 18, GLASS = 19;
const P_NONE = 0;                 /* include/skills.h */
const FIRE_RES = 1;               /* include/prop.h:15 */

// include/obj.h:382 Is_candle()
function Is_candle(otmp) {
    return otmp.otyp === ONAMES.TALLOW_CANDLE || otmp.otyp === ONAMES.WAX_CANDLE;
}

// src/mkobj.c is_flammable()
function is_flammable(otmp, objects) {
    const o = objects[otmp.otyp];
    const omat = o.oc_material;
    /* candles burn but take no fire damage and cannot be fireproofed */
    if (Is_candle(otmp))
        return false;
    if (o.oc_oprop === FIRE_RES || otmp.otyp === ONAMES.WAN_FIRE)
        return false;
    return (omat <= WOOD && omat !== LIQUID) || omat === PLASTIC;
}

// src/mkobj.c is_rottable()
function is_rottable(otmp, objects) {
    const omat = objects[otmp.otyp].oc_material;
    return (omat <= WOOD && omat !== LIQUID) || omat === DRAGON_HIDE;
}

// include/objclass.h:200-211
const is_rustprone  = (o, objs) => objs[o.otyp].oc_material === IRON;
const is_crackable  = (o, objs) => objs[o.otyp].oc_material === GLASS
                                && o.oclass === ARMOR_CLASS;
const is_corrodeable = (o, objs) => objs[o.otyp].oc_material === COPPER
                                 || objs[o.otyp].oc_material === IRON;
const is_damageable = (o, objs) =>
    is_rustprone(o, objs) || is_flammable(o, objs) || is_rottable(o, objs)
    || is_corrodeable(o, objs) || is_crackable(o, objs);

// include/obj.h:249 is_weptool() — oc_skill is oc_subtyp in the generated table
const is_weptool = (o, objs) =>
    o.oclass === TOOL_CLASS && objs[o.otyp].oc_subtyp !== P_NONE;

// src/mkobj.c erosion_matters()
export function erosion_matters(otmp, objects) {
    switch (otmp.oclass) {
    case TOOL_CLASS:
        return is_weptool(otmp, objects);
    case WEAPON_CLASS:
    case ARMOR_CLASS:
    case BALL_CLASS:
    case CHAIN_CLASS:
        return true;
    default:
        return false;
    }
}

// src/mkobj.c:175 may_generate_eroded()
function may_generate_eroded(otmp, objects) {
    /* initial hero inventory is never eroded; in_mklev exempts level items */
    if ((game.moves ?? 1) <= 1 && !game.in_mklev)
        return false;
    if (otmp.oerodeproof || !erosion_matters(otmp, objects)
        || !is_damageable(otmp, objects))
        return false;
    if (otmp.otyp === ONAMES.WORM_TOOTH || otmp.otyp === ONAMES.UNICORN_HORN)
        return false;
    if (otmp.oartifact)
        return false;
    return true;
}

// src/mkobj.c:196 mkobj_erosions() — random chance of erosion or grease.
export function mkobj_erosions(otmp) {
    const objects = game.objects;

    if (may_generate_eroded(otmp, objects)) {
        /* a small fraction generate eroded or possibly erodeproof; an item
           that generates eroded is never erodeproof, and vice versa */
        if (!rn2(100)) {
            otmp.oerodeproof = 1;
        } else {
            if (!rn2(80) && (is_flammable(otmp, objects)
                             || is_rustprone(otmp, objects)
                             || is_crackable(otmp, objects))) {
                do {
                    otmp.oeroded = (otmp.oeroded || 0) + 1;
                } while (otmp.oeroded < 3 && !rn2(9));
            }
            if (!rn2(80) && (is_rottable(otmp, objects)
                             || is_corrodeable(otmp, objects))) {
                do {
                    otmp.oeroded2 = (otmp.oeroded2 || 0) + 1;
                } while (otmp.oeroded2 < 3 && !rn2(9));
            }
        }
        /* and very rarely, greased */
        if (!rn2(1000))
            otmp.greased = 1;
    }
}

// src/mkobj.c mksobj() — create a specific object type.
//
// Only the identity and o_id allocation are ported so far. mksobj_init(), which
// carries the per-class enchantment, blessing, corpse-type and artifact draws,
// needs artifacts and monster-hatching and lands with those subsystems. Nothing
// here invents a draw it cannot justify.
export function mksobj(otyp, init, artif) {
    const objects = game.objects;
    const otmp = {
        otyp,
        oclass: objects[otyp].oc_class,
        quan: 1,
        spe: 0,
        blessed: 0,
        cursed: 0,
        oeaten: 0,
        age: Math.max(game.moves ?? 1, 1),
        corpsenm: NON_PM,
        o_id: next_ident(),
    };
    unknow_object(otmp);

    /* src/mkobj.c:1197 — mkobj_erosions() is the last statement of
       mksobj_init(), not of mksobj(), so an uninitialised object must not
       draw for erosion. */
    if (init)
        mksobj_init(otmp, artif);

    /* src/mkobj.c:1200-1227 — "some things must get done (corpsenm, timers)
       even if init = 0". This block is what makes a corpse draw rndmonnum()
       for its species and rn2(2) for its gender before mkcorpstat() overrides
       the species; the draws happen either way. */
    switch (otmp.otyp) {
    case ONAMES.CORPSE:
        if (otmp.corpsenm === NON_PM) {
            otmp.corpsenm = undead_to_corpse(rndmonnum());
            if (game.mvitals[otmp.corpsenm].mvflags & (G_NOCORPSE | G_GONE))
                otmp.corpsenm = pmIndexOf(game.urole?.mnum);
        }
        /* FALLTHRU */
    case ONAMES.STATUE:
    case ONAMES.FIGURINE:
        if (otmp.corpsenm === NON_PM)
            otmp.corpsenm = rndmonnum();
        if (otmp.corpsenm !== NON_PM) {
            const ptr = game.mons[otmp.corpsenm];
            otmp.spe = is_neuter(ptr) ? CORPSTAT_NEUTER
                     : is_female(ptr) ? CORPSTAT_FEMALE
                     : is_male(ptr) ? CORPSTAT_MALE
                     : rn2(2) ? CORPSTAT_FEMALE : CORPSTAT_MALE;
        }
        /* FALLTHRU */
    case ONAMES.EGG:
        set_corpsenm(otmp, otmp.corpsenm);
        break;
    case ONAMES.BOULDER:
        otmp.next_boulder = 0;
        break;
    default:
        break;
    }
    return otmp;
}

// src/mondata.c:1305 little_to_big() / :1318 big_to_little()
function little_to_big(montype) {
    const p = GROWNUPS.find(([baby]) => baby === montype);
    return p ? p[1] : montype;
}
function big_to_little(montype) {
    const p = GROWNUPS.find(([, adult]) => adult === montype);
    return p ? p[0] : montype;
}

const lays_eggs = (ptr) => (ptr.mflags1 & MFLAGS.M1_OVIPAROUS) !== 0;

// src/mon.c:5538 — #define BREEDER_EGG (!rn2(77))
//
// This is a DRAW inside can_be_hatched(), which the EGG branch of mksobj_init()
// calls up to 200 times. C's `||` short-circuits, so the draw only happens for
// an egg-laying species that is not a killer bee or gargoyle; getting that
// ordering wrong changes the call count, not just the values.
const BREEDER_EGG = () => !rn2(77);

// src/mkobj.c can_be_hatched()
function can_be_hatched(mnum) {
    if (mnum === PMNAMES.PM_SCORPIUS)
        mnum = PMNAMES.PM_SCORPION;

    mnum = little_to_big(mnum);
    /* Queen bees lay killer bee eggs (usually), but killer bees don't grow
       into queen bees. Ditto for [winged-]gargoyles. */
    if (mnum === PMNAMES.PM_KILLER_BEE || mnum === PMNAMES.PM_GARGOYLE
        || (lays_eggs(game.mons[mnum])
            && (BREEDER_EGG()
                || (mnum !== PMNAMES.PM_QUEEN_BEE
                    && mnum !== PMNAMES.PM_WINGED_GARGOYLE))))
        return mnum;
    return NON_PM;
}

// src/mon.c dead_species() — genociding either the baby or the adult form
// kills the eggs of both. Extinction by overpopulation does not.
function dead_species(m_idx, egg) {
    if (m_idx < 0)
        return true;
    const alt_idx = egg ? big_to_little(m_idx) : m_idx;
    return (game.mvitals[m_idx].mvflags & G_GENOD) !== 0
        || (game.mvitals[alt_idx].mvflags & G_GENOD) !== 0;
}

// src/eat.c:143 tintxts[] has 16 entries including the "" terminator, so
// TTSZ - 1 is 15. src/read.c:283 candy_wrappers[] has 13.
const TTSZ = 16;
const ROTTEN_TIN = 0, HOMEMADE_TIN = 1;
const SPINACH_TIN = -1, RANDOM_TIN = -2;   /* include/obj.h sentinels */
const N_CANDY_WRAPPERS = 13;

// src/eat.c set_tin_variety() — only the SPINACH_TIN and RANDOM_TIN paths are
// reachable from mksobj_init(); HEALTHY_TIN comes from eating code.
function set_tin_variety(obj, forcetype) {
    let r;
    const mnum = obj.corpsenm;

    if (forcetype === SPINACH_TIN) {
        obj.corpsenm = NON_PM;
        obj.spe = 1;           /* spinach */
        return;
    } else if (forcetype >= 0 && forcetype < TTSZ - 1) {
        r = forcetype;
    } else {                   /* RANDOM_TIN */
        r = rn2(TTSZ - 1);
        if (r === ROTTEN_TIN && mnum >= 0 && nonrotting_corpse(mnum))
            r = HOMEMADE_TIN;  /* lizards don't rot */
    }
    obj.spe = -(r + 1);
}

const nonrotting_corpse = (mnum) =>
    mnum === PMNAMES.PM_LIZARD || mnum === PMNAMES.PM_LICHEN;

// src/read.c assign_candy_wrapper() — skips candy_wrappers[0].
function assign_candy_wrapper(obj) {
    if (obj.otyp === ONAMES.CANDY_BAR)
        obj.spe = 1 + rn2(N_CANDY_WRAPPERS - 1);
}

// include/obj.h:327 Is_pudding()
function Is_pudding(o) {
    return o.otyp === ONAMES.GLOB_OF_GRAY_OOZE
        || o.otyp === ONAMES.GLOB_OF_BROWN_PUDDING
        || o.otyp === ONAMES.GLOB_OF_GREEN_SLIME
        || o.otyp === ONAMES.GLOB_OF_BLACK_PUDDING;
}

// src/timeout.c start_glob_timeout() — when the caller passes 0, the shrink
// time is 25 + rn2(5) - 2.
function start_glob_timeout(obj, when) {
    if (when < 1)
        when = 25 + rn2(5) - 2;
    obj.shrink_when = when;
}

// src/objnam.c:5403 rnd_class() — pick within an otyp range by oc_prob.
// Falls back to a flat rn1() when the whole range has zero probability, which
// is a different draw, not just a different value.
export function rnd_class(first, last) {
    const objects = game.objects;
    let sum = 0;

    if (last > first) {
        for (let i = first; i <= last; i++)
            sum += objects[i].oc_prob;
        if (!sum)
            return rn1(last - first + 1, first);
        let x = rnd(sum);
        for (let i = first; i <= last; i++)
            if ((x -= objects[i].oc_prob) <= 0)
                return i;
    }
    return (first === last) ? first : 0 /* STRANGE_OBJECT */;
}

const Is_mbag = (o) =>
    o.otyp === ONAMES.BAG_OF_HOLDING || o.otyp === ONAMES.BAG_OF_TRICKS;

// src/mkobj.c:315 mkbox_cnts() — fill a container.
//
// The capacity `n` depends on whether the box is locked, and the loop count is
// rn2(n + 1), so an unlocked large box and a locked chest draw different
// numbers of times before anything is created.
export function mkbox_cnts(box) {
    let n;
    box.cobj = [];

    switch (box.otyp) {
    case ONAMES.ICE_BOX:
        n = 20;
        break;
    case ONAMES.CHEST:
        n = box.olocked ? 7 : 5;
        break;
    case ONAMES.LARGE_BOX:
        n = box.olocked ? 5 : 3;
        break;
    case ONAMES.SACK:
    case ONAMES.OILSKIN_SACK:
        /* initial inventory: a sack starts out empty */
        if ((game.moves ?? 1) <= 1 && !game.in_mklev) {
            n = 0;
            break;
        }
        /* FALLTHRU */
    case ONAMES.BAG_OF_HOLDING:
        n = 1;
        break;
    default:
        n = 0;
        break;
    }

    for (n = rn2(n + 1); n > 0; n--) {
        let otmp;
        if (box.otyp === ONAMES.ICE_BOX) {
            otmp = mksobj(ONAMES.CORPSE, true, false);
            otmp.age = 0;
        } else {
            let tprob, idx = 0;
            for (tprob = rnd(100); (tprob -= boxiprobs[idx][0]) > 0; idx++)
                continue;
            otmp = mkobj(boxiprobs[idx][1], false);
            if (!otmp) continue;

            if (otmp.oclass === COIN_CLASS) {
                otmp.quan = rnd(level_difficulty() + 2) * rnd(75);
            } else {
                while (otmp.otyp === ONAMES.ROCK) {
                    otmp.otyp = rnd_class(ONAMES.DILITHIUM_CRYSTAL,
                                          ONAMES.LOADSTONE);
                    if (otmp.quan > 2) otmp.quan = 1;
                }
            }
            if (box.otyp === ONAMES.BAG_OF_HOLDING) {
                if (Is_mbag(otmp)) {
                    otmp.otyp = ONAMES.SACK;
                    otmp.spe = 0;
                } else {
                    while (otmp.otyp === ONAMES.WAN_CANCELLATION)
                        otmp.otyp = rnd_class(ONAMES.WAN_LIGHT,
                                              ONAMES.WAN_LIGHTNING);
                }
            }
        }
        box.cobj.push(otmp);
    }
}

// src/mon.c:417 undead_to_corpse() — a zombie or mummy leaves its living
// species' corpse. Pure lookup, no draw.
const UNDEAD_TO_CORPSE = (() => {
    const P = PMNAMES, m = new Map();
    const pairs = [
        ['KOBOLD', ['KOBOLD_ZOMBIE', 'KOBOLD_MUMMY']],
        ['DWARF', ['DWARF_ZOMBIE', 'DWARF_MUMMY']],
        ['GNOME', ['GNOME_ZOMBIE', 'GNOME_MUMMY']],
        ['ORC', ['ORC_ZOMBIE', 'ORC_MUMMY']],
        ['ELF', ['ELF_ZOMBIE', 'ELF_MUMMY']],
        ['HUMAN', ['VAMPIRE', 'VAMPIRE_LEADER', 'HUMAN_ZOMBIE', 'HUMAN_MUMMY']],
        ['GIANT', ['GIANT_ZOMBIE', 'GIANT_MUMMY']],
        ['ETTIN', ['ETTIN_ZOMBIE', 'ETTIN_MUMMY']],
    ];
    for (const [live, undead] of pairs)
        for (const u of undead)
            if (P[`PM_${u}`] !== undefined && P[`PM_${live}`] !== undefined)
                m.set(P[`PM_${u}`], P[`PM_${live}`]);
    return m;
})();

function undead_to_corpse(mndx) {
    return UNDEAD_TO_CORPSE.get(mndx) ?? mndx;
}

// src/mkobj.c:1090 unknow_object() — "set up dknown and known: non-0 for some
// things". The last line is the one that matters here: object types that do NOT
// use the known flag get it set TRUE, which is what makes a starting scroll or
// potion eligible for discovery in ini_inv_use_obj().
function unknow_object(obj) {
    obj.dknown = 0;
    obj.bknown = obj.rknown = 0;
    obj.cknown = obj.lknown = 0;
    obj.tknown = 0;
    obj.known = game.objects[obj.otyp].oc_uses_known ? 0 : 1;
}

// src/mkobj.c g_at() — gold already on this square, if any.
function g_at(x, y) {
    return (game.level?.objects || []).find(
        o => o.ox === x && o.oy === y && o.oclass === COIN_CLASS) ?? null;
}

// src/mkobj.c:2002 mkgold()
//
// The g_at() merge matters for the stream: when gold is already on the square
// the existing pile absorbs the amount and no object is created, so there is no
// next_ident(). A vault fills four distinct squares, so it makes four.
// src/mkobj.c mksobj_at() — make it, then PUT IT ON THE FLOOR. Returning the
// object without place_object() meant nothing ever reached level.objects, so
// every floor object the level generator produced vanished on creation: the
// pet's search box was always empty and objects the screens expect to see were
// never drawn.
export function mksobj_at(otyp, x, y, init, artif) {
    const otmp = mksobj(otyp, init, artif);
    place_object(otmp, x, y);
    return otmp;
}

// src/mkobj.c mkobj_at()
export function mkobj_at(oclass, x, y, artif) {
    const otmp = mkobj(oclass, artif);
    place_object(otmp, x, y);
    return otmp;
}

// src/mkobj.c place_object() — C PREPENDS to fobj:
//
//     otmp->nobj = fobj;
//     fobj = otmp;
//
// so the level's object list is newest-first, and anything that walks it in
// order sees the most recently created object first. dog_goal()'s search walks
// it calling dogfood() on each, and dogfood() draws, so the order is part of
// the PRNG contract.
export function place_object(otmp, x, y) {
    otmp.ox = x;
    otmp.oy = y;
    (game.level.objects ||= []).unshift(otmp);
}

export function mkgold(amount, x, y) {
    let gold = g_at(x, y);

    if (amount <= 0) {
        /* src/mkobj.c:2008 — the multiplier uses depth(), the amount uses
           level_difficulty(). They agree on an ordinary level and diverge once
           the hero carries the Amulet or reaches the endgame, where
           level_difficulty() stops tracking depth. */
        const mul = rnd(Math.trunc(30 / Math.max(12 - depth(game.u.uz), 2)));
        amount = 1 + rnd(level_difficulty() + 2) * mul;
    }
    if (gold) {
        gold.quan += amount;
    } else {
        /* C calls mksobj_at(), which routes through place_object() and so
           PREPENDS. Building the object by hand and pushing put gold at the
           wrong end of the list, and dog_goal() walks that list in order
           calling dogfood(), which draws. */
        gold = mksobj_at(ONAMES.GOLD_PIECE, x, y, true, false);
        gold.quan = amount;
    }
    /* src/mkobj.c:2018 — runs on BOTH branches, so a pile that just grew gets
       reweighed too. can_carry() reads this as its `newload`. */
    gold.owt = weight(gold);
    return gold;
}

// src/mkobj.c:2052 special_corpse() — lizards and lichen don't rot, trolls
// and Riders auto-revive.
export function special_corpse(num) {
    if (num === NON_PM) return false;
    return num === PMNAMES.PM_LIZARD || num === PMNAMES.PM_LICHEN
        || game.mons[num].mlet === MONSYMS.S_TROLL
        || is_rider(game.mons[num]);
}

// src/mkobj.c:1976 set_corpsenm()
export function set_corpsenm(obj, id) {
    obj.corpsenm = id;
    switch (obj.otyp) {
    case ONAMES.CORPSE:
        start_corpse_timeout(obj);
        break;
    default:
        /* FIGURINE and EGG attach their own timers; both need the timer
           subsystem, which is not ported. Neither draws. */
        break;
    }
}

// src/mkobj.c:1391 start_corpse_timeout() — the single rnz() here is five
// PRNG calls in the log (rn2(1000), rn2(4), rne(4), rn2(2)) recorded under
// one rnz() entry.
export function start_corpse_timeout(body) {
    if (body.corpsenm === PMNAMES.PM_LIZARD
        || body.corpsenm === PMNAMES.PM_LICHEN)
        return;

    const rot_adjust = game.in_mklev ? 25 : 10;
    const age = Math.max(game.moves ?? 1, 1) - body.age;
    let when = (age > ROT_AGE) ? rot_adjust : (ROT_AGE - age);
    when += rnz(rot_adjust) - rot_adjust;

    if (is_rider(game.mons[body.corpsenm])) {
        /* rider_revival_time() draws; no Rider is generatable here */
        note_unported_obj('rider_revival_time');
    } else if (game.mons[body.corpsenm].mlet === MONSYMS.S_TROLL) {
        for (let a = 2; a <= TAINT_AGE; a++)
            if (!rn2(TROLL_REVIVE_CHANCE)) {
                when = a;
                break;
            }
    }
    body.rot_when = when;
}

// include/objclass.h OBJ_NAME() — obj_descr[].oc_name; a null name marks a
// table slot that is not a real object.
function obj_descr_name(i) {
    return obj_descr[game.objects[i].oc_name_idx]?.oc_name ?? null;
}

function note_unported_obj(what) {
    (game.unported ||= new Set()).add(what);
}

/* Is_rogue_level() is include/dungeon.h's Lcheck against rogue_level and lives
   in js/const.js with the other level tests. The copy that used to
   be here tested game.level.flags.is_rogue_level instead, which is a different
   question and a flag nothing sets. */
function Inhell() {
    return game.dungeons?.[game.u?.uz?.dnum]?.flags?.hellish === true;
}

// src/mkobj.c:2676 add_to_container() — link an object into a container's cobj
// chain, or merge it into an identical stack already there.
//
// C PREPENDS: `obj->nobj = container->cobj; container->cobj = obj;`. The merge
// loop runs first and walks the existing contents in that same order, so the
// returned pointer is the SURVIVING object, which is not always the one passed
// in. Callers that keep using `obj` after this without taking the return value
// are using a freed pointer.
export function add_to_container(container, obj) {
    /* C also panics on obj->where != OBJ_FREE and calls obj_no_longer_held()
       when the container is on the floor; neither is modelled yet, and both
       are bookkeeping rather than draws. */
    for (const otmp of (container.cobj || []))
        if (merged({ o: otmp }, { o: obj }) !== 0)
            return otmp;

    obj.where = OBJ_CONTAINED;
    obj.ocontainer = container;
    (container.cobj ||= []).unshift(obj);
    return obj;
}

