import { NODIR, IMMEDIATE } from './const.js';
// o_init.js — object initialisation and description shuffling.
// C ref: src/o_init.c
//
// This is the first thing in the game that draws a random number: every
// recorded session's very first PRNG call is
// `rn2(2) @ randomize_gem_colors(o_init.c:89)`. Nothing later in the stream can
// align until this file does.
//
// The object tables come from js/objects_data.js, generated by
// tools/gen-objects.mjs.

import { game } from './gstate.js';
import { PMNAMES } from './monst_data.js';
import { exercise } from './attrib.js';
import { gem_learned } from './shk.js';
import { impossible } from './pline.js';
import { docall, objtyp_is_callable } from './do_name.js';
import { BUFSZ } from './const.js';
import { update_inventory, inv_order, loot_classify } from './invent.js';
import { disp_artifact_discoveries, dump_artifact_info } from './artifact.js';
import { Hallucination } from './youprop.js';
import { A_WIS } from './const.js';
import { rn2 } from './rng.js';
import { obj_typename, OBJ_DESCR as objDescrOf, OBJ_NAME,
         Japanese_item_name } from './objnam.js';
import { ATR_NONE, ATR_INVERSE, tty_create_nhwindow, tty_start_menu,
         tty_add_menu, tty_add_menu_str, tty_end_menu, tty_select_menu,
         tty_destroy_nhwindow, tty_putstr, tty_display_nhwindow,
         tty_next_page, NHW_MENU, NHW_TEXT } from './tty/wintty.js';
import { NO_COLOR } from './terminal.js';
import { MENU_BEHAVE_STANDARD, MENU_ITEMFLAGS_NONE, MENU_ITEMFLAGS_SELECTED,
         PICK_ONE, NON_PM, MENU_TRADITIONAL, MENU_COMBINATION, MENU_PARTIAL
       } from './const.js';
import { xwaitforspace } from './tty/getline.js';
import { tty_yn_function } from './tty/topl.js';
import { def_oc_syms } from './drawing_data.js';
import { def_char_to_objclass } from './sp_lev.js';
import { You } from './pline.js';
import { tty_clear_nhwindow_message } from './display.js';
import {
    objects as OBJECTS_INIT, obj_descr as OBJ_DESCR_INIT,
    NUM_OBJECTS, ONAMES, OCLASSES,
} from './objects_data.js';

const {
    ARMOR_CLASS, RING_CLASS, AMULET_CLASS,
    POTION_CLASS, SCROLL_CLASS, SPBOOK_CLASS, WAND_CLASS, GEM_CLASS,
    VENOM_CLASS, MAXOCLASSES,
} = OCLASSES;

const {
    HELMET, HELM_OF_TELEPATHY, LEATHER_GLOVES, GAUNTLETS_OF_DEXTERITY,
    CLOAK_OF_PROTECTION, CLOAK_OF_DISPLACEMENT, SPEED_BOOTS, LEVITATION_BOOTS,
    POT_WATER, WAN_NOTHING, LAST_REAL_GEM,
} = ONAMES;

// include/objclass.h — oc_dir values.
/* NODIR and IMMEDIATE live in js/const.js with the oc_dir family. */

// The generated table stores oc_class as the C identifier ("WEAPON_CLASS");
// resolve to the numeric class once so the hot paths compare ints as C does.
function numericClass(v) {
    return typeof v === 'string' ? OCLASSES[v] : v;
}

// A fresh, mutable copy of objects[]. shuffle() swaps fields between entries,
// so this is per-game state, never the shared generated table.
export function reset_objects() {
    game.objects = OBJECTS_INIT.map(o => ({ ...o, oc_class: numericClass(o.oc_class) }));
    game.obj_descr = OBJ_DESCR_INIT.map(d => ({ ...d }));
    // src/options.c:7341 initoptions_finish(), before object use. The table
    // is per game here; the preferred fruit remains in the separate list.
    game.obj_descr[ONAMES.SLIME_MOLD].oc_name = 'fruit';
    game.bases = new Array(MAXOCLASSES + 2).fill(0);
    game.oclass_prob_totals = new Array(MAXOCLASSES).fill(0);
    return game.objects;
}

// OBJ_DESCR(obj) from include/objclass.h
function OBJ_DESCR(i) { return game.obj_descr[i].oc_descr; }

// src/o_init.c:54 setgemprobs()
// init_objects() calls this with dlev == 0, so lev is 0 there.
export function setgemprobs(dlev) {
    const objects = game.objects;
    let j, first, lev, sum = 0;

    if (dlev) {
        const dgn = game.dungeons?.[dlev.dnum];
        const ledger = (dgn?.ledger_start ?? 0) + dlev.dlevel;
        const last = game.dungeons?.[game.dungeons.length - 1];
        const maxledger = last
            ? last.ledger_start + last.num_dunlevs
            : ledger;
        lev = Math.min(ledger, maxledger);
    } else {
        lev = 0;
    }
    first = game.bases[GEM_CLASS];

    for (j = 0; j < 9 - Math.trunc(lev / 3); j++)
        objects[first + j].oc_prob = 0;
    first += j;

    for (j = first; j <= LAST_REAL_GEM; j++)
        objects[j].oc_prob = Math.trunc((171 + j - first) / (LAST_REAL_GEM + 1 - first));

    /* recompute GEM_CLASS total oc_prob - including rocks/stones */
    for (j = game.bases[GEM_CLASS]; j < game.bases[GEM_CLASS + 1]; j++)
        sum += objects[j].oc_prob;
    game.oclass_prob_totals[GEM_CLASS] = sum;
}

// src/o_init.c:369 oinit(), level-dependent object probabilities.
export function oinit() {
    setgemprobs(game.u.uz);
}

// src/o_init.c:85 randomize_gem_colors()
// Three draws, and they are the first three of every game.
export function randomize_gem_colors() {
    const objects = game.objects;
    const { TURQUOISE, SAPPHIRE, AQUAMARINE, FLUORITE, DIAMOND, EMERALD } = ONAMES;
    const COPY_OBJ_DESCR = (o_dst, o_src) => {
        objects[o_dst].oc_descr_idx = objects[o_src].oc_descr_idx;
        objects[o_dst].oc_color = objects[o_src].oc_color;
    };

    if (rn2(2)) { /* change turquoise from green to blue? */
        COPY_OBJ_DESCR(TURQUOISE, SAPPHIRE);
    }
    if (rn2(2)) { /* change aquamarine from green to blue? */
        COPY_OBJ_DESCR(AQUAMARINE, SAPPHIRE);
    }
    switch (rn2(4)) { /* change fluorite from violet? */
    case 0:
        break;
    case 1: /* blue */
        COPY_OBJ_DESCR(FLUORITE, SAPPHIRE);
        break;
    case 2: /* white */
        COPY_OBJ_DESCR(FLUORITE, DIAMOND);
        break;
    case 3: /* green */
        COPY_OBJ_DESCR(FLUORITE, EMERALD);
        break;
    }
}

// src/o_init.c:113 shuffle() — shuffle descriptions on objects o_low to o_high.
// This is the bulk of the corpus's o_init draws (10,725 of them). The rejection
// loop matters: every rejected candidate consumes another rn2.
function shuffle(o_low, o_high, domaterial) {
    const objects = game.objects;
    let i, j, num_to_shuffle;
    let sw, color;

    for (num_to_shuffle = 0, j = o_low; j <= o_high; j++)
        if (!objects[j].oc_name_known)
            num_to_shuffle++;
    if (num_to_shuffle < 2)
        return;

    for (j = o_low; j <= o_high; j++) {
        if (objects[j].oc_name_known)
            continue;
        do
            i = j + rn2(o_high - j + 1);
        while (objects[i].oc_name_known);
        sw = objects[j].oc_descr_idx;
        objects[j].oc_descr_idx = objects[i].oc_descr_idx;
        objects[i].oc_descr_idx = sw;
        sw = objects[j].oc_tough;
        objects[j].oc_tough = objects[i].oc_tough;
        objects[i].oc_tough = sw;
        color = objects[j].oc_color;
        objects[j].oc_color = objects[i].oc_color;
        objects[i].oc_color = color;

        /* shuffle material */
        if (domaterial) {
            sw = objects[j].oc_material;
            objects[j].oc_material = objects[i].oc_material;
            objects[i].oc_material = sw;
        }
    }
}

// src/o_init.c:240 init_oclass_probs()
export function init_oclass_probs() {
    const objects = game.objects;
    let i, sum, oclass;

    for (oclass = 0; oclass < MAXOCLASSES; ++oclass) {
        sum = 0;
        /* note: for ILLOBJ_CLASS, bases[oclass+1]-1 isn't the last item
           in the class; but all the generic items have probability 0 so
           adding them to 'sum' has no impact */
        for (i = game.bases[oclass]; i < game.bases[oclass + 1]; ++i) {
            sum += objects[i].oc_prob;
        }
        game.oclass_prob_totals[oclass] = sum;
    }
}

// src/o_init.c:269 obj_shuffle_range() — the range otyp shares descriptions
// with. Returns { lo, hi } instead of writing through out-pointers.
export function obj_shuffle_range(otyp) {
    const objects = game.objects;
    let i;
    const ocls = objects[otyp].oc_class;

    /* default is just the object itself */
    let lo = otyp, hi = otyp;

    switch (ocls) {
    case ARMOR_CLASS:
        if (otyp >= HELMET && otyp <= HELM_OF_TELEPATHY)
            { lo = HELMET; hi = HELM_OF_TELEPATHY; }
        else if (otyp >= LEATHER_GLOVES && otyp <= GAUNTLETS_OF_DEXTERITY)
            { lo = LEATHER_GLOVES; hi = GAUNTLETS_OF_DEXTERITY; }
        else if (otyp >= CLOAK_OF_PROTECTION && otyp <= CLOAK_OF_DISPLACEMENT)
            { lo = CLOAK_OF_PROTECTION; hi = CLOAK_OF_DISPLACEMENT; }
        else if (otyp >= SPEED_BOOTS && otyp <= LEVITATION_BOOTS)
            { lo = SPEED_BOOTS; hi = LEVITATION_BOOTS; }
        break;
    case POTION_CLASS:
        /* potion of water has the only fixed description */
        lo = game.bases[POTION_CLASS];
        hi = POT_WATER - 1;
        break;
    case AMULET_CLASS:
    case SCROLL_CLASS:
    case SPBOOK_CLASS:
        /* exclude non-magic types and also unique ones */
        lo = game.bases[ocls];
        for (i = lo; objects[i].oc_class === ocls; i++)
            if (objects[i].oc_unique || !objects[i].oc_magic)
                break;
        hi = i - 1;
        break;
    case RING_CLASS:
    case WAND_CLASS:
    case VENOM_CLASS:
        /* entire class */
        lo = game.bases[ocls];
        hi = game.bases[ocls + 1] - 1;
        break;
    }

    /* artifact checking might ask about item which isn't part of any range
       but fell within the classes that do have ranges specified above */
    if (otyp < lo || otyp > hi) { lo = otyp; hi = otyp; }
    return { lo, hi };
}

// src/o_init.c:322 shuffle_all() — randomize object descriptions.
function shuffle_all() {
    /* entire classes; obj_shuffle_range() handles their exceptions */
    const shuffle_classes = [
        AMULET_CLASS, POTION_CLASS, RING_CLASS, SCROLL_CLASS,
        SPBOOK_CLASS, WAND_CLASS, VENOM_CLASS,
    ];
    /* sub-class type ranges (one item from each group) */
    const shuffle_types = [
        HELMET, LEATHER_GLOVES, CLOAK_OF_PROTECTION, SPEED_BOOTS,
    ];
    let idx;

    /* do whole classes (amulets, &c) */
    for (idx = 0; idx < shuffle_classes.length; idx++) {
        const { lo, hi } = obj_shuffle_range(game.bases[shuffle_classes[idx]]);
        shuffle(lo, hi, true);
    }
    /* do type ranges (helms, &c) */
    for (idx = 0; idx < shuffle_types.length; idx++) {
        const { lo, hi } = obj_shuffle_range(shuffle_types[idx]);
        shuffle(lo, hi, false);
    }
}

// src/o_init.c:151 init_objects()
export function init_objects() {
    reset_objects();
    const objects = game.objects;
    let i, first, last, prevoclass;
    let oclass;

    for (i = 0; i <= MAXOCLASSES; i++)
        game.bases[i] = 0;

    /* initialize object descriptions */
    for (i = 0; i < NUM_OBJECTS; i++)
        objects[i].oc_name_idx = objects[i].oc_descr_idx = i;

    /* init base; if probs given check that they add up to 1000,
       otherwise compute probs */
    first = MAXOCLASSES;
    prevoclass = -1;
    while (first < NUM_OBJECTS) {
        oclass = objects[first].oc_class;

        last = first + 1;
        while (last < NUM_OBJECTS && objects[last].oc_class === oclass)
            last++;
        game.bases[oclass] = first;

        if (oclass === GEM_CLASS) {
            setgemprobs(null);
            randomize_gem_colors();
        }
        first = last;
        prevoclass = oclass;
    }
    /* extra entry allows deriving the range of a class via
       bases[class] through bases[class+1]-1 for all classes */
    game.bases[MAXOCLASSES] = game.bases[MAXOCLASSES + 1] = NUM_OBJECTS;

    /* guarantee that there are no gaps in bases[] */
    for (last = MAXOCLASSES - 1; last >= 0; --last)
        if (!game.bases[last])
            game.bases[last] = game.bases[last + 1];

    /* check objects[].oc_name_known.
       The C repairs a mismatch silently when sanity_check is off, and the
       repair changes oc_name_known — which changes how many draws shuffle()
       makes. It has to be ported, not skipped. */
    for (i = MAXOCLASSES; i < NUM_OBJECTS; ++i) {
        const nmkn = objects[i].oc_name_known !== 0 ? 1 : 0;

        if (((OBJ_DESCR(i) ? 0 : 1) ^ nmkn) !== 0) {
            /* repair the mistake and keep going */
            objects[i].oc_name_known = nmkn ? 0 : 1;
        }
    }

    /* compute oclass_prob_totals */
    init_oclass_probs();

    /* shuffle descriptions */
    shuffle_all();

    objects[WAN_NOTHING].oc_dir = rn2(2) ? NODIR : IMMEDIATE;
}

// ---------------------------------------------------------------------------
// Discoveries
// ---------------------------------------------------------------------------

// src/o_init.c:599 disco_order_let / disco_orders_descr.
const disco_order_let = 'osca';
const disco_orders_descr = [
    'by order of discovery within each class',
    'sortloot order (by class with some sub-class groupings)',
    'alphabetical within each class',
    'alphabetical across all classes',
];

// src/o_init.c:542 uniq_objs, in C's relic order.
const uniq_objs = [ONAMES.AMULET_OF_YENDOR, ONAMES.BELL_OF_OPENING,
                   ONAMES.SPE_BOOK_OF_THE_DEAD, ONAMES.CANDELABRUM_OF_INVOCATION];

// src/o_init.c:554 discovered_cmp(). Ignore the encountered marker.
function discovered_cmp(s1, s2) {
    s1 = s1.slice(2).toLowerCase();
    s2 = s2.slice(2).toLowerCase();
    return s1 < s2 ? -1 : s1 > s2 ? 1 : 0;
}

// src/o_init.c:568 sortloot_descr(). The temporary object has no owner.
function sortloot_descr(otyp) {
    const oc = game.objects[otyp];
    const o = { otyp, oclass: oc.oc_class, dknown: 1,
                known: Number(oc.oc_name_known || !oc.oc_uses_known),
                corpsenm: NON_PM };
    if (otyp === ONAMES.SLIME_MOLD)
        o.spe = game.context.current_fruit;
    const sl_cookie = {};
    loot_classify(sl_cookie, o);
    return String(sl_cookie.orderclass).padStart(2, '0')
        + String(sl_cookie.subclass).padStart(2, '0') + sl_cookie.disco + ' ';
}

// src/o_init.c:611 choose_disco_sort(). Choice persists across both commands.
export async function choose_disco_sort(mode) {
    const win = tty_create_nhwindow(NHW_MENU);
    tty_start_menu(win, MENU_BEHAVE_STANDARD);
    for (let i = 0; i < disco_orders_descr.length; i++) {
        const c = disco_order_let[i];
        tty_add_menu(win, null, c, c, 0, ATR_NONE, NO_COLOR,
                     disco_orders_descr[i], c === (game.flags.discosort ?? 'o')
                         ? MENU_ITEMFLAGS_SELECTED : MENU_ITEMFLAGS_NONE);
    }
    if (mode === 2) {
        tty_add_menu_str(win, '');
        tty_add_menu_str(win, 'Note: full alphabetical and alphabetical within class');
        tty_add_menu_str(win, '      are equivalent for single class discovery, but');
        tty_add_menu_str(win, '      will matter for future use of total discoveries.');
    }
    tty_end_menu(win, 'Ordering of discoveries');
    const selected = await tty_select_menu(win, PICK_ONE);
    tty_destroy_nhwindow(win);
    const n = selected.cancelled ? -1 : selected.length;
    if (n > 0) {
        let choice = selected[0];
        if (n > 1 && choice === (game.flags.discosort ?? 'o'))
            choice = selected[1];
        game.flags.discosort = choice;
    }
    return n;
}

// src/o_init.c:520 discover_object()
//
// src/o_init.c:442 observe_object() — naming an object in view marks its
// type as encountered. xname() calls this on every use, which is how a
// starting kit ends up '  listed' rather than '* listed' in discoveries.
export function observe_object(obj) {
    const oindx = obj.otyp;
    /* Skip generic objects and STRANGE_OBJECT. */
    if (oindx >= ONAMES.FIRST_OBJECT && !Hallucination()) {
        obj.dknown = 1;
        discover_object(oindx, false, true, false);
    }
}

// svd.disco[] is NOT a flat list: it is indexed by object class, filled from
// svb.bases[class] upward, so discoveries stay grouped by class in the order
// they were made. dodiscovered() walks it that way.
export function discover_object(oindx, mark_as_known, mark_as_encountered,
                                credit_hero) {
    const objects = game.objects;
    if (oindx < ONAMES.FIRST_OBJECT)
        return;

    if ((!objects[oindx].oc_name_known && mark_as_known)
        || (!objects[oindx].oc_encountered && mark_as_encountered)
        /* src/o_init.c — a Samurai's Japanese-named items go on the
           discoveries list even when the type is pre-known (a knife has no
           appearance so ships name_known; "shito [knife]" still lists) */
        || ((game.urole?.mnum === 'PM_SAMURAI'
             || game.urole?.mnum === PMNAMES.PM_SAMURAI)
            && Japanese_item_name(oindx, null))) {
        const acls = objects[oindx].oc_class;
        game.disco ||= [];

        let dindx = game.bases[acls];
        for (; game.disco[dindx]; dindx++)
            if (game.disco[dindx] === oindx)
                break;
        game.disco[dindx] = oindx;

        if (mark_as_encountered)
            objects[oindx].oc_encountered = 1;
        if (!objects[oindx].oc_name_known && mark_as_known) {
            objects[oindx].oc_name_known = 1;
            /* src/o_init.c:478 — learning a NEW type exercises wisdom,
               one rn2(19); re-knowing draws nothing */
            if (credit_hero)
                exercise(A_WIS, true);
            if (game.program_state?.in_moveloop && !game.program_state_gameover) {
                if (objects[oindx].oc_class === GEM_CLASS)
                    gem_learned(oindx);
                update_inventory();
            }
        }
    }
}

// src/o_init.c:498 undiscover_object(); preserve identified or encountered types.
export async function undiscover_object(oindx) {
    const objects = game.objects;
    if (!objects[oindx].oc_name_known && !objects[oindx].oc_encountered) {
        const acls = objects[oindx].oc_class;
        let found = false, dindx = game.bases[acls];
        for (; dindx < NUM_OBJECTS && game.disco[dindx]
               && objects[dindx].oc_class === acls; dindx++) {
            if (found)
                game.disco[dindx - 1] = game.disco[dindx];
            else if (game.disco[dindx] === oindx)
                found = true;
        }
        if (found)
            game.disco[dindx - 1] = 0;
        else
            await impossible('named object not in disco');
        if (acls === GEM_CLASS)
            gem_learned(oindx);
    }
}

// src/o_init.c:660 interesting_to_discover()
function interesting_to_discover(i) {
    /* most players who don't speak Japanese manage to figure out what
       gunyoki, osaku, and so forth mean, but treat them as pre-discovered
       to be disclosed by '\' */
    if ((game.urole?.mnum === 'PM_SAMURAI'
         || game.urole?.mnum === PMNAMES.PM_SAMURAI)
        && Japanese_item_name(i, null))
        return true;

    const o = game.objects[i];
    return !!o.oc_uname
        || ((o.oc_name_known || o.oc_encountered) && objDescrOf(o) !== null);
}

// src/o_init.c:668 disco_typename() — augment obj_typename() with the
// English explanation of a Japanese item name: "shito [knife]", or spliced
// before " called"/" (" when those follow.
function disco_typename(otyp) {
    let result = obj_typename(otyp);

    if ((game.urole?.mnum === 'PM_SAMURAI'
         || game.urole?.mnum === PMNAMES.PM_SAMURAI)
        && Japanese_item_name(otyp, null)) {
        const actualn =
            ((otyp !== ONAMES.MAGIC_HARP && otyp !== ONAMES.WOODEN_HARP)
             || game.objects[otyp].oc_name_known)
            ? OBJ_NAME(game.objects[otyp]) : 'harp';
        if (!actualn) {
            ;
        } else if (result.includes(' called')) {
            result = result.replace(' called', ` [${actualn}] called`);
        } else if (result.includes(' (')) {
            result = result.replace(' (', ` [${actualn}] (`);
        } else {
            result += ` [${actualn}]`;
        }
    }
    return result;
}

// src/o_init.c:694 disco_append_typename(); preserve a trailing appearance
// when truncating a long type name, and append the price quote only if it fits.
function disco_append_typename(buf, dis) {
    const name = disco_typename(dis);
    const paren = name.lastIndexOf('(');
    if (buf.length + name.length < BUFSZ) {
        buf += name;
    } else if (paren > 0 && name[paren - 1] === ' ' && name.includes(')', paren)) {
        const suffix = name.slice(paren - 1);
        buf += name.slice(0, BUFSZ - 1 - buf.length - suffix.length) + suffix;
    } else {
        buf += name.slice(0, BUFSZ - 1 - buf.length);
    }
    const quote = append_price_quote(dis);
    if (quote.length < BUFSZ - buf.length - 1)
        buf += quote;
    return buf;
}

// src/shk.c:454 append_price_quote(), used unconditionally by discoveries.
function append_price_quote(otyp) {
    const oc = game.objects[otyp];
    const parts = [];
    if ((oc.oc_buy_minseen ?? -1) >= 0) {
        parts.push(oc.oc_buy_minseen === oc.oc_buy_maxseen
            ? `buy ${oc.oc_buy_minseen}`
            : `buy ${oc.oc_buy_minseen}-${oc.oc_buy_maxseen}`);
    }
    if ((oc.oc_sell_minseen ?? -1) >= 0) {
        parts.push(oc.oc_sell_minseen === oc.oc_sell_maxseen
            ? `sell ${oc.oc_sell_minseen}`
            : `sell ${oc.oc_sell_minseen}-${oc.oc_sell_maxseen}`);
    }
    return parts.length ? ` {${parts.join(' ')}}` : '';
}

// src/o_init.c:725 disco_fmt_uniq(). Unknown relics use their descriptions.
function disco_fmt_uniq(uidx) {
    const oc = game.objects[uidx];
    let buf = '  ' + (oc.oc_name_known ? OBJ_NAME(oc) : objDescrOf(oc));
    if (!oc.oc_name_known && oc.oc_class === SPBOOK_CLASS)
        buf += ' spellbook';
    return buf;
}

// src/o_init.c:745 disco_output_sorted(). Strip the six-character sort key.
function disco_output_sorted(tmpwin, sorted_lines, sorted_ct, lootsort) {
    sorted_lines.sort(discovered_cmp);
    for (let j = 0; j < sorted_ct; j++) {
        const p = sorted_lines[j];
        tty_putstr(tmpwin, 0, lootsort ? p[0] + p.slice(7) : p);
    }
    sorted_lines.length = 0;
}

// src/o_init.c:764 dodiscovered(). Relics and artifacts retain their own order.
export async function dodiscovered() {
    const objects = game.objects;
    if (!game.flags.discosort || !disco_order_let.includes(game.flags.discosort))
        game.flags.discosort = 'o';
    if (game.iflags?.menu_requested && await choose_disco_sort(1) < 0)
        return 0;
    const alphabyclass = game.flags.discosort === 'c';
    const alphabetized = game.flags.discosort === 'a' || alphabyclass;
    const lootsort = game.flags.discosort === 's';
    const sortindx = disco_order_let.indexOf(game.flags.discosort);
    const heading = game.iflags?.menu_headings?.attr ?? ATR_INVERSE;
    const win = tty_create_nhwindow(NHW_TEXT);
    tty_putstr(win, 0, 'Discoveries, ' + disco_orders_descr[sortindx]);
    tty_putstr(win, 0, '');
    let uniq_ct = 0;
    for (const uidx of uniq_objs) {
        if (objects[uidx].oc_name_known
            || (objects[uidx].oc_encountered && uidx !== ONAMES.AMULET_OF_YENDOR)) {
            if (!uniq_ct++)
                tty_putstr(win, heading, 'Unique items or Relics');
            tty_putstr(win, 0, disco_fmt_uniq(uidx));
        }
    }
    const arti_ct = disp_artifact_discoveries(win);
    const classes = [...inv_order()];
    if (!classes.includes(VENOM_CLASS))
        classes.push(VENOM_CLASS);
    let ct = uniq_ct + arti_ct;
    const sorted_lines = [];
    for (const oclass of classes) {
        let prev_class = oclass + 1;
        for (let i = game.bases[oclass];
             i < NUM_OBJECTS && objects[i].oc_class === oclass; i++) {
            const dis = game.disco?.[i];
            if (!dis || !interesting_to_discover(dis))
                continue;
            ct++;
            if (oclass !== prev_class) {
                if ((alphabyclass || lootsort) && sorted_lines.length)
                    disco_output_sorted(win, sorted_lines, sorted_lines.length, lootsort);
                if (!alphabetized || alphabyclass) {
                    tty_putstr(win, heading, let_to_name(oclass));
                    prev_class = oclass;
                }
            }
            let buf = objects[dis].oc_encountered ? '  ' : '* ';
            if (lootsort)
                buf += sortloot_descr(dis);
            buf = disco_append_typename(buf, dis);
            if (!alphabetized && !lootsort)
                tty_putstr(win, 0, buf);
            else
                sorted_lines.push(buf);
        }
    }
    if (!ct) {
        await You("haven't discovered anything yet...");
    } else {
        if (sorted_lines.length) {
            if ((uniq_ct || arti_ct) && alphabetized && !alphabyclass)
                tty_putstr(win, heading, 'Discovered items');
            disco_output_sorted(win, sorted_lines, sorted_lines.length, lootsort);
        }
        await tty_display_nhwindow(win);
        await xwaitforspace(' \r\n\x1b');
        while (game.morc !== '\x1b' && tty_next_page(win))
            await xwaitforspace(' \r\n\x1b');
    }
    tty_destroy_nhwindow(win);
    return 0;
}

// src/o_init.c:879 oclass_to_name().
function oclass_to_name(oclass) {
    return let_to_name(oclass).toLowerCase();
}

// src/o_init.c:891 doclassdisco(), including relic/artifact pseudo-classes.
export async function doclassdisco() {
    const prompt = 'View discoveries for which sort of objects?';
    const unique_items = 'unique items or relics', artifact_items = 'artifacts';
    if (!game.flags.discosort || !disco_order_let.includes(game.flags.discosort))
        game.flags.discosort = 'o';
    if (game.iflags?.menu_requested && await choose_disco_sort(2) < 0)
        return 0;
    const alphabetized = game.flags.discosort === 'a' || game.flags.discosort === 'c';
    const lootsort = game.flags.discosort === 's';
    const traditional = game.flags.menu_style === MENU_TRADITIONAL
        || game.flags.menu_style === MENU_COMBINATION;
    const objects = game.objects;
    let tmpwin = -1, discosyms = '', menulet = 97;
    if (!traditional) {
        tmpwin = tty_create_nhwindow(NHW_MENU);
        tty_start_menu(tmpwin, MENU_BEHAVE_STANDARD);
    }
    for (const uidx of uniq_objs) {
        if (objects[uidx].oc_name_known
            || (objects[uidx].oc_encountered && uidx !== ONAMES.AMULET_OF_YENDOR)) {
            discosyms += 'u';
            if (!traditional)
                tty_add_menu(tmpwin, null, 'u', String.fromCharCode(menulet++), 'r',
                             ATR_NONE, NO_COLOR, unique_items, MENU_ITEMFLAGS_NONE);
            break;
        }
    }
    if (disp_artifact_discoveries(-1) > 0) {
        discosyms += 'a';
        if (!traditional)
            tty_add_menu(tmpwin, null, 'a', String.fromCharCode(menulet++), 0,
                         ATR_NONE, NO_COLOR, artifact_items, MENU_ITEMFLAGS_NONE);
    }
    const allclasses = [...inv_order()];
    if (!allclasses.includes(VENOM_CLASS))
        allclasses.push(VENOM_CLASS);
    for (const oclass of allclasses) {
        const c = def_oc_syms[oclass];
        for (let i = game.bases[oclass];
             i < NUM_OBJECTS && objects[i].oc_class === oclass; i++) {
            const dis = game.disco?.[i];
            if (dis && interesting_to_discover(dis) && !discosyms.includes(c)) {
                discosyms += c;
                if (!traditional)
                    tty_add_menu(tmpwin, null, c, String.fromCharCode(menulet++), c,
                                 ATR_NONE, NO_COLOR, oclass_to_name(oclass),
                                 MENU_ITEMFLAGS_NONE);
            }
        }
    }
    if (!discosyms) {
        await You("haven't discovered any items yet.");
        if (tmpwin !== -1)
            tty_destroy_nhwindow(tmpwin);
        return 0;
    }
    let c = '';
    if (traditional) {
        let xtras = 0;
        for (const symbol of [...allclasses.map(cl => def_oc_syms[cl]), 'a', 'u', 'r']) {
            if (!discosyms.includes(symbol)) {
                if (!xtras++)
                    discosyms += '\x1b';
                discosyms += symbol;
            }
        }
        c = await tty_yn_function(prompt, discosyms, '\0', true);
        if (!c || c === '\0')
            tty_clear_nhwindow_message(game._topl_cury || 0);
    } else {
        if (discosyms.length === 1 && game.flags.menu_style === MENU_PARTIAL)
            c = discosyms[0];
        else {
            tty_end_menu(tmpwin, prompt);
            const picks = await tty_select_menu(tmpwin, PICK_ONE);
            c = picks[0] || '';
        }
        tty_destroy_nhwindow(tmpwin);
    }
    if (!c || c === '\0')
        return 0;
    tmpwin = tty_create_nhwindow(NHW_TEXT);
    let ct = 0;
    switch (c) {
    case 'u': case 'r':
        tty_putstr(tmpwin, game.iflags?.menu_headings?.attr ?? ATR_INVERSE,
                   'Unique items or relics');
        for (const uidx of uniq_objs) {
            if (objects[uidx].oc_name_known
                || (objects[uidx].oc_encountered && uidx !== ONAMES.AMULET_OF_YENDOR)) {
                ct++;
                tty_putstr(tmpwin, 0, disco_fmt_uniq(uidx));
            }
        }
        if (!ct)
            await You(`haven't discovered any ${unique_items} yet.`);
        break;
    case 'a':
        if (game.wizard
            && await tty_yn_function('Dump information about all artifacts?', 'yn', 'n', true) === 'y') {
            dump_artifact_info(tmpwin);
            ct = 1;
            break;
        }
        ct = disp_artifact_discoveries(tmpwin);
        if (!ct)
            await You(`haven't discovered any ${artifact_items} yet.`);
        break;
    default: {
        const oclass = def_char_to_objclass(c);
        if (oclass === MAXOCLASSES)
            impossible(`doclassdisco: invalid object class '${c}'`);
        const order = game.flags.discosort === 'o' ? 'order of discovery'
            : game.flags.discosort === 's' ? "'sortloot' order" : 'alphabetical order';
        tty_putstr(tmpwin, 0, `Discovered ${let_to_name(oclass)} in ${order}`);
        const sorted_lines = [];
        for (let i = game.bases[oclass]; i < game.bases[oclass + 1]; i++) {
            const dis = game.disco?.[i];
            if (dis && interesting_to_discover(dis)) {
                ct++;
                let buf = objects[dis].oc_encountered ? '  ' : '* ';
                if (lootsort)
                    buf += sortloot_descr(dis);
                buf = disco_append_typename(buf, dis);
                if (!alphabetized && !lootsort)
                    tty_putstr(tmpwin, 0, buf);
                else
                    sorted_lines.push(buf);
            }
        }
        if (!ct)
            await You(`haven't discovered any ${oclass_to_name(oclass)} yet.`);
        else if (sorted_lines.length)
            disco_output_sorted(tmpwin, sorted_lines, sorted_lines.length, lootsort);
        break;
    }
    }
    if (ct) {
        await tty_display_nhwindow(tmpwin);
        await xwaitforspace(' \r\n\x1b');
        while (game.morc !== '\x1b' && tty_next_page(tmpwin))
            await xwaitforspace(' \r\n\x1b');
    }
    tty_destroy_nhwindow(tmpwin);
    return 0;
}

// src/o_init.c:1131 rename_disco(); name a discovered type without an instance.
export async function rename_disco() {
    const {
        tty_create_nhwindow, tty_start_menu, tty_add_menu, tty_end_menu,
        tty_select_menu, tty_destroy_nhwindow, NHW_MENU,
    } = await import('./tty/wintty.js');
    const { MENU_BEHAVE_STANDARD, MENU_ITEMFLAGS_NONE, PICK_ONE } =
        await import('./const.js');
    const { NO_COLOR } = await import('./terminal.js');
    const { add_menu_heading } = await import('./options.js');
    const { You } = await import('./pline.js');
    const { pline } = await import('./display.js');
    const win = tty_create_nhwindow(NHW_MENU);
    tty_start_menu(win, MENU_BEHAVE_STANDARD);
    let ct = 0, mn = 0;
    for (const oclass of inv_order()) {
        let prev_class = oclass + 1;
        for (let i = game.bases[oclass];
             i < NUM_OBJECTS && game.objects[i].oc_class === oclass; i++) {
            const dis = game.disco?.[i];
            if (!dis || !interesting_to_discover(dis))
                continue;
            ct++;
            if (!objtyp_is_callable(dis))
                continue;
            mn++;
            if (oclass !== prev_class) {
                add_menu_heading(win, let_to_name(oclass));
                prev_class = oclass;
            }
            tty_add_menu(win, null, dis, 0, 0, ATR_NONE, NO_COLOR,
                         disco_append_typename('', dis), MENU_ITEMFLAGS_NONE);
        }
    }
    if (!ct) {
        await You("haven't discovered anything yet...");
    } else if (!mn) {
        await pline('None of your discoveries can be assigned names...');
    } else {
        tty_end_menu(win, 'Pick an object type to name');
        const picks = await tty_select_menu(win, PICK_ONE);
        const dis = picks[0] || ONAMES.STRANGE_OBJECT;
        if (dis !== ONAMES.STRANGE_OBJECT) {
            const oc = game.objects[dis];
            await docall({ otyp: dis, oclass: oc.oc_class, quan: 1,
                           known: !oc.oc_uses_known, dknown: 1 });
        }
    }
    tty_destroy_nhwindow(win);
}

// src/objnam.c let_to_name() — the plural class heading used in menus.
const CLASS_NAMES = {
    COIN_CLASS: 'Coins', AMULET_CLASS: 'Amulets', WEAPON_CLASS: 'Weapons',
    ARMOR_CLASS: 'Armor', FOOD_CLASS: 'Comestibles', SCROLL_CLASS: 'Scrolls',
    SPBOOK_CLASS: 'Spellbooks', POTION_CLASS: 'Potions', RING_CLASS: 'Rings',
    WAND_CLASS: 'Wands', TOOL_CLASS: 'Tools', GEM_CLASS: 'Gems/Stones',
    ROCK_CLASS: 'Boulders/Statues', BALL_CLASS: 'Iron balls',
    CHAIN_CLASS: 'Chains', VENOM_CLASS: 'Venoms',
};
function let_to_name(oclass) {
    for (const [k, v] of Object.entries(OCLASSES))
        if (v === oclass && CLASS_NAMES[k]) return CLASS_NAMES[k];
    return '';
}

// src/o_init.c makeknown() — fully discover an object type; the wisdom
// exercise only fires when the type was actually unknown.
export function makeknown(otyp) {
    discover_object(otyp, true, true, true);
}

// src/o_init.c:352 objdescr_is(), does obj's unidentified description
// match descr?
export function objdescr_is(obj, descr) {
    let objdescr;

    if (!obj) {
        /* impossible("objdescr_is: null obj"); */
        return false;
    }
    objdescr = OBJ_DESCR(game.objects[obj.otyp].oc_descr_idx);
    if (!objdescr)
        return false; /* no obj description, no match */
    return objdescr === descr;
}

// src/o_init.c:1210 get_sortdisco(). Invalid stored values reset to default.
export function get_sortdisco(cnf) {
    let i = disco_order_let.indexOf(game.flags.discosort || 'o');
    if (i < 0) {
        game.flags.discosort = 'o';
        i = 0;
    }
    return cnf ? (game.flags.discosort || 'o') : disco_orders_descr[i];
}
