// o_init.js — object initialisation and description shuffling.
// C ref: src/o_init.c
//
// This is the first thing in the game that draws a random number: every
// recorded session's very first PRNG call is
// `rn2(2) @ randomize_gem_colors(o_init.c:89)`. Nothing later in the stream can
// align until this file does.
//
// The object tables come from js/objects_data.js, generated by
// tools/gen-objects.mjs.

import { game } from './gstate.js';
import { rn2 } from './rng.js';
import {
    objects as OBJECTS_INIT, obj_descr as OBJ_DESCR_INIT,
    NUM_OBJECTS, ONAMES, OCLASSES,
} from './objects_data.js';

const {
    ARMOR_CLASS, RING_CLASS, AMULET_CLASS,
    POTION_CLASS, SCROLL_CLASS, SPBOOK_CLASS, WAND_CLASS, GEM_CLASS,
    VENOM_CLASS, MAXOCLASSES,
} = OCLASSES;

const {
    HELMET, HELM_OF_TELEPATHY, LEATHER_GLOVES, GAUNTLETS_OF_DEXTERITY,
    CLOAK_OF_PROTECTION, CLOAK_OF_DISPLACEMENT, SPEED_BOOTS, LEVITATION_BOOTS,
    POT_WATER, WAN_NOTHING, LAST_REAL_GEM,
} = ONAMES;

// include/objclass.h — oc_dir values.
const NODIR = 1, IMMEDIATE = 2;

// The generated table stores oc_class as the C identifier ("WEAPON_CLASS");
// resolve to the numeric class once so the hot paths compare ints as C does.
function numericClass(v) {
    return typeof v === 'string' ? OCLASSES[v] : v;
}

// A fresh, mutable copy of objects[]. shuffle() swaps fields between entries,
// so this is per-game state, never the shared generated table.
export function reset_objects() {
    game.objects = OBJECTS_INIT.map(o => ({ ...o, oc_class: numericClass(o.oc_class) }));
    game.obj_descr = OBJ_DESCR_INIT.map(d => ({ ...d }));
    game.bases = new Array(MAXOCLASSES + 2).fill(0);
    game.oclass_prob_totals = new Array(MAXOCLASSES).fill(0);
    return game.objects;
}

// OBJ_DESCR(obj) from include/objclass.h
function OBJ_DESCR(i) { return game.obj_descr[i].oc_descr; }

// src/o_init.c:54 setgemprobs()
// init_objects() calls this with dlev == 0, so lev is 0 there.
export function setgemprobs(dlev) {
    const objects = game.objects;
    let j, first, lev, sum = 0;

    if (dlev) lev = dlev.ledger_no > dlev.maxledgerno ? dlev.maxledgerno : dlev.ledger_no;
    else lev = 0;
    first = game.bases[GEM_CLASS];

    for (j = 0; j < 9 - Math.trunc(lev / 3); j++)
        objects[first + j].oc_prob = 0;
    first += j;

    for (j = first; j <= LAST_REAL_GEM; j++)
        objects[j].oc_prob = Math.trunc((171 + j - first) / (LAST_REAL_GEM + 1 - first));

    /* recompute GEM_CLASS total oc_prob - including rocks/stones */
    for (j = game.bases[GEM_CLASS]; j < game.bases[GEM_CLASS + 1]; j++)
        sum += objects[j].oc_prob;
    game.oclass_prob_totals[GEM_CLASS] = sum;
}

// src/o_init.c:85 randomize_gem_colors()
// Three draws, and they are the first three of every game.
export function randomize_gem_colors() {
    const objects = game.objects;
    const { TURQUOISE, SAPPHIRE, AQUAMARINE, FLUORITE, DIAMOND, EMERALD } = ONAMES;
    const COPY_OBJ_DESCR = (o_dst, o_src) => {
        objects[o_dst].oc_descr_idx = objects[o_src].oc_descr_idx;
        objects[o_dst].oc_color = objects[o_src].oc_color;
    };

    if (rn2(2)) { /* change turquoise from green to blue? */
        COPY_OBJ_DESCR(TURQUOISE, SAPPHIRE);
    }
    if (rn2(2)) { /* change aquamarine from green to blue? */
        COPY_OBJ_DESCR(AQUAMARINE, SAPPHIRE);
    }
    switch (rn2(4)) { /* change fluorite from violet? */
    case 0:
        break;
    case 1: /* blue */
        COPY_OBJ_DESCR(FLUORITE, SAPPHIRE);
        break;
    case 2: /* white */
        COPY_OBJ_DESCR(FLUORITE, DIAMOND);
        break;
    case 3: /* green */
        COPY_OBJ_DESCR(FLUORITE, EMERALD);
        break;
    }
}

// src/o_init.c:113 shuffle() — shuffle descriptions on objects o_low to o_high.
// This is the bulk of the corpus's o_init draws (10,725 of them). The rejection
// loop matters: every rejected candidate consumes another rn2.
function shuffle(o_low, o_high, domaterial) {
    const objects = game.objects;
    let i, j, num_to_shuffle;
    let sw, color;

    for (num_to_shuffle = 0, j = o_low; j <= o_high; j++)
        if (!objects[j].oc_name_known)
            num_to_shuffle++;
    if (num_to_shuffle < 2)
        return;

    for (j = o_low; j <= o_high; j++) {
        if (objects[j].oc_name_known)
            continue;
        do
            i = j + rn2(o_high - j + 1);
        while (objects[i].oc_name_known);
        sw = objects[j].oc_descr_idx;
        objects[j].oc_descr_idx = objects[i].oc_descr_idx;
        objects[i].oc_descr_idx = sw;
        sw = objects[j].oc_tough;
        objects[j].oc_tough = objects[i].oc_tough;
        objects[i].oc_tough = sw;
        color = objects[j].oc_color;
        objects[j].oc_color = objects[i].oc_color;
        objects[i].oc_color = color;

        /* shuffle material */
        if (domaterial) {
            sw = objects[j].oc_material;
            objects[j].oc_material = objects[i].oc_material;
            objects[i].oc_material = sw;
        }
    }
}

// src/o_init.c:240 init_oclass_probs()
export function init_oclass_probs() {
    const objects = game.objects;
    let i, sum, oclass;

    for (oclass = 0; oclass < MAXOCLASSES; ++oclass) {
        sum = 0;
        /* note: for ILLOBJ_CLASS, bases[oclass+1]-1 isn't the last item
           in the class; but all the generic items have probability 0 so
           adding them to 'sum' has no impact */
        for (i = game.bases[oclass]; i < game.bases[oclass + 1]; ++i) {
            sum += objects[i].oc_prob;
        }
        game.oclass_prob_totals[oclass] = sum;
    }
}

// src/o_init.c:269 obj_shuffle_range() — the range otyp shares descriptions
// with. Returns { lo, hi } instead of writing through out-pointers.
export function obj_shuffle_range(otyp) {
    const objects = game.objects;
    let i;
    const ocls = objects[otyp].oc_class;

    /* default is just the object itself */
    let lo = otyp, hi = otyp;

    switch (ocls) {
    case ARMOR_CLASS:
        if (otyp >= HELMET && otyp <= HELM_OF_TELEPATHY)
            { lo = HELMET; hi = HELM_OF_TELEPATHY; }
        else if (otyp >= LEATHER_GLOVES && otyp <= GAUNTLETS_OF_DEXTERITY)
            { lo = LEATHER_GLOVES; hi = GAUNTLETS_OF_DEXTERITY; }
        else if (otyp >= CLOAK_OF_PROTECTION && otyp <= CLOAK_OF_DISPLACEMENT)
            { lo = CLOAK_OF_PROTECTION; hi = CLOAK_OF_DISPLACEMENT; }
        else if (otyp >= SPEED_BOOTS && otyp <= LEVITATION_BOOTS)
            { lo = SPEED_BOOTS; hi = LEVITATION_BOOTS; }
        break;
    case POTION_CLASS:
        /* potion of water has the only fixed description */
        lo = game.bases[POTION_CLASS];
        hi = POT_WATER - 1;
        break;
    case AMULET_CLASS:
    case SCROLL_CLASS:
    case SPBOOK_CLASS:
        /* exclude non-magic types and also unique ones */
        lo = game.bases[ocls];
        for (i = lo; objects[i].oc_class === ocls; i++)
            if (objects[i].oc_unique || !objects[i].oc_magic)
                break;
        hi = i - 1;
        break;
    case RING_CLASS:
    case WAND_CLASS:
    case VENOM_CLASS:
        /* entire class */
        lo = game.bases[ocls];
        hi = game.bases[ocls + 1] - 1;
        break;
    }

    /* artifact checking might ask about item which isn't part of any range
       but fell within the classes that do have ranges specified above */
    if (otyp < lo || otyp > hi) { lo = otyp; hi = otyp; }
    return { lo, hi };
}

// src/o_init.c:322 shuffle_all() — randomize object descriptions.
function shuffle_all() {
    /* entire classes; obj_shuffle_range() handles their exceptions */
    const shuffle_classes = [
        AMULET_CLASS, POTION_CLASS, RING_CLASS, SCROLL_CLASS,
        SPBOOK_CLASS, WAND_CLASS, VENOM_CLASS,
    ];
    /* sub-class type ranges (one item from each group) */
    const shuffle_types = [
        HELMET, LEATHER_GLOVES, CLOAK_OF_PROTECTION, SPEED_BOOTS,
    ];
    let idx;

    /* do whole classes (amulets, &c) */
    for (idx = 0; idx < shuffle_classes.length; idx++) {
        const { lo, hi } = obj_shuffle_range(game.bases[shuffle_classes[idx]]);
        shuffle(lo, hi, true);
    }
    /* do type ranges (helms, &c) */
    for (idx = 0; idx < shuffle_types.length; idx++) {
        const { lo, hi } = obj_shuffle_range(shuffle_types[idx]);
        shuffle(lo, hi, false);
    }
}

// src/o_init.c:151 init_objects()
export function init_objects() {
    reset_objects();
    const objects = game.objects;
    let i, first, last, prevoclass;
    let oclass;

    for (i = 0; i <= MAXOCLASSES; i++)
        game.bases[i] = 0;

    /* initialize object descriptions */
    for (i = 0; i < NUM_OBJECTS; i++)
        objects[i].oc_name_idx = objects[i].oc_descr_idx = i;

    /* init base; if probs given check that they add up to 1000,
       otherwise compute probs */
    first = MAXOCLASSES;
    prevoclass = -1;
    while (first < NUM_OBJECTS) {
        oclass = objects[first].oc_class;

        last = first + 1;
        while (last < NUM_OBJECTS && objects[last].oc_class === oclass)
            last++;
        game.bases[oclass] = first;

        if (oclass === GEM_CLASS) {
            setgemprobs(null);
            randomize_gem_colors();
        }
        first = last;
        prevoclass = oclass;
    }
    /* extra entry allows deriving the range of a class via
       bases[class] through bases[class+1]-1 for all classes */
    game.bases[MAXOCLASSES] = game.bases[MAXOCLASSES + 1] = NUM_OBJECTS;

    /* guarantee that there are no gaps in bases[] */
    for (last = MAXOCLASSES - 1; last >= 0; --last)
        if (!game.bases[last])
            game.bases[last] = game.bases[last + 1];

    /* check objects[].oc_name_known.
       The C repairs a mismatch silently when sanity_check is off, and the
       repair changes oc_name_known — which changes how many draws shuffle()
       makes. It has to be ported, not skipped. */
    for (i = MAXOCLASSES; i < NUM_OBJECTS; ++i) {
        const nmkn = objects[i].oc_name_known !== 0 ? 1 : 0;

        if (((OBJ_DESCR(i) ? 0 : 1) ^ nmkn) !== 0) {
            /* repair the mistake and keep going */
            objects[i].oc_name_known = nmkn ? 0 : 1;
        }
    }

    /* compute oclass_prob_totals */
    init_oclass_probs();

    /* shuffle descriptions */
    shuffle_all();

    objects[WAN_NOTHING].oc_dir = rn2(2) ? NODIR : IMMEDIATE;
}
