// pager.js — the '?' help menu and its viewers.
// C ref: src/pager.c
//
// dohelp() (pager.c:2861) puts up the help_menu_items list (pager.c:2830)
// as a one-item menu; each entry dispatches a viewer. Only the About entry
// (hmenu_doextversion) is live — it is the one the sessions open — and the
// rest record with their letters when picked.
//
// doextversion() (src/version.c:169) composes the About window: the dynamic
// version line, then the build's option summary via do_runtime_info()
// (src/mdlib.c) with :PATMATCH:/:LUACOPYRIGHT: substituted (version.c:327).
// Blank lines are skipped and a separator precedes each outdented header
// (version.c:256). The Lua copyright substitution needs a Lua state, and
// creating one runs dat/nhlib.lua's file-scope shuffle(align) — the rn2(3),
// rn2(2) pair every Lua load costs (js/nhlua.js nhl_init). The text below
// is the reference build's output verbatim (recorder dat/options plus the
// runtime soundlib section), substitutions applied.

import { game } from './gstate.js';
import { nhl_init } from './nhlua.js';
import { tty_create_nhwindow, tty_putstr, tty_display_nhwindow,
         tty_next_page, tty_destroy_nhwindow, tty_start_menu, tty_add_menu,
         tty_end_menu, NHW_TEXT, NHW_MENU, ATR_NONE } from './tty/wintty.js';
import { MENU_ITEMFLAGS_NONE, MENU_BEHAVE_STANDARD, ECMD_OK } from './const.js';
import { NO_COLOR } from './terminal.js';
import { nhgetch } from './input.js';
import { docrt } from './display.js';

function note_unported_pager(what) {
    (game.unported ||= new Set()).add('pager:' + what);
}

const ABOUT_VERSION_LINE =
    'MacOS NetHack Version 5.0.0 - last build May  2 2026 12:00:00.';
const ABOUT_RUNTIME_INFO = [
    '',
    'Options compiled into this edition:',
    '    I32LP64 data model, color, data file compression, deferred handling of',
    '    hangup signal, insurance files for recovering from crashes, live logging',
    '    support, log file, extended log file, errors and warnings log file, mail',
    '    daemon, news file, internal pager used for viewing help files, pattern',
    '    matching via posixregex, pseudo random numbers generated by ISAAC64,',
    '    strong PRNG seed from /dev/random, restore saved games via menu, screen',
    '    clipping, shell command, traditional status display, status via',
    '    windowport with highlighting, suspend command, terminal info library,',
    '    system configuration at run-time, show stack trace on error, launch',
    '    browser to report issues, save and bones files accepted from version',
    '    5.0.0 only, and basic NetHack features.',
    '',
    'Supported windowing system:',
    '    "tty" (traditional text with optional line-drawing).',
    '',
    'Supported soundlib:',
    '    "nosound".',
    '',
    "NetHack 5.0.* uses the 'Lua' interpreter to process some data:",
    '    Lua 5.4.8  Copyright (C) 1994-2025 Lua.org, PUC-Rio',
    '    "Permission is hereby granted, free of charge, to any person obtaining',
    '     a copy of this software and associated documentation files (the',
    '     "Software"), to deal in the Software without restriction including',
    '     without limitation the rights to use, copy, modify, merge, publish,',
    '     distribute, sublicense, and/or sell copies of the Software, and to',
    '     permit persons to whom the Software is furnished to do so, subject to',
    '     the following conditions:',
    '     The above copyright notice and this permission notice shall be',
    '     included in all copies or substantial portions of the Software."',
];

// src/version.c:169 doextversion()
export async function doextversion() {
    /* get_lua_version() creates a Lua state; the nhlib align shuffle is
       its observable cost */
    nhl_init();

    const win = tty_create_nhwindow(NHW_TEXT);
    tty_putstr(win, 0, ABOUT_VERSION_LINE);
    for (const line of ABOUT_RUNTIME_INFO)
        tty_putstr(win, 0, line);
    tty_display_nhwindow(win);
    await nhgetch();
    while (tty_next_page(win))
        await nhgetch();
    tty_destroy_nhwindow(win);
    await docrt();
    return ECMD_OK;
}

/* src/pager.c:2830 help_menu_items[] — texts exactly as the reference
   displays them ('i' carries the "'#optionsfull' or 'm O'" substitution). */
const HELP_MENU_ITEMS = [
    'About NetHack (version information).',
    'Long description of the game and commands.',
    'List of game commands.',
    'Concise history of NetHack.',
    'Info on a character in the game display.',
    'Info on what a given key does.',
    'List of game options.',
    'Longer explanation of game options.',
    "Using the '#optionsfull' or 'm O' command to set options.",
    'Full list of keyboard commands.',
    'List of extended commands.',
    'List menu control keys.',
    "Description of NetHack's command line.",
    'The NetHack license.',
    'Support information.',
];

// src/pager.c:2861 dohelp() — the '?' command.
export async function dohelp() {
    const win = tty_create_nhwindow(NHW_MENU);
    tty_start_menu(win, MENU_BEHAVE_STANDARD);
    HELP_MENU_ITEMS.forEach((text, i) => {
        tty_add_menu(win, null, String.fromCharCode(97 + i), 0, 0, ATR_NONE,
                     NO_COLOR, text, MENU_ITEMFLAGS_NONE);
    });
    tty_end_menu(win, 'Select one item:');
    tty_display_nhwindow(win);

    const key = await nhgetch();
    tty_destroy_nhwindow(win);
    await docrt();

    const ch = String.fromCharCode(key);
    if (ch === 'a') {
        return await doextversion();
    } else if (ch >= 'b' && ch <= 'o') {
        note_unported_pager(`dohelp:item_${ch}`);
        return ECMD_OK;
    }
    /* ESC/space — menu dismissed with no pick */
    return ECMD_OK;
}
