// role_data.js — GENERATED by tools/gen-roledata.mjs from
// nethack-c/upstream/src/role.c. Do not edit by hand; re-run the generator.
//
// Field names come from the struct definitions in include/you.h (struct Role at
// you.h:183). Leaf values are the raw C expressions — "PM_ARCHEOLOGIST",
// "MH_HUMAN | MH_DWARF | ROLE_LAWFUL", -4 — because resolving constants is
// js/const.js's job, not this table's.
//
// 13 roles, 5 races, 4 genders, 4 alignments.

export const roles = [
    {
        "name": {
            "m": "Archeologist",
            "f": null
        },
        "rank": [
            {
                "m": "Digger",
                "f": null
            },
            {
                "m": "Field Worker",
                "f": null
            },
            {
                "m": "Investigator",
                "f": null
            },
            {
                "m": "Exhumer",
                "f": null
            },
            {
                "m": "Excavator",
                "f": null
            },
            {
                "m": "Spelunker",
                "f": null
            },
            {
                "m": "Speleologist",
                "f": null
            },
            {
                "m": "Collector",
                "f": null
            },
            {
                "m": "Curator",
                "f": null
            }
        ],
        "lgod": "Quetzalcoatl",
        "ngod": "Camaxtli",
        "cgod": "Huhetotl",
        "filecode": "Arc",
        "homebase": "the College of Archeology",
        "intermed": "the Tomb of the Toltec Kings",
        "mnum": "PM_ARCHEOLOGIST",
        "petnum": "NON_PM",
        "ldrnum": "PM_LORD_CARNARVON",
        "guardnum": "PM_STUDENT",
        "neminum": "PM_MINION_OF_HUHETOTL",
        "enemy1num": "NON_PM",
        "enemy2num": "PM_HUMAN_MUMMY",
        "enemy1sym": "S_SNAKE",
        "enemy2sym": "S_MUMMY",
        "questarti": "ART_ORB_OF_DETECTION",
        "allow": "MH_HUMAN | MH_DWARF | MH_GNOME | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL | ROLE_NEUTRAL",
        "attrbase": [
            7,
            10,
            10,
            7,
            7,
            7
        ],
        "attrdist": [
            20,
            20,
            20,
            10,
            20,
            10
        ],
        "hpadv": [
            11,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 14,
        "initrecord": 10,
        "spelbase": 5,
        "spelheal": 0,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": "A_INT",
        "spelspec": "SPE_MAGIC_MAPPING",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Barbarian",
            "f": null
        },
        "rank": [
            {
                "m": "Plunderer",
                "f": "Plunderess"
            },
            {
                "m": "Pillager",
                "f": null
            },
            {
                "m": "Bandit",
                "f": null
            },
            {
                "m": "Brigand",
                "f": null
            },
            {
                "m": "Raider",
                "f": null
            },
            {
                "m": "Reaver",
                "f": null
            },
            {
                "m": "Slayer",
                "f": null
            },
            {
                "m": "Chieftain",
                "f": "Chieftainess"
            },
            {
                "m": "Conqueror",
                "f": "Conqueress"
            }
        ],
        "lgod": "Mitra",
        "ngod": "Crom",
        "cgod": "Set",
        "filecode": "Bar",
        "homebase": "the Camp of the Duali Tribe",
        "intermed": "the Duali Oasis",
        "mnum": "PM_BARBARIAN",
        "petnum": "NON_PM",
        "ldrnum": "PM_PELIAS",
        "guardnum": "PM_CHIEFTAIN",
        "neminum": "PM_THOTH_AMON",
        "enemy1num": "PM_OGRE",
        "enemy2num": "PM_TROLL",
        "enemy1sym": "S_OGRE",
        "enemy2sym": "S_TROLL",
        "questarti": "ART_HEART_OF_AHRIMAN",
        "allow": "MH_HUMAN | MH_ORC | ROLE_MALE | ROLE_FEMALE | ROLE_NEUTRAL | ROLE_CHAOTIC",
        "attrbase": [
            16,
            7,
            7,
            15,
            16,
            6
        ],
        "attrdist": [
            30,
            6,
            7,
            20,
            30,
            7
        ],
        "hpadv": [
            14,
            0,
            0,
            10,
            2,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 10,
        "initrecord": 10,
        "spelbase": 14,
        "spelheal": 0,
        "spelshld": 0,
        "spelarmr": 8,
        "spelstat": "A_INT",
        "spelspec": "SPE_HASTE_SELF",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Caveman",
            "f": "Cavewoman"
        },
        "rank": [
            {
                "m": "Troglodyte",
                "f": null
            },
            {
                "m": "Aborigine",
                "f": null
            },
            {
                "m": "Wanderer",
                "f": null
            },
            {
                "m": "Vagrant",
                "f": null
            },
            {
                "m": "Wayfarer",
                "f": null
            },
            {
                "m": "Roamer",
                "f": null
            },
            {
                "m": "Nomad",
                "f": null
            },
            {
                "m": "Rover",
                "f": null
            },
            {
                "m": "Pioneer",
                "f": null
            }
        ],
        "lgod": "Anu",
        "ngod": "_Ishtar",
        "cgod": "Anshar",
        "filecode": "Cav",
        "homebase": "the Caves of the Ancestors",
        "intermed": "the Dragon's Lair",
        "mnum": "PM_CAVE_DWELLER",
        "petnum": "PM_LITTLE_DOG",
        "ldrnum": "PM_SHAMAN_KARNOV",
        "guardnum": "PM_NEANDERTHAL",
        "neminum": "PM_CHROMATIC_DRAGON",
        "enemy1num": "PM_BUGBEAR",
        "enemy2num": "PM_HILL_GIANT",
        "enemy1sym": "S_HUMANOID",
        "enemy2sym": "S_GIANT",
        "questarti": "ART_SCEPTRE_OF_MIGHT",
        "allow": "MH_HUMAN | MH_DWARF | MH_GNOME | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL | ROLE_NEUTRAL",
        "attrbase": [
            10,
            7,
            7,
            7,
            8,
            6
        ],
        "attrdist": [
            30,
            6,
            7,
            20,
            30,
            7
        ],
        "hpadv": [
            14,
            0,
            0,
            8,
            2,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 10,
        "initrecord": 0,
        "spelbase": 12,
        "spelheal": 0,
        "spelshld": 1,
        "spelarmr": 8,
        "spelstat": "A_INT",
        "spelspec": "SPE_DIG",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Healer",
            "f": null
        },
        "rank": [
            {
                "m": "Rhizotomist",
                "f": null
            },
            {
                "m": "Empiric",
                "f": null
            },
            {
                "m": "Embalmer",
                "f": null
            },
            {
                "m": "Dresser",
                "f": null
            },
            {
                "m": "Medicus ossium",
                "f": "Medica ossium"
            },
            {
                "m": "Herbalist",
                "f": null
            },
            {
                "m": "Magister",
                "f": "Magistra"
            },
            {
                "m": "Physician",
                "f": null
            },
            {
                "m": "Chirurgeon",
                "f": null
            }
        ],
        "lgod": "_Athena",
        "ngod": "Hermes",
        "cgod": "Poseidon",
        "filecode": "Hea",
        "homebase": "the Temple of Epidaurus",
        "intermed": "the Temple of Coeus",
        "mnum": "PM_HEALER",
        "petnum": "NON_PM",
        "ldrnum": "PM_HIPPOCRATES",
        "guardnum": "PM_ATTENDANT",
        "neminum": "PM_CYCLOPS",
        "enemy1num": "PM_GIANT_RAT",
        "enemy2num": "PM_SNAKE",
        "enemy1sym": "S_RODENT",
        "enemy2sym": "S_YETI",
        "questarti": "ART_STAFF_OF_AESCULAPIUS",
        "allow": "MH_HUMAN | MH_GNOME | ROLE_MALE | ROLE_FEMALE | ROLE_NEUTRAL",
        "attrbase": [
            7,
            7,
            13,
            7,
            11,
            16
        ],
        "attrdist": [
            15,
            20,
            20,
            15,
            25,
            5
        ],
        "hpadv": [
            11,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            4,
            0,
            1,
            0,
            2
        ],
        "xlev": 20,
        "initrecord": 10,
        "spelbase": 3,
        "spelheal": -3,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": "A_WIS",
        "spelspec": "SPE_CURE_SICKNESS",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Knight",
            "f": null
        },
        "rank": [
            {
                "m": "Gallant",
                "f": null
            },
            {
                "m": "Esquire",
                "f": null
            },
            {
                "m": "Bachelor",
                "f": null
            },
            {
                "m": "Sergeant",
                "f": null
            },
            {
                "m": "Knight",
                "f": null
            },
            {
                "m": "Banneret",
                "f": null
            },
            {
                "m": "Chevalier",
                "f": "Chevaliere"
            },
            {
                "m": "Seignieur",
                "f": "Dame"
            },
            {
                "m": "Paladin",
                "f": null
            }
        ],
        "lgod": "Lugh",
        "ngod": "_Brigit",
        "cgod": "Manannan Mac Lir",
        "filecode": "Kni",
        "homebase": "Camelot Castle",
        "intermed": "the Isle of Glass",
        "mnum": "PM_KNIGHT",
        "petnum": "PM_PONY",
        "ldrnum": "PM_KING_ARTHUR",
        "guardnum": "PM_PAGE",
        "neminum": "PM_IXOTH",
        "enemy1num": "PM_QUASIT",
        "enemy2num": "PM_OCHRE_JELLY",
        "enemy1sym": "S_IMP",
        "enemy2sym": "S_JELLY",
        "questarti": "ART_MAGIC_MIRROR_OF_MERLIN",
        "allow": "MH_HUMAN | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL",
        "attrbase": [
            13,
            7,
            14,
            8,
            10,
            17
        ],
        "attrdist": [
            30,
            15,
            15,
            10,
            20,
            10
        ],
        "hpadv": [
            14,
            0,
            0,
            8,
            2,
            0
        ],
        "enadv": [
            1,
            4,
            0,
            1,
            0,
            2
        ],
        "xlev": 10,
        "initrecord": 10,
        "spelbase": 8,
        "spelheal": -2,
        "spelshld": 0,
        "spelarmr": 9,
        "spelstat": "A_WIS",
        "spelspec": "SPE_TURN_UNDEAD",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Monk",
            "f": null
        },
        "rank": [
            {
                "m": "Candidate",
                "f": null
            },
            {
                "m": "Novice",
                "f": null
            },
            {
                "m": "Initiate",
                "f": null
            },
            {
                "m": "Student of Stones",
                "f": null
            },
            {
                "m": "Student of Waters",
                "f": null
            },
            {
                "m": "Student of Metals",
                "f": null
            },
            {
                "m": "Student of Winds",
                "f": null
            },
            {
                "m": "Student of Fire",
                "f": null
            },
            {
                "m": "Master",
                "f": null
            }
        ],
        "lgod": "Shan Lai Ching",
        "ngod": "Chih Sung-tzu",
        "cgod": "Huan Ti",
        "filecode": "Mon",
        "homebase": "the Monastery of Chan-Sune",
        "intermed": "the Monastery of the Earth-Lord",
        "mnum": "PM_MONK",
        "petnum": "NON_PM",
        "ldrnum": "PM_GRAND_MASTER",
        "guardnum": "PM_ABBOT",
        "neminum": "PM_MASTER_KAEN",
        "enemy1num": "PM_EARTH_ELEMENTAL",
        "enemy2num": "PM_XORN",
        "enemy1sym": "S_ELEMENTAL",
        "enemy2sym": "S_XORN",
        "questarti": "ART_EYES_OF_THE_OVERWORLD",
        "allow": "MH_HUMAN | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL | ROLE_NEUTRAL | ROLE_CHAOTIC",
        "attrbase": [
            10,
            7,
            8,
            8,
            7,
            7
        ],
        "attrdist": [
            25,
            10,
            20,
            20,
            15,
            10
        ],
        "hpadv": [
            12,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            2,
            2,
            0,
            2,
            0,
            2
        ],
        "xlev": 10,
        "initrecord": 10,
        "spelbase": 8,
        "spelheal": -2,
        "spelshld": 2,
        "spelarmr": 20,
        "spelstat": "A_WIS",
        "spelspec": "SPE_RESTORE_ABILITY",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Priest",
            "f": "Priestess"
        },
        "rank": [
            {
                "m": "Aspirant",
                "f": null
            },
            {
                "m": "Acolyte",
                "f": null
            },
            {
                "m": "Adept",
                "f": null
            },
            {
                "m": "Priest",
                "f": "Priestess"
            },
            {
                "m": "Curate",
                "f": null
            },
            {
                "m": "Canon",
                "f": "Canoness"
            },
            {
                "m": "Lama",
                "f": null
            },
            {
                "m": "Patriarch",
                "f": "Matriarch"
            },
            {
                "m": "High Priest",
                "f": "High Priestess"
            }
        ],
        "lgod": 0,
        "ngod": 0,
        "cgod": 0,
        "filecode": "Pri",
        "homebase": "the Great Temple",
        "intermed": "the Temple of Nalzok",
        "mnum": "PM_CLERIC",
        "petnum": "NON_PM",
        "ldrnum": "PM_ARCH_PRIEST",
        "guardnum": "PM_ACOLYTE",
        "neminum": "PM_NALZOK",
        "enemy1num": "PM_HUMAN_ZOMBIE",
        "enemy2num": "PM_WRAITH",
        "enemy1sym": "S_ZOMBIE",
        "enemy2sym": "S_WRAITH",
        "questarti": "ART_MITRE_OF_HOLINESS",
        "allow": "MH_HUMAN | MH_ELF | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL | ROLE_NEUTRAL | ROLE_CHAOTIC",
        "attrbase": [
            7,
            7,
            10,
            7,
            7,
            7
        ],
        "attrdist": [
            15,
            10,
            30,
            15,
            20,
            10
        ],
        "hpadv": [
            12,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            4,
            3,
            0,
            2,
            0,
            2
        ],
        "xlev": 10,
        "initrecord": 0,
        "spelbase": 3,
        "spelheal": -2,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": "A_WIS",
        "spelspec": "SPE_REMOVE_CURSE",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Rogue",
            "f": null
        },
        "rank": [
            {
                "m": "Footpad",
                "f": null
            },
            {
                "m": "Cutpurse",
                "f": null
            },
            {
                "m": "Rogue",
                "f": null
            },
            {
                "m": "Pilferer",
                "f": null
            },
            {
                "m": "Robber",
                "f": null
            },
            {
                "m": "Burglar",
                "f": null
            },
            {
                "m": "Filcher",
                "f": null
            },
            {
                "m": "Magsman",
                "f": "Magswoman"
            },
            {
                "m": "Thief",
                "f": null
            }
        ],
        "lgod": "Issek",
        "ngod": "Mog",
        "cgod": "Kos",
        "filecode": "Rog",
        "homebase": "the Thieves' Guild Hall",
        "intermed": "the Assassins' Guild Hall",
        "mnum": "PM_ROGUE",
        "petnum": "NON_PM",
        "ldrnum": "PM_MASTER_OF_THIEVES",
        "guardnum": "PM_THUG",
        "neminum": "PM_MASTER_ASSASSIN",
        "enemy1num": "PM_LEPRECHAUN",
        "enemy2num": "PM_GUARDIAN_NAGA",
        "enemy1sym": "S_NYMPH",
        "enemy2sym": "S_NAGA",
        "questarti": "ART_MASTER_KEY_OF_THIEVERY",
        "allow": "MH_HUMAN | MH_ORC | ROLE_MALE | ROLE_FEMALE | ROLE_CHAOTIC",
        "attrbase": [
            7,
            7,
            7,
            10,
            7,
            6
        ],
        "attrdist": [
            20,
            10,
            10,
            30,
            20,
            10
        ],
        "hpadv": [
            10,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 11,
        "initrecord": 10,
        "spelbase": 8,
        "spelheal": 0,
        "spelshld": 1,
        "spelarmr": 9,
        "spelstat": "A_INT",
        "spelspec": "SPE_DETECT_TREASURE",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Ranger",
            "f": null
        },
        "rank": [
            {
                "m": "Edhel",
                "f": "Elleth"
            },
            {
                "m": "Edhel",
                "f": "Elleth"
            },
            {
                "m": "Ohtar",
                "f": "Ohtie"
            },
            {
                "m": "Kano",
                "f": "Kanie"
            },
            {
                "m": "Arandur",
                "f": " Aranduriel"
            },
            {
                "m": "Hir",
                "f": "Hiril"
            },
            {
                "m": "Aredhel",
                "f": "Arwen"
            },
            {
                "m": "Ernil",
                "f": "Elentariel"
            },
            {
                "m": "Elentar",
                "f": "Elentari"
            },
            {
                "m": "Solonor Thelandira",
                "f": null
            },
            {
                "m": "Aerdrie Faenya",
                "f": null
            },
            {
                "m": "Lolth",
                "f": null
            },
            {
                "m": "Tenderfoot",
                "f": null
            },
            {
                "m": "Lookout",
                "f": null
            },
            {
                "m": "Trailblazer",
                "f": null
            },
            {
                "m": "Reconnoiterer",
                "f": "Reconnoiteress"
            },
            {
                "m": "Scout",
                "f": null
            },
            {
                "m": "Arbalester",
                "f": null
            },
            {
                "m": "Archer",
                "f": null
            },
            {
                "m": "Sharpshooter",
                "f": null
            },
            {
                "m": "Marksman",
                "f": "Markswoman"
            }
        ],
        "lgod": "Mercury",
        "ngod": "_Venus",
        "cgod": "Mars",
        "filecode": "Ran",
        "homebase": "Orion's camp",
        "intermed": "the cave of the wumpus",
        "mnum": "PM_RANGER",
        "petnum": "PM_LITTLE_DOG",
        "ldrnum": "PM_ORION",
        "guardnum": "PM_HUNTER",
        "neminum": "PM_SCORPIUS",
        "enemy1num": "PM_FOREST_CENTAUR",
        "enemy2num": "PM_SCORPION",
        "enemy1sym": "S_CENTAUR",
        "enemy2sym": "S_SPIDER",
        "questarti": "ART_LONGBOW_OF_DIANA",
        "allow": "MH_HUMAN | MH_ELF | MH_GNOME | MH_ORC | ROLE_MALE | ROLE_FEMALE | ROLE_NEUTRAL | ROLE_CHAOTIC",
        "attrbase": [
            13,
            13,
            13,
            9,
            13,
            7
        ],
        "attrdist": [
            30,
            10,
            10,
            20,
            20,
            10
        ],
        "hpadv": [
            13,
            0,
            0,
            6,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 12,
        "initrecord": 10,
        "spelbase": 9,
        "spelheal": 2,
        "spelshld": 1,
        "spelarmr": 10,
        "spelstat": "A_INT",
        "spelspec": "SPE_INVISIBILITY",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Samurai",
            "f": null
        },
        "rank": [
            {
                "m": "Hatamoto",
                "f": null
            },
            {
                "m": "Ronin",
                "f": null
            },
            {
                "m": "Ninja",
                "f": "Kunoichi"
            },
            {
                "m": "Joshu",
                "f": null
            },
            {
                "m": "Ryoshu",
                "f": null
            },
            {
                "m": "Kokushu",
                "f": null
            },
            {
                "m": "Daimyo",
                "f": null
            },
            {
                "m": "Kuge",
                "f": null
            },
            {
                "m": "Shogun",
                "f": null
            }
        ],
        "lgod": "_Amaterasu Omikami",
        "ngod": "Raijin",
        "cgod": "Susanowo",
        "filecode": "Sam",
        "homebase": "the Castle of the Taro Clan",
        "intermed": "the Shogun's Castle",
        "mnum": "PM_SAMURAI",
        "petnum": "PM_LITTLE_DOG",
        "ldrnum": "PM_LORD_SATO",
        "guardnum": "PM_ROSHI",
        "neminum": "PM_ASHIKAGA_TAKAUJI",
        "enemy1num": "PM_WOLF",
        "enemy2num": "PM_STALKER",
        "enemy1sym": "S_DOG",
        "enemy2sym": "S_ELEMENTAL",
        "questarti": "ART_TSURUGI_OF_MURAMASA",
        "allow": "MH_HUMAN | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL",
        "attrbase": [
            10,
            8,
            7,
            10,
            17,
            6
        ],
        "attrdist": [
            30,
            10,
            8,
            30,
            14,
            8
        ],
        "hpadv": [
            13,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 11,
        "initrecord": 10,
        "spelbase": 10,
        "spelheal": 0,
        "spelshld": 0,
        "spelarmr": 8,
        "spelstat": "A_INT",
        "spelspec": "SPE_CLAIRVOYANCE",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Tourist",
            "f": null
        },
        "rank": [
            {
                "m": "Rambler",
                "f": null
            },
            {
                "m": "Sightseer",
                "f": null
            },
            {
                "m": "Excursionist",
                "f": null
            },
            {
                "m": "Peregrinator",
                "f": "Peregrinatrix"
            },
            {
                "m": "Traveler",
                "f": null
            },
            {
                "m": "Journeyer",
                "f": null
            },
            {
                "m": "Voyager",
                "f": null
            },
            {
                "m": "Explorer",
                "f": null
            },
            {
                "m": "Adventurer",
                "f": null
            }
        ],
        "lgod": "Blind Io",
        "ngod": "_The Lady",
        "cgod": "Offler",
        "filecode": "Tou",
        "homebase": "Ankh-Morpork",
        "intermed": "the Thieves' Guild Hall",
        "mnum": "PM_TOURIST",
        "petnum": "NON_PM",
        "ldrnum": "PM_TWOFLOWER",
        "guardnum": "PM_GUIDE",
        "neminum": "PM_MASTER_OF_THIEVES",
        "enemy1num": "PM_GIANT_SPIDER",
        "enemy2num": "PM_FOREST_CENTAUR",
        "enemy1sym": "S_SPIDER",
        "enemy2sym": "S_CENTAUR",
        "questarti": "ART_YENDORIAN_EXPRESS_CARD",
        "allow": "MH_HUMAN | ROLE_MALE | ROLE_FEMALE | ROLE_NEUTRAL",
        "attrbase": [
            7,
            10,
            6,
            7,
            7,
            10
        ],
        "attrdist": [
            15,
            10,
            10,
            15,
            30,
            20
        ],
        "hpadv": [
            8,
            0,
            0,
            8,
            0,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 14,
        "initrecord": 0,
        "spelbase": 5,
        "spelheal": 1,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": "A_INT",
        "spelspec": "SPE_CHARM_MONSTER",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Valkyrie",
            "f": null
        },
        "rank": [
            {
                "m": "Stripling",
                "f": null
            },
            {
                "m": "Skirmisher",
                "f": null
            },
            {
                "m": "Fighter",
                "f": null
            },
            {
                "m": "Man-at-arms",
                "f": "Woman-at-arms"
            },
            {
                "m": "Warrior",
                "f": null
            },
            {
                "m": "Swashbuckler",
                "f": null
            },
            {
                "m": "Hero",
                "f": "Heroine"
            },
            {
                "m": "Champion",
                "f": null
            },
            {
                "m": "Lord",
                "f": "Lady"
            }
        ],
        "lgod": "Tyr",
        "ngod": "Odin",
        "cgod": "Loki",
        "filecode": "Val",
        "homebase": "the Shrine of Destiny",
        "intermed": "the cave of Surtur",
        "mnum": "PM_VALKYRIE",
        "petnum": "NON_PM",
        "ldrnum": "PM_NORN",
        "guardnum": "PM_WARRIOR",
        "neminum": "PM_LORD_SURTUR",
        "enemy1num": "PM_FIRE_ANT",
        "enemy2num": "PM_FIRE_GIANT",
        "enemy1sym": "S_ANT",
        "enemy2sym": "S_GIANT",
        "questarti": "ART_ORB_OF_FATE",
        "allow": "MH_HUMAN | MH_DWARF | ROLE_FEMALE | ROLE_LAWFUL | ROLE_NEUTRAL",
        "attrbase": [
            10,
            7,
            7,
            7,
            10,
            7
        ],
        "attrdist": [
            30,
            6,
            7,
            20,
            30,
            7
        ],
        "hpadv": [
            14,
            0,
            0,
            8,
            2,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 10,
        "initrecord": 0,
        "spelbase": 10,
        "spelheal": -2,
        "spelshld": 0,
        "spelarmr": 9,
        "spelstat": "A_WIS",
        "spelspec": "SPE_CONE_OF_COLD",
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Wizard",
            "f": null
        },
        "rank": [
            {
                "m": "Evoker",
                "f": null
            },
            {
                "m": "Conjurer",
                "f": null
            },
            {
                "m": "Thaumaturge",
                "f": null
            },
            {
                "m": "Magician",
                "f": null
            },
            {
                "m": "Enchanter",
                "f": "Enchantress"
            },
            {
                "m": "Sorcerer",
                "f": "Sorceress"
            },
            {
                "m": "Necromancer",
                "f": null
            },
            {
                "m": "Wizard",
                "f": null
            },
            {
                "m": "Mage",
                "f": null
            }
        ],
        "lgod": "Ptah",
        "ngod": "Thoth",
        "cgod": "Anhur",
        "filecode": "Wiz",
        "homebase": "the Lonely Tower",
        "intermed": "the Tower of Darkness",
        "mnum": "PM_WIZARD",
        "petnum": "PM_KITTEN",
        "ldrnum": "PM_NEFERET_THE_GREEN",
        "guardnum": "PM_APPRENTICE",
        "neminum": "PM_DARK_ONE",
        "enemy1num": "PM_VAMPIRE_BAT",
        "enemy2num": "PM_XORN",
        "enemy1sym": "S_BAT",
        "enemy2sym": "S_WRAITH",
        "questarti": "ART_EYE_OF_THE_AETHIOPICA",
        "allow": "MH_HUMAN | MH_ELF | MH_GNOME | MH_ORC | ROLE_MALE | ROLE_FEMALE | ROLE_NEUTRAL | ROLE_CHAOTIC",
        "attrbase": [
            7,
            10,
            7,
            7,
            7,
            7
        ],
        "attrdist": [
            10,
            30,
            10,
            20,
            20,
            10
        ],
        "hpadv": [
            10,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            4,
            3,
            0,
            2,
            0,
            3
        ],
        "xlev": 12,
        "initrecord": 0,
        "spelbase": 1,
        "spelheal": 0,
        "spelshld": 3,
        "spelarmr": 10,
        "spelstat": "A_INT",
        "spelspec": "SPE_MAGIC_MISSILE",
        "spelsbon": -4
    }
];

export const races = [
    [
        "human",
        "human",
        "humanity",
        "Hum",
        [
            "man",
            "woman"
        ],
        "PM_HUMAN",
        "PM_HUMAN_MUMMY",
        "PM_HUMAN_ZOMBIE",
        "MH_HUMAN | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL | ROLE_NEUTRAL | ROLE_CHAOTIC",
        "MH_HUMAN",
        0,
        "MH_GNOME | MH_ORC",
        [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        [
            "STR18(100)",
            18,
            18,
            18,
            18,
            18
        ],
        [
            2,
            0,
            0,
            2,
            1,
            0
        ],
        [
            1,
            0,
            2,
            0,
            2,
            0
        ]
    ],
    [
        "elf",
        "elven",
        "elvenkind",
        "Elf",
        [
            0,
            0
        ],
        "PM_ELF",
        "PM_ELF_MUMMY",
        "PM_ELF_ZOMBIE",
        "MH_ELF | ROLE_MALE | ROLE_FEMALE | ROLE_CHAOTIC",
        "MH_ELF",
        "MH_ELF",
        "MH_ORC",
        [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        [
            18,
            20,
            20,
            18,
            16,
            18
        ],
        [
            1,
            0,
            0,
            1,
            1,
            0
        ],
        [
            2,
            0,
            3,
            0,
            3,
            0
        ]
    ],
    [
        "dwarf",
        "dwarven",
        "dwarvenkind",
        "Dwa",
        [
            0,
            0
        ],
        "PM_DWARF",
        "PM_DWARF_MUMMY",
        "PM_DWARF_ZOMBIE",
        "MH_DWARF | ROLE_MALE | ROLE_FEMALE | ROLE_LAWFUL",
        "MH_DWARF",
        "MH_DWARF | MH_GNOME",
        "MH_ORC",
        [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        [
            "STR18(100)",
            16,
            16,
            20,
            20,
            16
        ],
        [
            4,
            0,
            0,
            3,
            2,
            0
        ],
        [
            0,
            0,
            0,
            0,
            0,
            0
        ]
    ],
    [
        "gnome",
        "gnomish",
        "gnomehood",
        "Gno",
        [
            0,
            0
        ],
        "PM_GNOME",
        "PM_GNOME_MUMMY",
        "PM_GNOME_ZOMBIE",
        "MH_GNOME | ROLE_MALE | ROLE_FEMALE | ROLE_NEUTRAL",
        "MH_GNOME",
        "MH_DWARF | MH_GNOME",
        "MH_HUMAN",
        [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        [
            "STR18(50)",
            19,
            18,
            18,
            18,
            18
        ],
        [
            1,
            0,
            0,
            1,
            0,
            0
        ],
        [
            2,
            0,
            2,
            0,
            2,
            0
        ]
    ],
    [
        "orc",
        "orcish",
        "orcdom",
        "Orc",
        [
            0,
            0
        ],
        "PM_ORC",
        "PM_ORC_MUMMY",
        "PM_ORC_ZOMBIE",
        "MH_ORC | ROLE_MALE | ROLE_FEMALE | ROLE_CHAOTIC",
        "MH_ORC",
        0,
        "MH_HUMAN | MH_ELF | MH_DWARF",
        [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        [
            "STR18(50)",
            16,
            16,
            18,
            18,
            16
        ],
        [
            1,
            0,
            0,
            1,
            0,
            0
        ],
        [
            1,
            0,
            1,
            0,
            1,
            0
        ]
    ]
];

export const genders = [
    [
        "male",
        "he",
        "him",
        "his",
        "Mal",
        "ROLE_MALE"
    ],
    [
        "female",
        "she",
        "her",
        "her",
        "Fem",
        "ROLE_FEMALE"
    ],
    [
        "neuter",
        "it",
        "it",
        "its",
        "Ntr",
        "ROLE_NEUTER"
    ],
    [
        "group",
        "they",
        "them",
        "their",
        "Grp",
        0
    ]
];

export const aligns = [
    [
        "law",
        "lawful",
        "Law",
        "ROLE_LAWFUL",
        "A_LAWFUL"
    ],
    [
        "balance",
        "neutral",
        "Neu",
        "ROLE_NEUTRAL",
        "A_NEUTRAL"
    ],
    [
        "chaos",
        "chaotic",
        "Cha",
        "ROLE_CHAOTIC",
        "A_CHAOTIC"
    ],
    [
        "evil",
        "unaligned",
        "Una",
        0,
        "A_NONE"
    ]
];

// src/role.c str2role() matches on the role name, case-insensitively.
export function findRole(name) {
    const n = String(name).toLowerCase();
    return roles.find(r => r.name.m.toLowerCase() === n
                        || (r.name.f && r.name.f.toLowerCase() === n)) || null;
}
