// role_data.js — GENERATED by tools/gen-roledata.mjs from
// nethack-c/upstream/src/role.c. Do not edit by hand; re-run the generator.
//
// Field names come from the struct definitions in include/you.h (struct Role at
// you.h:183). Leaf values are the raw C expressions — "PM_ARCHEOLOGIST",
// "MH_HUMAN | MH_DWARF | ROLE_LAWFUL", -4 — because resolving constants is
// js/const.js's job, not this table's.
//
// 13 roles, 5 races, 4 genders, 4 alignments.

export const roles = [
    {
        "name": {
            "m": "Archeologist",
            "f": null
        },
        "rank": [
            {
                "m": "Digger",
                "f": null
            },
            {
                "m": "Field Worker",
                "f": null
            },
            {
                "m": "Investigator",
                "f": null
            },
            {
                "m": "Exhumer",
                "f": null
            },
            {
                "m": "Excavator",
                "f": null
            },
            {
                "m": "Spelunker",
                "f": null
            },
            {
                "m": "Speleologist",
                "f": null
            },
            {
                "m": "Collector",
                "f": null
            },
            {
                "m": "Curator",
                "f": null
            }
        ],
        "lgod": "Quetzalcoatl",
        "ngod": "Camaxtli",
        "cgod": "Huhetotl",
        "filecode": "Arc",
        "homebase": "the College of Archeology",
        "intermed": "the Tomb of the Toltec Kings",
        "mnum": 331,
        "petnum": -1,
        "ldrnum": 344,
        "guardnum": 369,
        "neminum": 357,
        "enemy1num": -1,
        "enemy2num": 192,
        "enemy1sym": 45,
        "enemy2sym": 39,
        "questarti": 21,
        "allow": 12398,
        "attrbase": [
            7,
            10,
            10,
            7,
            7,
            7
        ],
        "attrdist": [
            20,
            20,
            20,
            10,
            20,
            10
        ],
        "hpadv": [
            11,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 14,
        "initrecord": 10,
        "spelbase": 5,
        "spelheal": 0,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": 1,
        "spelspec": 396,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Barbarian",
            "f": null
        },
        "rank": [
            {
                "m": "Plunderer",
                "f": "Plunderess"
            },
            {
                "m": "Pillager",
                "f": null
            },
            {
                "m": "Bandit",
                "f": null
            },
            {
                "m": "Brigand",
                "f": null
            },
            {
                "m": "Raider",
                "f": null
            },
            {
                "m": "Reaver",
                "f": null
            },
            {
                "m": "Slayer",
                "f": null
            },
            {
                "m": "Chieftain",
                "f": "Chieftainess"
            },
            {
                "m": "Conqueror",
                "f": "Conqueress"
            }
        ],
        "lgod": "Mitra",
        "ngod": "Crom",
        "cgod": "Set",
        "filecode": "Bar",
        "homebase": "the Camp of the Duali Tribe",
        "intermed": "the Duali Oasis",
        "mnum": 332,
        "petnum": -1,
        "ldrnum": 345,
        "guardnum": 370,
        "neminum": 358,
        "enemy1num": 203,
        "enemy2num": 220,
        "enemy1sym": 41,
        "enemy2sym": 46,
        "questarti": 22,
        "allow": 12427,
        "attrbase": [
            16,
            7,
            7,
            15,
            16,
            6
        ],
        "attrdist": [
            30,
            6,
            7,
            20,
            30,
            7
        ],
        "hpadv": [
            14,
            0,
            0,
            10,
            2,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 10,
        "initrecord": 10,
        "spelbase": 14,
        "spelheal": 0,
        "spelshld": 0,
        "spelarmr": 8,
        "spelstat": 1,
        "spelspec": 388,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Caveman",
            "f": "Cavewoman"
        },
        "rank": [
            {
                "m": "Troglodyte",
                "f": null
            },
            {
                "m": "Aborigine",
                "f": null
            },
            {
                "m": "Wanderer",
                "f": null
            },
            {
                "m": "Vagrant",
                "f": null
            },
            {
                "m": "Wayfarer",
                "f": null
            },
            {
                "m": "Roamer",
                "f": null
            },
            {
                "m": "Nomad",
                "f": null
            },
            {
                "m": "Rover",
                "f": null
            },
            {
                "m": "Pioneer",
                "f": null
            }
        ],
        "lgod": "Anu",
        "ngod": "_Ishtar",
        "cgod": "Anshar",
        "filecode": "Cav",
        "homebase": "the Caves of the Ancestors",
        "intermed": "the Dragon's Lair",
        "mnum": 333,
        "petnum": 16,
        "ldrnum": 346,
        "guardnum": 371,
        "neminum": 359,
        "enemy1num": 45,
        "enemy2num": 171,
        "enemy1sym": 8,
        "enemy2sym": 34,
        "questarti": 23,
        "allow": 12398,
        "attrbase": [
            10,
            7,
            7,
            7,
            8,
            6
        ],
        "attrdist": [
            30,
            6,
            7,
            20,
            30,
            7
        ],
        "hpadv": [
            14,
            0,
            0,
            8,
            2,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 10,
        "initrecord": 0,
        "spelbase": 12,
        "spelheal": 0,
        "spelshld": 1,
        "spelarmr": 8,
        "spelstat": 1,
        "spelspec": 366,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Healer",
            "f": null
        },
        "rank": [
            {
                "m": "Rhizotomist",
                "f": null
            },
            {
                "m": "Empiric",
                "f": null
            },
            {
                "m": "Embalmer",
                "f": null
            },
            {
                "m": "Dresser",
                "f": null
            },
            {
                "m": "Medicus ossium",
                "f": "Medica ossium"
            },
            {
                "m": "Herbalist",
                "f": null
            },
            {
                "m": "Magister",
                "f": "Magistra"
            },
            {
                "m": "Physician",
                "f": null
            },
            {
                "m": "Chirurgeon",
                "f": null
            }
        ],
        "lgod": "_Athena",
        "ngod": "Hermes",
        "cgod": "Poseidon",
        "filecode": "Hea",
        "homebase": "the Temple of Epidaurus",
        "intermed": "the Temple of Coeus",
        "mnum": 334,
        "petnum": -1,
        "ldrnum": 347,
        "guardnum": 372,
        "neminum": 360,
        "enemy1num": 89,
        "enemy2num": 215,
        "enemy1sym": 18,
        "enemy2sym": 51,
        "questarti": 24,
        "allow": 12362,
        "attrbase": [
            7,
            7,
            13,
            7,
            11,
            16
        ],
        "attrdist": [
            15,
            20,
            20,
            15,
            25,
            5
        ],
        "hpadv": [
            11,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            4,
            0,
            1,
            0,
            2
        ],
        "xlev": 20,
        "initrecord": 10,
        "spelbase": 3,
        "spelheal": -3,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": 2,
        "spelspec": 386,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Knight",
            "f": null
        },
        "rank": [
            {
                "m": "Gallant",
                "f": null
            },
            {
                "m": "Esquire",
                "f": null
            },
            {
                "m": "Bachelor",
                "f": null
            },
            {
                "m": "Sergeant",
                "f": null
            },
            {
                "m": "Knight",
                "f": null
            },
            {
                "m": "Banneret",
                "f": null
            },
            {
                "m": "Chevalier",
                "f": "Chevaliere"
            },
            {
                "m": "Seignieur",
                "f": "Dame"
            },
            {
                "m": "Paladin",
                "f": null
            }
        ],
        "lgod": "Lugh",
        "ngod": "_Brigit",
        "cgod": "Manannan Mac Lir",
        "filecode": "Kni",
        "homebase": "Camelot Castle",
        "intermed": "the Isle of Glass",
        "mnum": 335,
        "petnum": 100,
        "ldrnum": 348,
        "guardnum": 373,
        "neminum": 361,
        "enemy1num": 54,
        "enemy2num": 58,
        "enemy1sym": 9,
        "enemy2sym": 10,
        "questarti": 25,
        "allow": 12300,
        "attrbase": [
            13,
            7,
            14,
            8,
            10,
            17
        ],
        "attrdist": [
            30,
            15,
            15,
            10,
            20,
            10
        ],
        "hpadv": [
            14,
            0,
            0,
            8,
            2,
            0
        ],
        "enadv": [
            1,
            4,
            0,
            1,
            0,
            2
        ],
        "xlev": 10,
        "initrecord": 10,
        "spelbase": 8,
        "spelheal": -2,
        "spelshld": 0,
        "spelarmr": 9,
        "spelstat": 2,
        "spelspec": 398,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Monk",
            "f": null
        },
        "rank": [
            {
                "m": "Candidate",
                "f": null
            },
            {
                "m": "Novice",
                "f": null
            },
            {
                "m": "Initiate",
                "f": null
            },
            {
                "m": "Student of Stones",
                "f": null
            },
            {
                "m": "Student of Waters",
                "f": null
            },
            {
                "m": "Student of Metals",
                "f": null
            },
            {
                "m": "Student of Winds",
                "f": null
            },
            {
                "m": "Student of Fire",
                "f": null
            },
            {
                "m": "Master",
                "f": null
            }
        ],
        "lgod": "Shan Lai Ching",
        "ngod": "Chih Sung-tzu",
        "cgod": "Huan Ti",
        "filecode": "Mon",
        "homebase": "the Monastery of Chan-Sune",
        "intermed": "the Monastery of the Earth-Lord",
        "mnum": 336,
        "petnum": -1,
        "ldrnum": 349,
        "guardnum": 374,
        "neminum": 362,
        "enemy1num": 156,
        "enemy2num": 232,
        "enemy1sym": 31,
        "enemy2sym": 50,
        "questarti": 26,
        "allow": 12303,
        "attrbase": [
            10,
            7,
            8,
            8,
            7,
            7
        ],
        "attrdist": [
            25,
            10,
            20,
            20,
            15,
            10
        ],
        "hpadv": [
            12,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            2,
            2,
            0,
            2,
            0,
            2
        ],
        "xlev": 10,
        "initrecord": 10,
        "spelbase": 8,
        "spelheal": -2,
        "spelshld": 2,
        "spelarmr": 20,
        "spelstat": 2,
        "spelspec": 392,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Priest",
            "f": "Priestess"
        },
        "rank": [
            {
                "m": "Aspirant",
                "f": null
            },
            {
                "m": "Acolyte",
                "f": null
            },
            {
                "m": "Adept",
                "f": null
            },
            {
                "m": "Priest",
                "f": "Priestess"
            },
            {
                "m": "Curate",
                "f": null
            },
            {
                "m": "Canon",
                "f": "Canoness"
            },
            {
                "m": "Lama",
                "f": null
            },
            {
                "m": "Patriarch",
                "f": "Matriarch"
            },
            {
                "m": "High Priest",
                "f": "High Priestess"
            }
        ],
        "lgod": 0,
        "ngod": 0,
        "cgod": 0,
        "filecode": "Pri",
        "homebase": "the Great Temple",
        "intermed": "the Temple of Nalzok",
        "mnum": 337,
        "petnum": -1,
        "ldrnum": 350,
        "guardnum": 375,
        "neminum": 363,
        "enemy1num": 244,
        "enemy2num": 230,
        "enemy1sym": 52,
        "enemy2sym": 49,
        "questarti": 27,
        "allow": 12319,
        "attrbase": [
            7,
            7,
            10,
            7,
            7,
            7
        ],
        "attrdist": [
            15,
            10,
            30,
            15,
            20,
            10
        ],
        "hpadv": [
            12,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            4,
            3,
            0,
            2,
            0,
            2
        ],
        "xlev": 10,
        "initrecord": 0,
        "spelbase": 3,
        "spelheal": -2,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": 2,
        "spelspec": 395,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Rogue",
            "f": null
        },
        "rank": [
            {
                "m": "Footpad",
                "f": null
            },
            {
                "m": "Cutpurse",
                "f": null
            },
            {
                "m": "Rogue",
                "f": null
            },
            {
                "m": "Pilferer",
                "f": null
            },
            {
                "m": "Robber",
                "f": null
            },
            {
                "m": "Burglar",
                "f": null
            },
            {
                "m": "Filcher",
                "f": null
            },
            {
                "m": "Magsman",
                "f": "Magswoman"
            },
            {
                "m": "Thief",
                "f": null
            }
        ],
        "lgod": "Issek",
        "ngod": "Mog",
        "cgod": "Kos",
        "filecode": "Rog",
        "homebase": "the Thieves' Guild Hall",
        "intermed": "the Assassins' Guild Hall",
        "mnum": 339,
        "petnum": -1,
        "ldrnum": 352,
        "guardnum": 377,
        "neminum": 365,
        "enemy1num": 63,
        "enemy2num": 202,
        "enemy1sym": 14,
        "enemy2sym": 40,
        "questarti": 29,
        "allow": 12425,
        "attrbase": [
            7,
            7,
            7,
            10,
            7,
            6
        ],
        "attrdist": [
            20,
            10,
            10,
            30,
            20,
            10
        ],
        "hpadv": [
            10,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 11,
        "initrecord": 10,
        "spelbase": 8,
        "spelheal": 0,
        "spelshld": 1,
        "spelarmr": 9,
        "spelstat": 1,
        "spelspec": 394,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Ranger",
            "f": null
        },
        "rank": [
            {
                "m": "Tenderfoot",
                "f": null
            },
            {
                "m": "Lookout",
                "f": null
            },
            {
                "m": "Trailblazer",
                "f": null
            },
            {
                "m": "Reconnoiterer",
                "f": "Reconnoiteress"
            },
            {
                "m": "Scout",
                "f": null
            },
            {
                "m": "Arbalester",
                "f": null
            },
            {
                "m": "Archer",
                "f": null
            },
            {
                "m": "Sharpshooter",
                "f": null
            },
            {
                "m": "Marksman",
                "f": "Markswoman"
            }
        ],
        "lgod": "Mercury",
        "ngod": "_Venus",
        "cgod": "Mars",
        "filecode": "Ran",
        "homebase": "Orion's camp",
        "intermed": "the cave of the wumpus",
        "mnum": 338,
        "petnum": 16,
        "ldrnum": 351,
        "guardnum": 376,
        "neminum": 364,
        "enemy1num": 131,
        "enemy2num": 97,
        "enemy1sym": 29,
        "enemy2sym": 19,
        "questarti": 28,
        "allow": 12507,
        "attrbase": [
            13,
            13,
            13,
            9,
            13,
            7
        ],
        "attrdist": [
            30,
            10,
            10,
            20,
            20,
            10
        ],
        "hpadv": [
            13,
            0,
            0,
            6,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 12,
        "initrecord": 10,
        "spelbase": 9,
        "spelheal": 2,
        "spelshld": 1,
        "spelarmr": 10,
        "spelstat": 1,
        "spelspec": 393,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Samurai",
            "f": null
        },
        "rank": [
            {
                "m": "Hatamoto",
                "f": null
            },
            {
                "m": "Ronin",
                "f": null
            },
            {
                "m": "Ninja",
                "f": "Kunoichi"
            },
            {
                "m": "Joshu",
                "f": null
            },
            {
                "m": "Ryoshu",
                "f": null
            },
            {
                "m": "Kokushu",
                "f": null
            },
            {
                "m": "Daimyo",
                "f": null
            },
            {
                "m": "Kuge",
                "f": null
            },
            {
                "m": "Shogun",
                "f": null
            }
        ],
        "lgod": "_Amaterasu Omikami",
        "ngod": "Raijin",
        "cgod": "Susanowo",
        "filecode": "Sam",
        "homebase": "the Castle of the Taro Clan",
        "intermed": "the Shogun's Castle",
        "mnum": 340,
        "petnum": 16,
        "ldrnum": 353,
        "guardnum": 379,
        "neminum": 366,
        "enemy1num": 20,
        "enemy2num": 153,
        "enemy1sym": 4,
        "enemy2sym": 31,
        "questarti": 30,
        "allow": 12300,
        "attrbase": [
            10,
            8,
            7,
            10,
            17,
            6
        ],
        "attrdist": [
            30,
            10,
            8,
            30,
            14,
            8
        ],
        "hpadv": [
            13,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 11,
        "initrecord": 10,
        "spelbase": 10,
        "spelheal": 0,
        "spelshld": 0,
        "spelarmr": 8,
        "spelstat": 1,
        "spelspec": 385,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Tourist",
            "f": null
        },
        "rank": [
            {
                "m": "Rambler",
                "f": null
            },
            {
                "m": "Sightseer",
                "f": null
            },
            {
                "m": "Excursionist",
                "f": null
            },
            {
                "m": "Peregrinator",
                "f": "Peregrinatrix"
            },
            {
                "m": "Traveler",
                "f": null
            },
            {
                "m": "Journeyer",
                "f": null
            },
            {
                "m": "Voyager",
                "f": null
            },
            {
                "m": "Explorer",
                "f": null
            },
            {
                "m": "Adventurer",
                "f": null
            }
        ],
        "lgod": "Blind Io",
        "ngod": "_The Lady",
        "cgod": "Offler",
        "filecode": "Tou",
        "homebase": "Ankh-Morpork",
        "intermed": "the Thieves' Guild Hall",
        "mnum": 341,
        "petnum": -1,
        "ldrnum": 354,
        "guardnum": 380,
        "neminum": 352,
        "enemy1num": 96,
        "enemy2num": 131,
        "enemy1sym": 19,
        "enemy2sym": 29,
        "questarti": 31,
        "allow": 12298,
        "attrbase": [
            7,
            10,
            6,
            7,
            7,
            10
        ],
        "attrdist": [
            15,
            10,
            10,
            15,
            30,
            20
        ],
        "hpadv": [
            8,
            0,
            0,
            8,
            0,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 14,
        "initrecord": 0,
        "spelbase": 5,
        "spelheal": 1,
        "spelshld": 2,
        "spelarmr": 10,
        "spelstat": 1,
        "spelspec": 387,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Valkyrie",
            "f": null
        },
        "rank": [
            {
                "m": "Stripling",
                "f": null
            },
            {
                "m": "Skirmisher",
                "f": null
            },
            {
                "m": "Fighter",
                "f": null
            },
            {
                "m": "Man-at-arms",
                "f": "Woman-at-arms"
            },
            {
                "m": "Warrior",
                "f": null
            },
            {
                "m": "Swashbuckler",
                "f": null
            },
            {
                "m": "Hero",
                "f": "Heroine"
            },
            {
                "m": "Champion",
                "f": null
            },
            {
                "m": "Lord",
                "f": "Lady"
            }
        ],
        "lgod": "Tyr",
        "ngod": "Odin",
        "cgod": "Loki",
        "filecode": "Val",
        "homebase": "the Shrine of Destiny",
        "intermed": "the cave of Surtur",
        "mnum": 342,
        "petnum": -1,
        "ldrnum": 355,
        "guardnum": 381,
        "neminum": 367,
        "enemy1num": 3,
        "enemy2num": 172,
        "enemy1sym": 1,
        "enemy2sym": 34,
        "questarti": 32,
        "allow": 8238,
        "attrbase": [
            10,
            7,
            7,
            7,
            10,
            7
        ],
        "attrdist": [
            30,
            6,
            7,
            20,
            30,
            7
        ],
        "hpadv": [
            14,
            0,
            0,
            8,
            2,
            0
        ],
        "enadv": [
            1,
            0,
            0,
            1,
            0,
            1
        ],
        "xlev": 10,
        "initrecord": 0,
        "spelbase": 10,
        "spelheal": -2,
        "spelshld": 0,
        "spelarmr": 9,
        "spelstat": 2,
        "spelspec": 369,
        "spelsbon": -4
    },
    {
        "name": {
            "m": "Wizard",
            "f": null
        },
        "rank": [
            {
                "m": "Evoker",
                "f": null
            },
            {
                "m": "Conjurer",
                "f": null
            },
            {
                "m": "Thaumaturge",
                "f": null
            },
            {
                "m": "Magician",
                "f": null
            },
            {
                "m": "Enchanter",
                "f": "Enchantress"
            },
            {
                "m": "Sorcerer",
                "f": "Sorceress"
            },
            {
                "m": "Necromancer",
                "f": null
            },
            {
                "m": "Wizard",
                "f": null
            },
            {
                "m": "Mage",
                "f": null
            }
        ],
        "lgod": "Ptah",
        "ngod": "Thoth",
        "cgod": "Anhur",
        "filecode": "Wiz",
        "homebase": "the Lonely Tower",
        "intermed": "the Tower of Darkness",
        "mnum": 343,
        "petnum": 32,
        "ldrnum": 356,
        "guardnum": 382,
        "neminum": 368,
        "enemy1num": 129,
        "enemy2num": 232,
        "enemy1sym": 28,
        "enemy2sym": 49,
        "questarti": 33,
        "allow": 12507,
        "attrbase": [
            7,
            10,
            7,
            7,
            7,
            7
        ],
        "attrdist": [
            10,
            30,
            10,
            20,
            20,
            10
        ],
        "hpadv": [
            10,
            0,
            0,
            8,
            1,
            0
        ],
        "enadv": [
            4,
            3,
            0,
            2,
            0,
            3
        ],
        "xlev": 12,
        "initrecord": 0,
        "spelbase": 1,
        "spelheal": 0,
        "spelshld": 3,
        "spelarmr": 10,
        "spelstat": 1,
        "spelspec": 367,
        "spelsbon": -4
    }
];

export const races = [
    {
        "noun": "human",
        "adj": "human",
        "coll": "humanity",
        "filecode": "Hum",
        "individual": {
            "m": "man",
            "f": "woman"
        },
        "mnum": 260,
        "mummynum": 192,
        "zombienum": 244,
        "allow": 12303,
        "selfmask": 8,
        "lovemask": 0,
        "hatemask": 192,
        "attrmin": [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        "attrmax": [
            118,
            18,
            18,
            18,
            18,
            18
        ],
        "hpadv": [
            2,
            0,
            0,
            2,
            1,
            0
        ],
        "enadv": [
            1,
            0,
            2,
            0,
            2,
            0
        ]
    },
    {
        "noun": "elf",
        "adj": "elven",
        "coll": "elvenkind",
        "filecode": "Elf",
        "individual": {
            "m": 0,
            "f": null
        },
        "mnum": 264,
        "mummynum": 191,
        "zombienum": 243,
        "allow": 12305,
        "selfmask": 16,
        "lovemask": 16,
        "hatemask": 128,
        "attrmin": [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        "attrmax": [
            18,
            20,
            20,
            18,
            16,
            18
        ],
        "hpadv": [
            1,
            0,
            0,
            1,
            1,
            0
        ],
        "enadv": [
            2,
            0,
            3,
            0,
            3,
            0
        ]
    },
    {
        "noun": "dwarf",
        "adj": "dwarven",
        "coll": "dwarvenkind",
        "filecode": "Dwa",
        "individual": {
            "m": 0,
            "f": null
        },
        "mnum": 44,
        "mummynum": 190,
        "zombienum": 242,
        "allow": 12324,
        "selfmask": 32,
        "lovemask": 96,
        "hatemask": 128,
        "attrmin": [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        "attrmax": [
            118,
            16,
            16,
            20,
            20,
            16
        ],
        "hpadv": [
            4,
            0,
            0,
            3,
            2,
            0
        ],
        "enadv": [
            0,
            0,
            0,
            0,
            0,
            0
        ]
    },
    {
        "noun": "gnome",
        "adj": "gnomish",
        "coll": "gnomehood",
        "filecode": "Gno",
        "individual": {
            "m": 0,
            "f": null
        },
        "mnum": 165,
        "mummynum": 188,
        "zombienum": 240,
        "allow": 12354,
        "selfmask": 64,
        "lovemask": 96,
        "hatemask": 8,
        "attrmin": [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        "attrmax": [
            68,
            19,
            18,
            18,
            18,
            18
        ],
        "hpadv": [
            1,
            0,
            0,
            1,
            0,
            0
        ],
        "enadv": [
            2,
            0,
            2,
            0,
            2,
            0
        ]
    },
    {
        "noun": "orc",
        "adj": "orcish",
        "coll": "orcdom",
        "filecode": "Orc",
        "individual": {
            "m": 0,
            "f": null
        },
        "mnum": 72,
        "mummynum": 189,
        "zombienum": 241,
        "allow": 12417,
        "selfmask": 128,
        "lovemask": 0,
        "hatemask": 56,
        "attrmin": [
            3,
            3,
            3,
            3,
            3,
            3
        ],
        "attrmax": [
            68,
            16,
            16,
            18,
            18,
            16
        ],
        "hpadv": [
            1,
            0,
            0,
            1,
            0,
            0
        ],
        "enadv": [
            1,
            0,
            1,
            0,
            1,
            0
        ]
    }
];

export const genders = [
    {
        "adj": "male",
        "he": "he",
        "him": "him",
        "his": "his",
        "filecode": "Mal",
        "allow": 4096
    },
    {
        "adj": "female",
        "he": "she",
        "him": "her",
        "his": "her",
        "filecode": "Fem",
        "allow": 8192
    },
    {
        "adj": "neuter",
        "he": "it",
        "him": "it",
        "his": "its",
        "filecode": "Ntr",
        "allow": 16384
    },
    {
        "adj": "group",
        "he": "they",
        "him": "them",
        "his": "their",
        "filecode": "Grp",
        "allow": 0
    }
];

export const aligns = [
    {
        "noun": "law",
        "adj": "lawful",
        "filecode": "Law",
        "allow": 4,
        "value": 1
    },
    {
        "noun": "balance",
        "adj": "neutral",
        "filecode": "Neu",
        "allow": 2,
        "value": 0
    },
    {
        "noun": "chaos",
        "adj": "chaotic",
        "filecode": "Cha",
        "allow": 1,
        "value": -1
    },
    {
        "noun": "evil",
        "adj": "unaligned",
        "filecode": "Una",
        "allow": 0,
        "value": -128
    }
];

// src/attrib.c:23 struct innate — [experience level, intrinsic] per role and
// race. Keys are the C table names (arc_abil, sam_abil, elf_abil, ...).
export const INNATE = {
 "arc_abil": [
  [
   1,
   "HSearching",
   "",
   ""
  ],
  [
   5,
   "HStealth",
   "stealthy",
   ""
  ],
  [
   10,
   "HFast",
   "quick",
   "slow"
  ]
 ],
 "bar_abil": [
  [
   1,
   "HPoison_resistance",
   "",
   ""
  ],
  [
   7,
   "HFast",
   "quick",
   "slow"
  ],
  [
   15,
   "HStealth",
   "stealthy",
   ""
  ]
 ],
 "cav_abil": [
  [
   7,
   "HFast",
   "quick",
   "slow"
  ],
  [
   15,
   "HWarning",
   "sensitive",
   ""
  ]
 ],
 "hea_abil": [
  [
   1,
   "HPoison_resistance",
   "",
   ""
  ],
  [
   15,
   "HWarning",
   "sensitive",
   ""
  ]
 ],
 "kni_abil": [
  [
   7,
   "HFast",
   "quick",
   "slow"
  ]
 ],
 "mon_abil": [
  [
   1,
   "HFast",
   "",
   ""
  ],
  [
   1,
   "HSleep_resistance",
   "",
   ""
  ],
  [
   1,
   "HSee_invisible",
   "",
   ""
  ],
  [
   3,
   "HPoison_resistance",
   "healthy",
   ""
  ],
  [
   5,
   "HStealth",
   "stealthy",
   ""
  ],
  [
   7,
   "HWarning",
   "sensitive",
   ""
  ],
  [
   9,
   "HSearching",
   "perceptive",
   "unaware"
  ],
  [
   11,
   "HFire_resistance",
   "cool",
   "warmer"
  ],
  [
   13,
   "HCold_resistance",
   "warm",
   "cooler"
  ],
  [
   15,
   "HShock_resistance",
   "insulated",
   "conductive"
  ],
  [
   17,
   "HTeleport_control",
   "controlled",
   "uncontrolled"
  ]
 ],
 "pri_abil": [
  [
   15,
   "HWarning",
   "sensitive",
   ""
  ],
  [
   20,
   "HFire_resistance",
   "cool",
   "warmer"
  ]
 ],
 "ran_abil": [
  [
   1,
   "HSearching",
   "",
   ""
  ],
  [
   7,
   "HStealth",
   "stealthy",
   ""
  ],
  [
   15,
   "HSee_invisible",
   "",
   ""
  ]
 ],
 "rog_abil": [
  [
   1,
   "HStealth",
   "",
   ""
  ],
  [
   10,
   "HSearching",
   "perceptive",
   ""
  ]
 ],
 "sam_abil": [
  [
   1,
   "HFast",
   "",
   ""
  ],
  [
   15,
   "HStealth",
   "stealthy",
   ""
  ]
 ],
 "tou_abil": [
  [
   10,
   "HSearching",
   "perceptive",
   ""
  ],
  [
   20,
   "HPoison_resistance",
   "hardy",
   ""
  ]
 ],
 "val_abil": [
  [
   1,
   "HCold_resistance",
   "",
   ""
  ],
  [
   3,
   "HStealth",
   "stealthy",
   ""
  ],
  [
   7,
   "HFast",
   "quick",
   "slow"
  ]
 ],
 "wiz_abil": [
  [
   15,
   "HWarning",
   "sensitive",
   ""
  ],
  [
   17,
   "HTeleport_control",
   "controlled",
   "uncontrolled"
  ]
 ],
 "dwa_abil": [
  [
   1,
   "HInfravision",
   "",
   ""
  ]
 ],
 "elf_abil": [
  [
   1,
   "HInfravision",
   "",
   ""
  ],
  [
   4,
   "HSleep_resistance",
   "awake",
   "tired"
  ]
 ],
 "gno_abil": [
  [
   1,
   "HInfravision",
   "",
   ""
  ]
 ],
 "orc_abil": [
  [
   1,
   "HInfravision",
   "",
   ""
  ],
  [
   1,
   "HPoison_resistance",
   "",
   ""
  ]
 ],
 "hum_abil": []
};

// src/attrib.c role_abil() — the table for a role.
//
// Keyed by NAME, not by position: roles[] lists Rogue before Ranger, while the
// abil tables are alphabetical (ran_abil then rog_abil), so an index-based map
// silently swaps their intrinsics.
const ROLE_ABIL_BY_NAME = {
    Archeologist: 'arc_abil', Barbarian: 'bar_abil', Caveman: 'cav_abil',
    Healer: 'hea_abil', Knight: 'kni_abil', Monk: 'mon_abil',
    Priest: 'pri_abil', Ranger: 'ran_abil', Rogue: 'rog_abil',
    Samurai: 'sam_abil', Tourist: 'tou_abil', Valkyrie: 'val_abil',
    Wizard: 'wiz_abil',
};
export function role_abil(rolenum) {
    const nm = roles[rolenum]?.name?.m;
    return INNATE[ROLE_ABIL_BY_NAME[nm]] || [];
}

// src/attrib.c check_innate_abil() - all four infravision races have a table.
// adjabil() separately limits level-based race grants to elves and orcs.
export function race_abil(racenum) {
    const noun = races[racenum]?.noun;
    return INNATE[{
        dwarf: 'dwa_abil', elf: 'elf_abil', gnome: 'gno_abil', orc: 'orc_abil',
    }[noun]] || [];
}

// src/role.c str2role() matches on the role name, case-insensitively.
export function findRole(name) {
    const n = String(name).toLowerCase();
    return roles.find(r => r.name.m.toLowerCase() === n
                        || (r.name.f && r.name.f.toLowerCase() === n)) || null;
}
