// GENERATED by tools/gen-shknam.mjs — do not edit.
// Source: src/shknam.c shopkeeper name lists.
//
// Leading punctuation is significant and preserved verbatim; nameshk()
// and shkname() read it. Each list's LENGTH is an rn2() modulus.

export const SHKNAMES = {
    shkliquors: ["Njezjin","Tsjernigof","Ossipewsk","Gorlowka","Gomel","Konosja","Weliki Oestjoeg","Syktywkar","Sablja","Narodnaja","Kyzyl","Walbrzych","Swidnica","Klodzko","Raciborz","Gliwice","Brzeg","Krnov","Hradec Kralove","Leuk","Brig","Brienz","Thun","Sarnen","Burglen","Elm","Flims","Vals","Schuls","Zum Loch"],
    shkbooks: ["Skibbereen","Kanturk","Rath Luirc","Ennistymon","Lahinch","Kinnegad","Lugnaquillia","Enniscorthy","Gweebarra","Kittamagh","Nenagh","Sneem","Ballingeary","Kilgarvan","Cahersiveen","Glenbeigh","Kilmihil","Kiltamagh","Droichead Atha","Inniscrone","Clonegal","Lisnaskea","Culdaff","Dunfanaghy","Inishbofin","Kesh"],
    shkarmors: ["Demirci","Kalecik","Boyabai","Yildizeli","Gaziantep","Siirt","Akhalataki","Tirebolu","Aksaray","Ermenak","Iskenderun","Kadirli","Siverek","Pervari","Malasgirt","Bayburt","Ayancik","Zonguldak","Balya","Tefenni","Artvin","Kars","Makharadze","Malazgirt","Midyat","Birecik","Kirikkale","Alaca","Polatli","Nallihan"],
    shkwands: ["Yr Wyddgrug","Trallwng","Mallwyd","Pontarfynach","Rhaeader","Llandrindod","Llanfair-ym-muallt","Y-Fenni","Maesteg","Rhydaman","Beddgelert","Curig","Llanrwst","Llanerchymedd","Caergybi","Nairn","Turriff","Inverurie","Braemar","Lochnagar","Kerloch","Beinn a Ghlo","Drumnadrochit","Morven","Uist","Storr","Sgurr na Ciche","Cannich","Gairloch","Kyleakin","Dunvegan"],
    shkrings: ["Feyfer","Flugi","Gheel","Havic","Haynin","Hoboken","Imbyze","Juyn","Kinsky","Massis","Matray","Moy","Olycan","Sadelin","Svaving","Tapper","Terwen","Wirix","Ypey","Rastegaisa","Varjag Njarga","Kautekeino","Abisko","Enontekis","Rovaniemi","Avasaksa","Haparanda","Lulea","Gellivare","Oeloe","Kajaani","Fauske"],
    shkfoods: ["Djasinga","Tjibarusa","Tjiwidej","Pengalengan","Bandjar","Parbalingga","Bojolali","Sarangan","Ngebel","Djombang","Ardjawinangun","Berbek","Papar","Baliga","Tjisolok","Siboga","Banjoewangi","Trenggalek","Karangkobar","Njalindoeng","Pasawahan","Pameunpeuk","Patjitan","Kediri","Pemboeang","Tringanoe","Makin","Tipor","Semai","Berhala","Tegal","Samoe"],
    shkweapons: ["Voulgezac","Rouffiac","Lerignac","Touverac","Guizengeard","Melac","Neuvicq","Vanzac","Picq","Urignac","Corignac","Fleac","Lonzac","Vergt","Queyssac","Liorac","Echourgnac","Cazelon","Eypau","Carignan","Monbazillac","Jonzac","Pons","Jumilhac","Fenouilledes","Laguiolet","Saujon","Eymoutiers","Eygurande","Eauze","Labouheyre"],
    shktools: ["Ymla","Eed-morra","Elan Lapinski","Cubask","Nieb","Bnowr Falr","Sperc","Noskcirdneh","Yawolloh","Hyeghu","Niskal","Trahnil","Htargcm","Enrobwem","Kachzi Rellim","Regien","Donmyar","Yelpur","Nosnehpets","Stewe","Renrut","Senna Hut","-Zlaw","Nosalnef","Rewuorb","Rellenk","Yad","Cire Htims","Y-crad","Nenilukah","Corsh","Aned","Dark Eery","Niknar","Lapu","Lechaim","Rebrol-nek","AlliWar Wickson","Oguhmk","Telloc Cyaj"],
    shklight: ["Zarnesti","Slanic","Nehoiasu","Ludus","Sighisoara","Nisipitu","Razboieni","Bicaz","Dorohoi","Vaslui","Fetesti","Tirgu Neamt","Babadag","Zimnicea","Zlatna","Jiu","Eforie","Mamaia","Silistra","Tulovo","Panagyuritshte","Smolyan","Kirklareli","Pernik","Lom","Haskovo","Dobrinishte","Varvara","Oryahovo","Troyan","Lovech","Sliven"],
    shkgeneral: ["Hebiwerie","Possogroenoe","Asidonhopo","Manlobbi","Adjama","Pakka Pakka","Kabalebo","Wonotobo","Akalapi","Sipaliwini","Annootok","Upernavik","Angmagssalik","Aklavik","Inuvik","Tuktoyaktuk","Chicoutimi","Ouiatchouane","Chibougamau","Matagami","Kipawa","Kinojevis","Abitibi","Maganasipi","Akureyri","Kopasker","Budereyri","Akranes","Bordeyri","Holmavik"],
    shkhealthfoods: ["Ga'er","Zhangmu","Rikaze","Jiangji","Changdu","Linzhi","Shigatse","Gyantse","Ganden","Tsurphu","Lhasa","Tsedong","Drepung","=Azura","=Blaze","=Breanna","=Breezy","=Dharma","=Feather","=Jasmine","=Luna","=Melody","=Moonjava","=Petal","=Rhiannon","=Starla","=Tranquilla","=Windsong","=Zennia","=Zoe","=Zora"],
};

// The shknms field of each shtypes[] entry, in table order.
export const SHKNMS_ORDER = ["shkgeneral","shkarmors","shkbooks","shkliquors","shkweapons","shkfoods","shkrings","shkwands","shktools","shkbooks","shkhealthfoods","shklight"];
