// themerms_data.js — GENERATED by tools/gen-themerms.mjs. Do not edit.
// Source: dat/themerms.lua, loaded with the real Lua 5.4.8 interpreter.
//
// themerooms_generate() reservoir-samples one entry per call:
//
//     total_frequency = total_frequency + this_frequency
//     if this_frequency > 0 and nh.rn2(total_frequency) < this_frequency then
//        pick = i
//
// so BOTH the order and the frequencies are part of the PRNG contract, and
// mindiff/maxdiff change which entries are eligible at a given level.
//
// 31 themerooms (19 of them stamp a des.map),
// 15 themeroom_fills.

export const themerooms = [
 {
  "index": 1,
  "name": "default",
  "frequency": 1000,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 2,
  "name": "Fake Delphi",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 3,
  "name": "Room in a room",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 4,
  "name": "Huge room with another room inside",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 5,
  "name": "Nesting rooms",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 6,
  "name": "Default room with themed fill",
  "frequency": 6,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 7,
  "name": "Unlit room with themed fill",
  "frequency": 2,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 8,
  "name": "Room with both normal contents and themed fill",
  "frequency": 2,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 9,
  "name": "Pillars",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 10,
  "name": "Mausoleum",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 11,
  "name": "Random dungeon feature in the middle of an odd-sized room",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 12,
  "name": "L-shaped",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 8,
    "rows": [
     "-----xxx",
     "|...|xxx",
     "|...|xxx",
     "|...----",
     "|......|",
     "|......|",
     "|......|",
     "--------"
    ],
    "filler": [
     1,
     1
    ]
   }
  ]
 },
 {
  "index": 13,
  "name": "L-shaped, rot 1",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 8,
    "rows": [
     "xxx-----",
     "xxx|...|",
     "xxx|...|",
     "----...|",
     "|......|",
     "|......|",
     "|......|",
     "--------"
    ],
    "filler": [
     5,
     1
    ]
   }
  ]
 },
 {
  "index": 14,
  "name": "L-shaped, rot 2",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 8,
    "rows": [
     "--------",
     "|......|",
     "|......|",
     "|......|",
     "----...|",
     "xxx|...|",
     "xxx|...|",
     "xxx-----"
    ],
    "filler": [
     1,
     1
    ]
   }
  ]
 },
 {
  "index": 15,
  "name": "L-shaped, rot 3",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 8,
    "rows": [
     "--------",
     "|......|",
     "|......|",
     "|......|",
     "|...----",
     "|...|xxx",
     "|...|xxx",
     "-----xxx"
    ],
    "filler": [
     1,
     1
    ]
   }
  ]
 },
 {
  "index": 16,
  "name": "Blocked center",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 11,
    "rows": [
     "-----------",
     "|.........|",
     "|.........|",
     "|.........|",
     "|...LLL...|",
     "|...LLL...|",
     "|...LLL...|",
     "|.........|",
     "|.........|",
     "|.........|",
     "-----------"
    ]
   }
  ]
 },
 {
  "index": 17,
  "name": "Circular, small",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 7,
    "hei": 7,
    "rows": [
     "xx---xx",
     "x--.--x",
     "--...--",
     "|.....|",
     "--...--",
     "x--.--x",
     "xx---xx"
    ],
    "filler": [
     3,
     3
    ]
   }
  ]
 },
 {
  "index": 18,
  "name": "Circular, medium",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 9,
    "hei": 9,
    "rows": [
     "xx-----xx",
     "x--...--x",
     "--.....--",
     "|.......|",
     "|.......|",
     "|.......|",
     "--.....--",
     "x--...--x",
     "xx-----xx"
    ],
    "filler": [
     4,
     4
    ]
   }
  ]
 },
 {
  "index": 19,
  "name": "Circular, big",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 11,
    "rows": [
     "xxx-----xxx",
     "x---...---x",
     "x-.......-x",
     "--.......--",
     "|.........|",
     "|.........|",
     "|.........|",
     "--.......--",
     "x-.......-x",
     "x---...---x",
     "xxx-----xxx"
    ],
    "filler": [
     5,
     5
    ]
   }
  ]
 },
 {
  "index": 20,
  "name": "T-shaped",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 8,
    "rows": [
     "xxx-----xxx",
     "xxx|...|xxx",
     "xxx|...|xxx",
     "----...----",
     "|.........|",
     "|.........|",
     "|.........|",
     "-----------"
    ],
    "filler": [
     5,
     5
    ]
   }
  ]
 },
 {
  "index": 21,
  "name": "T-shaped, rot 1",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 11,
    "rows": [
     "-----xxx",
     "|...|xxx",
     "|...|xxx",
     "|...----",
     "|......|",
     "|......|",
     "|......|",
     "|...----",
     "|...|xxx",
     "|...|xxx",
     "-----xxx"
    ],
    "filler": [
     2,
     2
    ]
   }
  ]
 },
 {
  "index": 22,
  "name": "T-shaped, rot 2",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 8,
    "rows": [
     "-----------",
     "|.........|",
     "|.........|",
     "|.........|",
     "----...----",
     "xxx|...|xxx",
     "xxx|...|xxx",
     "xxx-----xxx"
    ],
    "filler": [
     2,
     2
    ]
   }
  ]
 },
 {
  "index": 23,
  "name": "T-shaped, rot 3",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 11,
    "rows": [
     "xxx-----",
     "xxx|...|",
     "xxx|...|",
     "----...|",
     "|......|",
     "|......|",
     "|......|",
     "----...|",
     "xxx|...|",
     "xxx|...|",
     "xxx-----"
    ],
    "filler": [
     5,
     5
    ]
   }
  ]
 },
 {
  "index": 24,
  "name": "S-shaped",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 11,
    "rows": [
     "-----xxx",
     "|...|xxx",
     "|...|xxx",
     "|...----",
     "|......|",
     "|......|",
     "|......|",
     "----...|",
     "xxx|...|",
     "xxx|...|",
     "xxx-----"
    ],
    "filler": [
     2,
     2
    ]
   }
  ]
 },
 {
  "index": 25,
  "name": "S-shaped, rot 1",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 8,
    "rows": [
     "xxx--------",
     "xxx|......|",
     "xxx|......|",
     "----......|",
     "|......----",
     "|......|xxx",
     "|......|xxx",
     "--------xxx"
    ],
    "filler": [
     5,
     5
    ]
   }
  ]
 },
 {
  "index": 26,
  "name": "Z-shaped",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 8,
    "hei": 11,
    "rows": [
     "xxx-----",
     "xxx|...|",
     "xxx|...|",
     "----...|",
     "|......|",
     "|......|",
     "|......|",
     "|...----",
     "|...|xxx",
     "|...|xxx",
     "-----xxx"
    ],
    "filler": [
     5,
     5
    ]
   }
  ]
 },
 {
  "index": 27,
  "name": "Z-shaped, rot 1",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 8,
    "rows": [
     "--------xxx",
     "|......|xxx",
     "|......|xxx",
     "|......----",
     "----......|",
     "xxx|......|",
     "xxx|......|",
     "xxx--------"
    ],
    "filler": [
     2,
     2
    ]
   }
  ]
 },
 {
  "index": 28,
  "name": "Cross",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 11,
    "rows": [
     "xxx-----xxx",
     "xxx|...|xxx",
     "xxx|...|xxx",
     "----...----",
     "|.........|",
     "|.........|",
     "|.........|",
     "----...----",
     "xxx|...|xxx",
     "xxx|...|xxx",
     "xxx-----xxx"
    ],
    "filler": [
     6,
     6
    ]
   }
  ]
 },
 {
  "index": 29,
  "name": "Four-leaf clover",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 11,
    "hei": 11,
    "rows": [
     "-----x-----",
     "|...|x|...|",
     "|...---...|",
     "|.........|",
     "---.....---",
     "xx|.....|xx",
     "---.....---",
     "|.........|",
     "|...---...|",
     "|...|x|...|",
     "-----x-----"
    ],
    "filler": [
     6,
     6
    ]
   }
  ]
 },
 {
  "index": 30,
  "name": "Water-surrounded vault",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null,
  "maps": [
   {
    "wid": 6,
    "hei": 6,
    "rows": [
     "}}}}}}",
     "}----}",
     "}|..|}",
     "}|..|}",
     "}----}",
     "}}}}}}"
    ]
   }
  ]
 },
 {
  "index": 31,
  "name": "Twin businesses",
  "frequency": 1,
  "mindiff": 4,
  "maxdiff": null
 }
];

export const themeroom_fills = [
 {
  "index": 1,
  "name": "Ice room",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 2,
  "name": "Cloud room",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 3,
  "name": "Boulder room",
  "frequency": 1,
  "mindiff": 4,
  "maxdiff": null
 },
 {
  "index": 4,
  "name": "Spider nest",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 5,
  "name": "Trap room",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 6,
  "name": "Garden",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 7,
  "name": "Buried treasure",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 8,
  "name": "Buried zombies",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 9,
  "name": "Massacre",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 10,
  "name": "Statuary",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 11,
  "name": "Light source",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 12,
  "name": "Temple of the gods",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 13,
  "name": "Ghost of an Adventurer",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 14,
  "name": "Storeroom",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 },
 {
  "index": 15,
  "name": "Teleportation hub",
  "frequency": 1,
  "mindiff": null,
  "maxdiff": null
 }
];
