// uinit_data.js — GENERATED by tools/gen-uinit.mjs.
// Do not edit by hand; re-run the generator.
//
// The struct trobj tables from src/u_init.c: one per role, plus the shared
// extras a role may additionally roll (Lamp, Magicmarker, Blindfold, Leash,
// Towel, Tinopener, Xtra_food, Money, Wishing, and the three Monk spellbooks).
//
// Each row is { trotyp, trspe, trclass, trquan_min, trquan_max, trbless }, with
// every identifier resolved to its number. The all-zero terminator row is kept
// because ini_inv()'s loop condition is `while (trop->trclass)`.
//
// 26 tables.

export const UNDEF_TYP = 0;
export const UNDEF_SPE = 127;
export const UNDEF_BLESS = 2;

export const TROBJ = {
 "Archeologist": [
  {
   "trotyp": 82,
   "trspe": 2,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 135,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 92,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 293,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 3,
   "trquan_max": 3,
   "trbless": 0
  },
  {
   "trotyp": 259,
   "trspe": 127,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 238,
   "trspe": 127,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 472,
   "trspe": 0,
   "trclass": 13,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 217,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Barbarian_0": [
  {
   "trotyp": 55,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 44,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 132,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 293,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Barbarian_1": [
  {
   "trotyp": 45,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 46,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 132,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 293,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Cave_man": [
  {
   "trotyp": 77,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 87,
   "trspe": 2,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 473,
   "trspe": 0,
   "trclass": 13,
   "trquan_min": 10,
   "trquan_max": 20,
   "trbless": 2
  },
  {
   "trotyp": 474,
   "trspe": 0,
   "trclass": 13,
   "trquan_min": 3,
   "trquan_max": 3,
   "trbless": 0
  },
  {
   "trotyp": 134,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Healer": [
  {
   "trotyp": 39,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 159,
   "trspe": 1,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 237,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 307,
   "trspe": 0,
   "trclass": 8,
   "trquan_min": 4,
   "trquan_max": 4,
   "trbless": 2
  },
  {
   "trotyp": 308,
   "trspe": 0,
   "trclass": 8,
   "trquan_min": 4,
   "trquan_max": 4,
   "trbless": 2
  },
  {
   "trotyp": 432,
   "trspe": 127,
   "trclass": 11,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 374,
   "trspe": 0,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 391,
   "trspe": 0,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 405,
   "trspe": 0,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 277,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 5,
   "trquan_max": 5,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Knight": [
  {
   "trotyp": 54,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 72,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 132,
   "trspe": 1,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 97,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 150,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 159,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 277,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 10,
   "trquan_max": 10,
   "trbless": 0
  },
  {
   "trotyp": 282,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 10,
   "trquan_max": 10,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Monk": [
  {
   "trotyp": 159,
   "trspe": 2,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 143,
   "trspe": 1,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 9,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 307,
   "trspe": 0,
   "trclass": 8,
   "trquan_min": 3,
   "trquan_max": 3,
   "trbless": 2
  },
  {
   "trotyp": 293,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 3,
   "trquan_max": 3,
   "trbless": 0
  },
  {
   "trotyp": 277,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 5,
   "trquan_max": 5,
   "trbless": 2
  },
  {
   "trotyp": 278,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 5,
   "trquan_max": 5,
   "trbless": 2
  },
  {
   "trotyp": 289,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 3,
   "trquan_max": 3,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Priest": [
  {
   "trotyp": 73,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 143,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 150,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 322,
   "trspe": 0,
   "trclass": 8,
   "trquan_min": 4,
   "trquan_max": 4,
   "trbless": 1
  },
  {
   "trotyp": 284,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 283,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 10,
   "trquan_min": 2,
   "trquan_max": 2,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Ranger": [
  {
   "trotyp": 34,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 83,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 18,
   "trspe": 2,
   "trclass": 2,
   "trquan_min": 50,
   "trquan_max": 59,
   "trbless": 2
  },
  {
   "trotyp": 18,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 30,
   "trquan_max": 39,
   "trbless": 2
  },
  {
   "trotyp": 149,
   "trspe": 2,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 292,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 4,
   "trquan_max": 4,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Rogue": [
  {
   "trotyp": 46,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 34,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 6,
   "trquan_max": 15,
   "trbless": 0
  },
  {
   "trotyp": 134,
   "trspe": 1,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 318,
   "trspe": 0,
   "trclass": 8,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 222,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 217,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Samurai": [
  {
   "trotyp": 56,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 46,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 86,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 22,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 26,
   "trquan_max": 45,
   "trbless": 2
  },
  {
   "trotyp": 124,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Tourist": [
  {
   "trotyp": 24,
   "trspe": 2,
   "trclass": 2,
   "trquan_min": 21,
   "trquan_max": 40,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 7,
   "trquan_min": 10,
   "trquan_max": 10,
   "trbless": 0
  },
  {
   "trotyp": 308,
   "trspe": 0,
   "trclass": 8,
   "trquan_min": 2,
   "trquan_max": 2,
   "trbless": 2
  },
  {
   "trotyp": 337,
   "trspe": 0,
   "trclass": 9,
   "trquan_min": 4,
   "trquan_max": 4,
   "trbless": 2
  },
  {
   "trotyp": 136,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 229,
   "trspe": 127,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 223,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Valkyrie": [
  {
   "trotyp": 27,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 34,
   "trspe": 0,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 150,
   "trspe": 3,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 293,
   "trspe": 0,
   "trclass": 7,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Wizard": [
  {
   "trotyp": 79,
   "trspe": 1,
   "trclass": 2,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 148,
   "trspe": 0,
   "trclass": 3,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 11,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 4,
   "trquan_min": 2,
   "trquan_max": 2,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 8,
   "trquan_min": 3,
   "trquan_max": 3,
   "trbless": 2
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 9,
   "trquan_min": 3,
   "trquan_max": 3,
   "trbless": 2
  },
  {
   "trotyp": 376,
   "trspe": 0,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 2
  },
  {
   "trotyp": 242,
   "trspe": 19,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Healing_book": [
  {
   "trotyp": 374,
   "trspe": 127,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Protection_book": [
  {
   "trotyp": 403,
   "trspe": 127,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Confuse_monster_book": [
  {
   "trotyp": 377,
   "trspe": 127,
   "trclass": 10,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 1
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Tinopener": [
  {
   "trotyp": 239,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Magicmarker": [
  {
   "trotyp": 242,
   "trspe": 19,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Lamp": [
  {
   "trotyp": 227,
   "trspe": 1,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Blindfold": [
  {
   "trotyp": 233,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Xtra_food": [
  {
   "trotyp": 0,
   "trspe": 127,
   "trclass": 7,
   "trquan_min": 2,
   "trquan_max": 2,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Leash": [
  {
   "trotyp": 236,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Towel": [
  {
   "trotyp": 234,
   "trspe": 0,
   "trclass": 6,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Wishing": [
  {
   "trotyp": 414,
   "trspe": 3,
   "trclass": 11,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ],
 "Money": [
  {
   "trotyp": 438,
   "trspe": 0,
   "trclass": 12,
   "trquan_min": 1,
   "trquan_max": 1,
   "trbless": 0
  },
  {
   "trotyp": 0,
   "trspe": 0,
   "trclass": 0,
   "trquan_min": 0,
   "trquan_max": 0,
   "trbless": 0
  }
 ]
};
