// version_data.js — the #version pager text.
//
// src/version.c doextversion() composes this from the build's dat/options
// file (generated by makedefs from config.h at compile time) plus the Lua
// interpreter's own copyright block. It is BUILD data, identical for every
// session of the recorder binary; the version banner line itself is
// normalized by the scorer (<<VERSION_BANNER>>), so only the prefix before
// "Version" must match.
//
// The :LUAVERSION: substitution has already been applied.

export const VERSION_BANNER_LINE =
    'MacOS NetHack Version 5.0.0 - last build May  2 2026 12:00:00.';

export const VERSION_OPTIONS_TEXT = [
    '',
    'Options compiled into this edition:',
    '    I32LP64 data model, color, data file compression, deferred handling of',
    '    hangup signal, insurance files for recovering from crashes, live logging',
    '    support, log file, extended log file, errors and warnings log file, mail',
    '    daemon, news file, internal pager used for viewing help files, pattern',
    '    matching via posixregex, pseudo random numbers generated by ISAAC64,',
    '    strong PRNG seed from /dev/random, restore saved games via menu, screen',
    '    clipping, shell command, traditional status display, status via',
    '    windowport with highlighting, suspend command, terminal info library,',
    '    system configuration at run-time, show stack trace on error, launch',
    '    browser to report issues, save and bones files accepted from version',
    '    5.0.0 only, and basic NetHack features.',
    '',
    'Supported windowing system:',
    '    "tty" (traditional text with optional line-drawing).',
    '',
    'Supported soundlib:',
    '    "nosound".',
    '',
    "NetHack 5.0.* uses the 'Lua' interpreter to process some data:",
    '    Lua 5.4.8  Copyright (C) 1994-2025 Lua.org, PUC-Rio',
    '    "Permission is hereby granted, free of charge, to any person obtaining',
    '     a copy of this software and associated documentation files (the',
    '     "Software"), to deal in the Software without restriction including',
    '     without limitation the rights to use, copy, modify, merge, publish,',
    '     distribute, sublicense, and/or sell copies of the Software, and to',
    '     permit persons to whom the Software is furnished to do so, subject to',
    '     the following conditions:',
    '     The above copyright notice and this permission notice shall be',
    '     included in all copies or substantial portions of the Software."',
];
