// dat/water.js — the Plane of Water.
// C ref: dat/water.lua
//
// A level that is one solid sea. The hero arrives in an air bubble in the
// leftmost third; the portal to the Astral Plane floats in a bubble in the
// rightmost third. Bubbles are generated by special code in mkmaze.c
// (setup_waterlevel), not by the script.

import { lspo_level_flags, lspo_level_init, lspo_map_full, lspo_message,
         lspo_teleport_region, lspo_levregion,
         lspo_monster } from '../sp_lev.js';

const WATER_MAP = `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
`.replace(/^\n/, '').replace(/\n$/, '');

export async function water_level() {
    const des = {
        level_init: lspo_level_init,
        level_flags: lspo_level_flags,
        message: lspo_message,
        map: lspo_map_full,
        teleport_region: lspo_teleport_region,
        levregion: lspo_levregion,
        monster: (a, x, y, o) => lspo_monster(a, x, y, o),
    };

    des.level_init({ style: 'solidfill', fg: ' ' });

    des.level_flags('mazelevel', 'noteleport', 'hardfloor', 'shortsighted');
    des.message(
        'You find yourself suspended in an air bubble surrounded by water.');
    /* The player lands upon arrival to an air bubble within the leftmost
       third of the level.  The portal to the next level is randomly located
       in an air bubble within the rightmost third of the level.  Bubbles
       are generated by special code in mkmaze.c for now. */
    des.map(WATER_MAP);
    des.teleport_region({ region: [0, 0, 25, 19] });
    des.levregion({ type: 'portal', region: [51, 0, 75, 19],
                    name: 'astral' });
    /* A fisherman's dream... */
    des.monster('giant eel');
    des.monster('giant eel');
    des.monster('giant eel');
    des.monster('giant eel');
    des.monster('giant eel');
    des.monster('giant eel');
    des.monster('giant eel');
    des.monster('giant eel');
    des.monster('electric eel');
    des.monster('electric eel');
    des.monster('electric eel');
    des.monster('electric eel');
    des.monster('electric eel');
    des.monster('electric eel');
    des.monster('electric eel');
    des.monster('electric eel');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('kraken');
    des.monster('shark');
    des.monster('shark');
    des.monster('shark');
    des.monster('shark');
    des.monster('piranha');
    des.monster('piranha');
    des.monster('piranha');
    des.monster('piranha');
    des.monster('jellyfish');
    des.monster('jellyfish');
    des.monster('jellyfish');
    des.monster('jellyfish');
    des.monster(';');
    des.monster(';');
    des.monster(';');
    des.monster(';');
    /* These guys feel like home here */
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
    des.monster({ id: 'water elemental', peaceful: 0 });
}
