#!/usr/bin/env node
// coverage-map.mjs — Measure which C source files each recorded session
// actually executes, and generate docs/plan/coverage-map.md.
//
// Every recorded PRNG call carries a "@ function(file.c:line)" annotation, so
// the RNG log of a session is a direct sample of which C code ran. Aggregating
// that across the corpus gives a *measured* port priority order rather than a
// guessed one: the files that appear in the most sessions are the files whose
// absence costs the most points.
//
// Usage:
//   node tools/coverage-map.mjs                  # write docs/plan/coverage-map.md
//   node tools/coverage-map.mjs --dir sessions-private
//   node tools/coverage-map.mjs --stdout         # print instead of writing

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = fileURLToPath(new URL('..', import.meta.url));
const OUT = join(PROJECT_ROOT, 'docs/plan/coverage-map.md');

const ANNOTATION = /@\s*([A-Za-z0-9_]+)\(([A-Za-z0-9_.]+):(\d+)\)\s*$/;

function rcValue(rc, key) {
    const m = new RegExp(`${key}:([^,\\n]+)`).exec(rc || '');
    return m ? m[1].trim() : null;
}

function analyse(path) {
    const session = JSON.parse(readFileSync(path, 'utf8'));
    const segments = session.segments || [];
    const files = new Map();     // file.c -> call count
    const functions = new Map(); // fn -> call count
    let steps = 0, calls = 0;

    for (const seg of segments) {
        for (const step of seg.steps || []) {
            steps++;
            for (const entry of step.rng || []) {
                const m = ANNOTATION.exec(entry);
                if (!m) continue;
                calls++;
                files.set(m[2], (files.get(m[2]) || 0) + 1);
                functions.set(m[1], (functions.get(m[1]) || 0) + 1);
            }
        }
    }

    const rc = segments[0]?.nethackrc || '';
    return {
        name: path.split('/').pop().replace('.session.json', ''),
        segments: segments.length,
        steps,
        calls,
        role: rcValue(rc, 'role') || '?',
        race: rcValue(rc, 'race') || '?',
        debug: /playmode:debug/.test(rc),
        symset: rcValue(rc, 'symset') || 'default',
        files,
        functions,
    };
}

function topN(map, n) {
    return [...map.entries()].sort((a, b) => b[1] - a[1]).slice(0, n);
}

function main() {
    const argv = process.argv.slice(2);
    const dirIdx = argv.indexOf('--dir');
    const dir = join(PROJECT_ROOT, dirIdx >= 0 ? argv[dirIdx + 1] : 'sessions');
    const toStdout = argv.includes('--stdout');

    const paths = readdirSync(dir)
        .filter(f => f.endsWith('.session.json'))
        .sort()
        .map(f => join(dir, f));

    const sessions = paths.map(analyse);

    // Aggregate: how many sessions touch each C file, and how many calls.
    const fileSessions = new Map();
    const fileCalls = new Map();
    for (const s of sessions) {
        for (const [f, n] of s.files) {
            fileSessions.set(f, (fileSessions.get(f) || 0) + 1);
            fileCalls.set(f, (fileCalls.get(f) || 0) + n);
        }
    }

    const totalSteps = sessions.reduce((a, s) => a + s.steps, 0);
    const totalCalls = sessions.reduce((a, s) => a + s.calls, 0);

    const L = [];
    L.push('# Coverage map (generated)');
    L.push('');
    L.push('**Generated by `node tools/coverage-map.mjs`. Do not edit by hand.**');
    L.push('');
    L.push('Every recorded PRNG call carries a `@ function(file.c:line)` annotation, so');
    L.push('a session\'s RNG log is a direct sample of which C code ran while it was');
    L.push('recorded. This file aggregates that across the corpus.');
    L.push('');
    L.push('Two caveats worth keeping in mind. It only sees code that *draws random');
    L.push('numbers*, so purely deterministic subsystems — most of the tty windowport,');
    L.push('`botl.c`, `objnam.c` — are invisible here despite being where a large share');
    L.push('of the screen output comes from. And it describes the public corpus, which');
    L.push('is early-game heavy; the held-out set will go deeper.');
    L.push('');
    L.push(`Corpus: **${sessions.length} sessions**, ${totalSteps} steps, ${totalCalls} annotated PRNG calls.`);
    L.push('');

    L.push('## Port priority, measured');
    L.push('');
    L.push('Sorted by how many sessions execute the file. A file near the top is one');
    L.push('whose absence blocks progress almost everywhere.');
    L.push('');
    L.push('| C file | sessions | PRNG calls | share |');
    L.push('|---|---:|---:|---:|');
    const ranked = [...fileSessions.entries()].sort((a, b) =>
        b[1] - a[1] || (fileCalls.get(b[0]) - fileCalls.get(a[0])));
    for (const [f, nSessions] of ranked) {
        const calls = fileCalls.get(f);
        const share = ((calls / totalCalls) * 100).toFixed(1);
        L.push(`| \`src/${f}\` | ${nSessions}/${sessions.length} | ${calls} | ${share}% |`);
    }
    L.push('');

    L.push('## Per session');
    L.push('');
    L.push('`top C files` lists the five files that drew the most random numbers in that');
    L.push('session — a quick read of what the session is really exercising.');
    L.push('');
    L.push('| session | role | segs | steps | calls | top C files |');
    L.push('|---|---|---:|---:|---:|---|');
    for (const s of [...sessions].sort((a, b) => b.steps - a.steps)) {
        const top = topN(s.files, 5).map(([f, n]) => `${f} (${n})`).join(', ');
        const role = s.debug ? `${s.role} ${'`debug`'}` : s.role;
        L.push(`| \`${s.name}\` | ${role} | ${s.segments} | ${s.steps} | ${s.calls} | ${top} |`);
    }
    L.push('');

    L.push('## Sessions by role');
    L.push('');
    const byRole = new Map();
    for (const s of sessions) {
        if (!byRole.has(s.role)) byRole.set(s.role, []);
        byRole.get(s.role).push(s.name);
    }
    for (const [role, names] of [...byRole.entries()].sort()) {
        L.push(`- **${role}** (${names.length}): ${names.join(', ')}`);
    }
    L.push('');

    const debugSessions = sessions.filter(s => s.debug);
    L.push('## Sessions recorded in debug mode');
    L.push('');
    L.push(`${debugSessions.length} of ${sessions.length} sessions set \`playmode:debug\`. These need`);
    L.push('wizard-mode command handling, and the recorder needs `WIZARDS=*` in its');
    L.push('sysconf to reproduce them — see [NOTES.md](NOTES.md).');
    L.push('');
    for (const s of debugSessions) L.push(`- \`${s.name}\``);
    L.push('');

    const text = L.join('\n');
    if (toStdout) {
        process.stdout.write(text);
    } else {
        writeFileSync(OUT, text);
        console.log(`wrote ${OUT}`);
        console.log(`${sessions.length} sessions, ${ranked.length} distinct C files touched`);
        console.log('\ntop 12 by session coverage:');
        for (const [f, n] of ranked.slice(0, 12)) {
            console.log(`  src/${f.padEnd(14)} ${String(n).padStart(3)}/${sessions.length} sessions  ${fileCalls.get(f)} calls`);
        }
    }
}

main();
