// gen-extcmd.mjs — scrape src/cmd.c's extcmdlist[] into js/extcmd_data.js.
//
// The table drives two things a session depends on: which names #-completion
// will expand a prefix to, and which names an exact match accepts. Both are
// filtered by the AUTOCOMPLETE flag, so the flags have to come across too, not
// just the names.
//
//     src/cmd.c:1667  struct ext_func_tab extcmdlist[] = {
//         { '#', "#", "enter and perform an extended command",
//           doextcmd, IFBURIED | GENERALCMD | CMD_M_PREFIX, NULL },
//
// Entries span a variable number of lines, so this splits the initialiser on
// top-level braces rather than trying to match line by line.

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(ROOT, 'nethack-c/upstream/src/cmd.c'), 'utf8');

const start = src.indexOf('struct ext_func_tab extcmdlist[] = {');
if (start < 0) throw new Error('extcmdlist[] not found');
const open = src.indexOf('{', start + 'struct ext_func_tab extcmdlist[] ='.length);

// Walk to the matching close brace of the initialiser.
let depth = 0, end = open;
for (let i = open; i < src.length; i++) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') { depth--; if (depth === 0) { end = i; break; } }
}
const body = src.slice(open + 1, end);

// Split into top-level { ... } entries.
const entries = [];
depth = 0;
let cur = '';
for (const ch of body) {
    if (ch === '{') { depth++; if (depth === 1) { cur = ''; continue; } }
    if (ch === '}') { depth--; if (depth === 0) { entries.push(cur); continue; } }
    if (depth >= 1) cur += ch;
}

// include/func_tab.h flag bits, read from the header so they cannot drift.
const hdr = readFileSync(join(ROOT, 'nethack-c/upstream/include/func_tab.h'), 'utf8');
const FLAGS = {};
for (const m of hdr.matchAll(/^#define\s+([A-Z0-9_]+)\s+(0x[0-9a-fA-F]+|\d+)\s*(?:\/\*|$)/gm))
    FLAGS[m[1]] = Number(m[2]);

const out = [];
for (const e of entries) {
    // ef_txt is the second field: a string literal after the key.
    const strs = [...e.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map(m => m[1]);
    if (strs.length < 1) continue;
    const ef_txt = strs[0];

    // flags is the field after the function pointer; collect the ALL_CAPS
    // identifiers that name known bits.
    let flags = 0;
    for (const m of e.matchAll(/\b([A-Z][A-Z0-9_]{2,})\b/g))
        if (FLAGS[m[1]] !== undefined) flags |= FLAGS[m[1]];

    out.push({ ef_txt, flags });
}

const names = Object.keys(FLAGS).sort();
writeFileSync(join(ROOT, 'js/extcmd_data.js'),
`// GENERATED by tools/gen-extcmd.mjs from src/cmd.c extcmdlist[] — do not edit.
// C ref: src/cmd.c:1667, include/func_tab.h

export const EXTCMD_FLAGS = {
${names.map(n => `    ${n}: ${FLAGS[n]},`).join('\n')}
};

// src/cmd.c extcmdlist[] — ef_txt and flags, in table order. extcmds_match()
// walks this in order and returns the indices that matched.
export const extcmdlist = [
${out.map(e => `    { ef_txt: ${JSON.stringify(e.ef_txt)}, flags: ${e.flags} },`).join('\n')}
];
`);
console.log(`wrote ${out.length} extended commands, ${names.length} flag bits`);
