// gen-uinit.mjs — Generate js/uinit_data.js: the starting-inventory tables.
//
// src/u_init.c declares one `static const struct trobj NAME[]` per role plus a
// dozen shared extras (Lamp, Magicmarker, Blindfold, ...). ini_inv() walks
// them, and the quantities it rolls come straight out of the trquan_min /
// trquan_max fields, so the tables decide part of the PRNG stream. They are
// read from the source and resolved through the generated object tables rather
// than hand-copied.
//
// Usage: node tools/gen-uinit.mjs [--stdout]

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = fileURLToPath(new URL('..', import.meta.url));
const RECORDER = join(PROJECT_ROOT, 'nethack-c/recorder');
const OUT = join(PROJECT_ROOT, 'js/uinit_data.js');

const FIELDS = ['trotyp', 'trspe', 'trclass', 'trquan_min', 'trquan_max', 'trbless'];

function preprocessDefines() {
    /* UNDEF_TYP / UNDEF_SPE / UNDEF_BLESS live in u_init.c itself */
    const src = readFileSync(join(RECORDER, 'src/u_init.c'), 'utf8');
    const out = {};
    for (const m of src.matchAll(
        /^[ \t]*#[ \t]*define[ \t]+(UNDEF_\w+)[ \t]+(.+)$/gm)) {
        const expr = m[2].replace(/\/\*[\s\S]*?\*\//g, '').trim();
        /* these are char literals, often octal escapes like '\177' */
        const oct = /^'\\([0-7]{1,3})'$/.exec(expr);
        if (oct) { out[m[1]] = parseInt(oct[1], 8); continue; }
        const chr = /^'(.)'$/.exec(expr);
        if (chr) { out[m[1]] = chr[1].charCodeAt(0); continue; }
        // eslint-disable-next-line no-new-func
        out[m[1]] = Function(`"use strict"; return (${expr});`)();
    }
    return out;
}

// Every `static const struct trobj NAME[] = { {...}, ... };` in u_init.c.
function trobjTables(src, resolve) {
    const tables = {};
    const re = /static const struct trobj (\w+)\s*\[\s*\]\s*=\s*(?:\{|\n\s*\{)/g;
    let m;
    while ((m = re.exec(src)) !== null) {
        const name = m[1];
        const open = src.indexOf('{', m.index + m[0].length - 1);
        const close = src.indexOf('};', open);
        const body = src.slice(open + 1, close);
        const rows = [];
        for (const row of body.matchAll(/\{([^{}]*)\}/g)) {
            const vals = row[1].split(',').map(s =>
                s.replace(/\/\*[\s\S]*?\*\//g, '').trim()).filter(s => s !== '');
            if (vals.length !== FIELDS.length) continue;
            const entry = {};
            FIELDS.forEach((f, i) => { entry[f] = resolve(vals[i]); });
            rows.push(entry);
        }
        /* C terminates each table with an all-zero row; keep it, because
           ini_inv()'s loop condition is `while (trop->trclass)`. */
        tables[name] = rows;
    }
    return tables;
}

async function main() {
    if (!existsSync(RECORDER))
        throw new Error('nethack-c/recorder/ not found — run '
            + '`bash nethack-c/build-recorder.sh` first');

    const { ONAMES, OCLASSES } = await import(
        new URL('../js/objects_data.js', import.meta.url));
    const UNDEF = preprocessDefines();

    const unresolved = new Set();
    const resolve = (tok) => {
        const t = tok.trim();
        if (/^-?\d+$/.test(t)) return Number(t);
        if (t in UNDEF) return UNDEF[t];
        if (t in ONAMES) return ONAMES[t];
        if (t in OCLASSES) return OCLASSES[t];
        /* single-quoted char literal, e.g. '\0' */
        const ch = /^'(\\?.)'$/.exec(t);
        if (ch) return ch[1] === '\\0' ? 0 : ch[1].charCodeAt(0);
        unresolved.add(t);
        return t;
    };

    const src = readFileSync(join(RECORDER, 'src/u_init.c'), 'utf8');
    const tables = trobjTables(src, resolve);

    if (unresolved.size)
        throw new Error('unresolved trobj identifiers: '
            + [...unresolved].join(', '));
    if (!tables.Tourist) throw new Error('Tourist table not found');

    const out = `// uinit_data.js — GENERATED by tools/gen-uinit.mjs.
// Do not edit by hand; re-run the generator.
//
// The struct trobj tables from src/u_init.c: one per role, plus the shared
// extras a role may additionally roll (Lamp, Magicmarker, Blindfold, Leash,
// Towel, Tinopener, Xtra_food, Money, Wishing, and the three Monk spellbooks).
//
// Each row is { trotyp, trspe, trclass, trquan_min, trquan_max, trbless }, with
// every identifier resolved to its number. The all-zero terminator row is kept
// because ini_inv()'s loop condition is \`while (trop->trclass)\`.
//
// ${Object.keys(tables).length} tables.

export const UNDEF_TYP = ${UNDEF.UNDEF_TYP};
export const UNDEF_SPE = ${UNDEF.UNDEF_SPE};
export const UNDEF_BLESS = ${UNDEF.UNDEF_BLESS};

export const TROBJ = ${JSON.stringify(tables, null, 1)};
`;

    if (process.argv.includes('--stdout')) process.stdout.write(out);
    else {
        writeFileSync(OUT, out);
        console.log(`wrote ${OUT}`);
        console.log(`${Object.keys(tables).length} tables: `
            + Object.keys(tables).join(', '));
        console.log('UNDEF_TYP', UNDEF.UNDEF_TYP, 'UNDEF_SPE', UNDEF.UNDEF_SPE,
            'UNDEF_BLESS', UNDEF.UNDEF_BLESS);
    }
}

main();
