// gen-shknam.mjs — emit js/shknam_data.js from src/shknam.c.
//
// The shopkeeper name lists are ~370 strings across eleven arrays. Hand-copying
// them is exactly the drift this repo warns about, and one detail makes it
// worse than usual: nameshk() uses each list's LENGTH as the modulus of an
// rn2(), so a single dropped or duplicated name changes a draw rather than
// only a displayed name.
//
// The leading punctuation on some names is significant and is preserved
// verbatim: nameshk() and shkname() read it. '_' marks a name whose gender is
// reversed, '+' a fixed name (Izchak), '=' another marker. Do not strip it.
//
//     node tools/gen-shknam.mjs

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = fileURLToPath(new URL('..', import.meta.url));
const RECORDER = join(PROJECT_ROOT, 'nethack-c/recorder');
const UPSTREAM = join(PROJECT_ROOT, 'nethack-c/upstream');
const OUT = join(PROJECT_ROOT, 'js/shknam_data.js');

const base = existsSync(join(RECORDER, 'src/shknam.c')) ? RECORDER : UPSTREAM;
let src = readFileSync(join(base, 'src/shknam.c'), 'utf8');

/* The name lists carry #ifdef OVERLAY/WIN32/MACOS9/AMIGA/TOS/OS2/VMS blocks
   for other platforms' developers. None of those macros is defined for the
   unix tty build the recordings come from, so the names inside them do NOT
   exist at runtime — and each list's length is an rn2() modulus, so keeping
   them shifted every shopkeeper-name draw (shktools: 67 vs C's 40). */
src = src.replace(/^#ifdef \w+\n[\s\S]*?^#endif\n/gm, '');

/* static const char *const shkfoo[] = { "a", "b", 0 }; */
const lists = {};
const re = /static const char \*const (shk\w+)\[\] = \{([\s\S]*?)\n\};/g;
for (const m of src.matchAll(re)) {
    const names = [...m[2].matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((x) => x[1]);
    if (!names.length)
        throw new Error(`gen-shknam: ${m[1]} parsed empty`);
    lists[m[1]] = names;
}
if (!Object.keys(lists).length)
    throw new Error('gen-shknam: no shopkeeper name lists found');

/* Each shtypes[] entry ends with its shknms identifier, e.g. `shkgeneral },` */
const tbl = src.slice(src.indexOf('const struct shclass shtypes[] = {'));
const order = [...tbl.slice(0, tbl.indexOf('\n};')).matchAll(/\b(shk\w+)\s*\},/g)]
    .map((m) => m[1]);

let out = `// GENERATED by tools/gen-shknam.mjs — do not edit.\n`
    + `// Source: src/shknam.c shopkeeper name lists.\n`
    + `//\n`
    + `// Leading punctuation is significant and preserved verbatim; nameshk()\n`
    + `// and shkname() read it. Each list's LENGTH is an rn2() modulus.\n\n`
    + `export const SHKNAMES = {\n`;
for (const [name, names] of Object.entries(lists))
    out += `    ${name}: ${JSON.stringify(names)},\n`;
out += `};\n\n`
    + `// The shknms field of each shtypes[] entry, in table order.\n`
    + `export const SHKNMS_ORDER = ${JSON.stringify(order)};\n`;

writeFileSync(OUT, out);
const total = Object.values(lists).reduce((a, b) => a + b.length, 0);
console.log(`wrote ${OUT}`);
console.log(`  ${Object.keys(lists).length} lists, ${total} names`);
for (const [k, v] of Object.entries(lists))
    console.log(`  ${k.padEnd(16)} ${v.length}`);
console.log(`  shtypes order: ${order.join(', ')}`);
