// gen-banner.mjs — Generate js/banner_data.js: the four startup banner lines.
//
// win/tty/wintty.c:569-572 writes copyright_banner_line(1..4) at rows 4-7 of
// BASE_WINDOW before the "Who are you?" prompt, so those lines are part of
// every chargen frame in sessions that do not set !splash_screen.
//
// Every piece comes from the recorder source:
//   include/patchlevel.h  banner lines A, B and D
//   include/date.h        VERSION_STRING
//   include/global.h      PORT_ID for the build platform
//   src/date.c            the build date, which a recorder patch PINS to a
//                         constant so the banner is deterministic
//
// Usage: node tools/gen-banner.mjs

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROJECT_ROOT = fileURLToPath(new URL('..', import.meta.url));
const RECORDER = join(PROJECT_ROOT, 'nethack-c/recorder');
const OUT = join(PROJECT_ROOT, 'js/banner_data.js');

function read(rel) {
    return readFileSync(join(RECORDER, rel), 'utf8');
}

// #define NAME "literal", with C's adjacent-string concatenation.
function strDefine(text, name) {
    const re = new RegExp(
        `^[ \\t]*#[ \\t]*define[ \\t]+${name}[ \\t]*(?:\\\\\\s*\\n)?[ \\t]*((?:"(?:[^"\\\\]|\\\\.)*"[ \\t]*(?:\\\\\\s*\\n[ \\t]*)?)+)`,
        'm');
    const m = re.exec(text);
    if (!m) return null;
    return [...m[1].matchAll(/"((?:[^"\\]|\\.)*)"/g)]
        .map(x => x[1]).join('')
        .replace(/\\"/g, '"').replace(/\\\\/g, '\\');
}

function main() {
    if (!existsSync(RECORDER))
        throw new Error('nethack-c/recorder/ not found — run '
            + '`bash nethack-c/build-recorder.sh` first');

    const patch = read('include/patchlevel.h');
    const A = strDefine(patch, 'COPYRIGHT_BANNER_A');
    const B = strDefine(patch, 'COPYRIGHT_BANNER_B');
    const D = strDefine(patch, 'COPYRIGHT_BANNER_D');
    if (!A || !B || !D) throw new Error('copyright banner defines not found');

    const version = strDefine(read('include/date.h'), 'VERSION_STRING');
    if (!version) throw new Error('VERSION_STRING not found');

    /* src/date.c pins the build date so the banner is reproducible */
    const dateSrc = read('src/date.c');
    const pinned = /"([A-Z][a-z]{2} [ 0-9]\d \d{4} \d\d:\d\d:\d\d)"/.exec(dateSrc);
    if (!pinned) throw new Error('pinned build date not found in src/date.c');

    /* include/global.h picks PORT_ID by platform; the recorder is a mac build */
    const globalSrc = read('include/global.h');
    const portBlock = /#\s*ifdef\s+MACOSX[\s\S]{0,200}?#\s*define\s+PORT_ID\s+"([^"]+)"/
        .exec(globalSrc);
    const PORT_ID = portBlock ? portBlock[1] : 'MacOS';

    /* src/mdlib.c bannerc_string():
         "         Version %s %s%s, %s %s." */
    const C = `         Version ${version} ${PORT_ID}, built ${pinned[1]}.`;

    const out = `// banner_data.js — GENERATED by tools/gen-banner.mjs.
// Do not edit by hand; re-run the generator.
//
// The four startup banner lines, composed exactly as src/mdlib.c
// bannerc_string() and include/patchlevel.h do. win/tty/wintty.c writes them at
// rows 4-7 before the "Who are you?" prompt, so they are on every chargen frame.
//
// The build date is a constant because a recorder patch pins it (src/date.c);
// without that the banner would differ from the recording on every rebuild.

export const COPYRIGHT_BANNER = ${JSON.stringify([A, B, C, D], null, 1)};
`;
    writeFileSync(OUT, out);
    console.log(`wrote ${OUT}`);
    for (const l of [A, B, C, D]) console.log(`  ${JSON.stringify(l)}`);
}

main();
