#!/usr/bin/env node
// gen-drawing.mjs — emit js/drawing_data.js from include/defsym.h
//
// src/drawing.c's def_monsyms[] and def_oc_syms[] are not literal tables: they
// are built by including defsym.h with a MONSYM/OBJCLASS macro defined to pick
// out the fields it wants. The data itself lives in defsym.h as
//
//     MONSYM( 1, 'a', ANT, S_ANT,   "ant or other insect")
//     OBJCLASS( 2,  ')', WEAPON, S_weapon, "weapons", "weapon")
//
// newsym() needs the CHARACTER for a monster's class and an object's class, and
// getting one wrong shows the wrong glyph on every frame that monster or object
// appears on. Five separate bugs in this port came from tables typed by hand
// (oc_prob, the G_ flags, SPBOOK_no_NOVEL, MR_POISON, M3_ZOMBIFIER), so this one
// is scraped.
//
// Usage: node tools/gen-drawing.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = join(ROOT, 'nethack-c/upstream/include/defsym.h');
const OUT = join(ROOT, 'js/drawing_data.js');

const src = readFileSync(SRC, 'utf8');

/* A C character literal: 'a', ']', '\\' or '\''. */
const CH = String.raw`'(\\.|[^'\\])'`;

function scrape(re) {
    const out = [];
    let m;
    while ((m = re.exec(src)) !== null) {
        const idx = Number(m[1]);
        let ch = m[2].slice(1, -1);
        if (ch.startsWith('\\')) ch = ({ '\\\\': '\\', "\\'": "'" })[ch] ?? ch[1];
        out.push({ idx, ch, basename: m[3], sym: m[4] });
    }
    return out;
}

/* Only the indented invocations carry data; the #define lines above them name
   the same macro with its parameter list and must not be matched.
   Coins use OBJCLASS2, which carries an extra field (GOLD_SYM) between the
   basename and the symbol name — matching only OBJCLASS() silently left index
   12 empty and drew gold as '?'. */
const monsyms = scrape(
    new RegExp(String.raw`^\s+MONSYM\(\s*(\d+),\s*(${CH}),\s*(\w+),\s*(\w+)`, 'gm'));

/* the MONSYM explanation strings ("human or elf"), for farlook */
const monexplain = [];
{
    const re = new RegExp(
        String.raw`^\s+MONSYM\(\s*(\d+),\s*${CH},\s*\w+,\s*\w+,\s*"([^"]*)"`, 'gm');
    let m;
    while ((m = re.exec(src)) !== null)
        monexplain[Number(m[1])] = m[m.length - 1];
}
const oclasses = [
    ...scrape(new RegExp(
        String.raw`^\s+OBJCLASS\(\s*(\d+),\s*(${CH}),\s*(\w+),\s*(\w+)`, 'gm')),
    ...scrape(new RegExp(
        String.raw`^\s+OBJCLASS2\(\s*(\d+),\s*(${CH}),\s*(\w+),\s*\w+,\s*(\w+)`, 'gm')),
].sort((a, b) => a.idx - b.idx);

if (!monsyms.length || !oclasses.length) {
    console.error('scrape found nothing — defsym.h layout changed');
    process.exit(2);
}

const table = (rows) => {
    const max = Math.max(...rows.map(r => r.idx));
    const arr = new Array(max + 1).fill('');
    for (const r of rows) arr[r.idx] = r.ch;
    return arr;
};

const body = `// drawing_data.js — GENERATED by tools/gen-drawing.mjs. Do not edit.
// Source: include/defsym.h, the MONSYM() and OBJCLASS() invocations that
// src/drawing.c expands into def_monsyms[] and def_oc_syms[].
//
// Indexed by class number, so def_monsyms[mlet] and def_oc_syms[oclass] give
// the character newsym() should show. Index 0 is the "random class" placeholder
// in both and is deliberately empty.

// ${monsyms.length} monster classes
export const def_monsyms = ${JSON.stringify(table(monsyms))};

// ${oclasses.length} object classes
export const def_oc_syms = ${JSON.stringify(table(oclasses))};

// symbol name -> class index, for reading SYMBOLS= lines from an rc
export const monsym_names = ${JSON.stringify(
    Object.fromEntries(monsyms.map(r => [r.sym, r.idx])), null, 1)};

export const oclass_names = ${JSON.stringify(
    Object.fromEntries(oclasses.map(r => [r.sym, r.idx])), null, 1)};

// MONSYM explanation strings, indexed like def_monsyms ("human or elf");
// src/pager.c do_screen_description reads these for farlook
export const monexplain = ${JSON.stringify(monexplain)};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${monsyms.length} monster classes, `
            + `${oclasses.length} object classes`);
