#!/usr/bin/env node
// gen-skills.mjs — emit js/skills_data.js from src/u_init.c's Skill_X[] tables.
//
// Each role has a table naming every weapon and spell school it may train and
// the cap it may train to:
//
//     static const struct def_skill Skill_A[] = {
//         { P_DAGGER, P_BASIC },
//         ...
//         { P_NONE, 0 }
//     };
//
// restricted_spell_discipline() walks the table for the current role and
// refuses any spellbook whose oc_skill is absent from it, so a single missing
// row changes how many times ini_inv_mkobj_filter() retries and shifts every
// draw after the starting inventory. skill_init() will need the same tables.
//
// Usage: node tools/gen-skills.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SRC = join(ROOT, 'nethack-c/upstream/src/u_init.c');
const OUT = join(ROOT, 'js/skills_data.js');

const src = readFileSync(SRC, 'utf8');

/* The tables. Name them by their C identifier so a grep for Skill_Mon finds
   this file, and keep the P_ symbols as written rather than resolving them to
   numbers — const.js already holds the numbers and resolving here would put a
   second copy of skills.h in the tree. */
const tables = {};
const tableRe = /static const struct def_skill (Skill_\w+)\[\] = \{([\s\S]*?)\n\};/g;
let m;
while ((m = tableRe.exec(src)) !== null) {
    const rows = [];
    const rowRe = /\{\s*(P_\w+)\s*,\s*(P_\w+|\d+)\s*\}/g;
    let r;
    while ((r = rowRe.exec(m[2])) !== null) rows.push([r[1], r[2]]);
    tables[m[1]] = rows;
}

/* skills_for_role()'s switch: PM_ROLE -> Skill_X. Scraped rather than typed
   because the mapping is not guessable from the names (PM_CLERIC uses Skill_P,
   PM_MONK uses Skill_Mon, PM_CAVE_DWELLER uses Skill_C). */
const forRole = {};
/* Anchor on the definition, not the forward declaration a few hundred lines
   above it — matching the prototype makes the lazy [\s\S]*? run to the end of
   some unrelated function and find no cases at all. */
const swBody = src.match(/skills_for_role\(void\)\n\{[\s\S]*?\n\}/)[0];
const caseRe = /case (PM_\w+):\s*\n\s*skills = (Skill_\w+);/g;
while ((m = caseRe.exec(swBody)) !== null) forRole[m[1]] = m[2];

if (Object.keys(tables).length < 13 || Object.keys(forRole).length < 13) {
    console.error(`scrape found ${Object.keys(tables).length} tables and `
                  + `${Object.keys(forRole).length} roles — u_init.c layout changed`);
    process.exit(2);
}

const lines = [];
for (const [name, rows] of Object.entries(tables)) {
    lines.push(`export const ${name} = [`);
    for (const [skill, cap] of rows) lines.push(`    [${skill}, ${cap}],`);
    lines.push('];');
    lines.push('');
}

const imports = [...new Set(
    Object.values(tables).flat().flat().filter(s => s.startsWith('P_')))].sort();

writeFileSync(OUT, `// skills_data.js — GENERATED by tools/gen-skills.mjs. Do not edit.
// Source: src/u_init.c, the static const struct def_skill Skill_X[] tables and
// the skills_for_role() switch that selects between them.
//
// Each row is [skill, cap]: which weapon or spell school the role may train,
// and how far. The trailing { P_NONE, 0 } terminator is kept, because C's
// callers loop "while (skills->skill != P_NONE)" and dropping it would change
// where they stop.

import {
${imports.map(s => `    ${s},`).join('\n')}
} from './const.js';

${lines.join('\n')}// src/u_init.c skills_for_role() — role number to table.
export const skill_tables = {
${Object.entries(forRole).map(([pm, t]) => `    ${JSON.stringify(pm)}: ${t},`).join('\n')}
};
`);

console.log(`wrote ${OUT}: ${Object.keys(tables).length} tables, `
            + `${Object.values(tables).flat().length} rows, `
            + `${Object.keys(forRole).length} roles`);
